table Sales_Ledger
	lineageTag: f2dcd85a-4ac9-4a1b-8929-209d15f65acb

	column 'Order Company'
		dataType: string
		lineageTag: 6296337e-2f88-4e6b-a097-f206bb03c9f2
		summarizeBy: none
		sourceColumn: Order Company

		annotation SummarizationSetBy = Automatic

	column 'Order Number'
		dataType: int64
		formatString: 0
		lineageTag: c53715b6-6570-489c-bfa1-f5d67914089b
		summarizeBy: none
		sourceColumn: Order Number

		annotation SummarizationSetBy = Automatic

	column 'Line Number'
		dataType: double
		lineageTag: 2c023122-463f-473d-95b8-2a32cb7bcc44
		summarizeBy: none
		sourceColumn: Line Number

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column '2nd Item Number'
		dataType: string
		lineageTag: b732944f-e4af-4ae7-90c4-426107219803
		summarizeBy: none
		sourceColumn: 2nd Item Number

		annotation SummarizationSetBy = Automatic

	column 'Ordered Date'
		dataType: dateTime
		formatString: d MMM, yyyy
		lineageTag: fb5fafae-5813-4692-9ec2-772a1679f1c8
		summarizeBy: none
		sourceColumn: Ordered Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Date Created'
		dataType: dateTime
		formatString: d MMM, yyyy
		lineageTag: fe14ac7c-ce72-456c-bdc9-faca111767c3
		summarizeBy: none
		sourceColumn: Date Created

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Last Status'
		dataType: string
		lineageTag: fad07b42-2f92-4dbf-9ea4-832b2739ec63
		summarizeBy: none
		sourceColumn: Last Status

		annotation SummarizationSetBy = Automatic

	column 'Next Status'
		dataType: string
		lineageTag: e62451c9-d156-4dd1-ae2f-3d72ebecae2a
		summarizeBy: none
		sourceColumn: Next Status

		annotation SummarizationSetBy = Automatic

	column 'Order Line Last Updated'
		dataType: dateTime
		formatString: d MMM, yyyy h:mm
		lineageTag: 53af6eec-315a-4ddc-83a8-9447fe4fae5a
		summarizeBy: none
		sourceColumn: Order Line Last Updated

		annotation SummarizationSetBy = Automatic

	column 'Order Line Last Updated By'
		dataType: string
		lineageTag: 6d7d03f4-c2dd-4a9a-b907-d3ba25546155
		summarizeBy: none
		sourceColumn: Order Line Last Updated By

		annotation SummarizationSetBy = Automatic

	partition Sales_Ledger = m
		mode: import
		source =
				let
				    Source = Sql.Database("ODSPROD", "ODS"),
				    Data = Value.NativeQuery(
				        Source,
				        "
				        SELECT DISTINCT
				            LTRIM(RTRIM(l.SLKCOO))            AS [Order Company],
				            l.SLDOCO                          AS [Order Number],
				            l.SLLNID / 1000.0                 AS [Line Number],
				            LTRIM(RTRIM(l.SLLITM))            AS [2nd Item Number],
				            CASE WHEN o.SDTRDJ>0 THEN DATEADD(DAY,(o.SDTRDJ%1000)-1,DATEFROMPARTS(1900+(o.SDTRDJ/1000),1,1)) END AS [Ordered Date],
				            CASE WHEN l.SLUPMJ>0 THEN DATEADD(DAY,(l.SLUPMJ%1000)-1,DATEFROMPARTS(1900+(l.SLUPMJ/1000),1,1)) END AS [Date Created],
				            l.SLLTTR                          AS [Last Status],
				            l.SLNXTR                          AS [Next Status],
				            CASE WHEN l.SLUPMJ>0 THEN
				                DATEADD(SECOND,
				                        (l.SLTDAY/10000)*3600 + ((l.SLTDAY/100)%100)*60 + (l.SLTDAY%100),
				                        CAST(DATEADD(DAY,(l.SLUPMJ%1000)-1,DATEFROMPARTS(1900+(l.SLUPMJ/1000),1,1)) AS datetime2))
				            END                               AS [Order Line Last Updated],
				            LTRIM(RTRIM(l.SLUSER))            AS [Order Line Last Updated By]
				        FROM PRODDTA.F42199 l
				        JOIN (
				            SELECT SDKCOO, SDDOCO, SDDCTO, SDLNID, SDMCU, SDLITM, SDTRDJ
				            FROM PRODDTA.F4211
				            UNION ALL
				            SELECT h.SDKCOO, h.SDDOCO, h.SDDCTO, h.SDLNID, h.SDMCU, h.SDLITM, h.SDTRDJ
				            FROM PRODDTA.F42119 h
				            WHERE NOT EXISTS (SELECT 1 FROM PRODDTA.F4211 c
				                              WHERE c.SDKCOO = h.SDKCOO AND c.SDDOCO = h.SDDOCO
				                                AND c.SDDCTO = h.SDDCTO AND c.SDLNID = h.SDLNID)
				        ) o   ON o.SDKCOO = l.SLKCOO AND o.SDDOCO = l.SLDOCO
				             AND o.SDDCTO = l.SLDCTO AND o.SDLNID = l.SLLNID
				        JOIN PRODDTA.F4102 it ON LTRIM(RTRIM(o.SDMCU))  = LTRIM(RTRIM(it.IBMCU))
				                            AND LTRIM(RTRIM(o.SDLITM)) = LTRIM(RTRIM(it.IBLITM))
				        LEFT JOIN PRODDTA.F4101 im   ON it.IBITM = im.IMITM
				        LEFT JOIN PRODDTA.F554101 tag ON im.IMITM = tag.IMITM
				        WHERE CASE WHEN o.SDTRDJ>0 THEN DATEADD(DAY,(o.SDTRDJ%1000)-1,DATEFROMPARTS(1900+(o.SDTRDJ/1000),1,1)) END >= '2024-01-01'
				          AND LTRIM(RTRIM(l.SLKCOO)) = '00010'
				          AND LTRIM(RTRIM(l.SLNXTR)) IN ('520','525','530')
				          AND LTRIM(RTRIM(l.SLUSER)) <> 'SCHED'
				          AND CASE WHEN ISNULL(LTRIM(RTRIM(tag.IMGBLK)),'-')='-'
				                   THEN LTRIM(RTRIM(o.SDLITM)) ELSE LTRIM(RTRIM(tag.IMGBLK)) END
				              NOT IN ('IGST','CGST','SGST','CVD','ADD')
				        ",
				        null,
				        [EnableFolding = true]
				    ),
				    Typed = Table.TransformColumnTypes(
				        Data,
				        {
				            {"Order Company", type text},
				            {"Order Number", Int64.Type},
				            {"Line Number", type number},
				            {"2nd Item Number", type text},
				            {"Ordered Date", type date},
				            {"Date Created", type date},
				            {"Last Status", type text},
				            {"Next Status", type text},
				            {"Order Line Last Updated", type datetime},
				            {"Order Line Last Updated By", type text}
				        },
				        "en-US"
				    )
				in
				    Typed

	annotation PBI_ResultType = Table

