INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('A1', 'Assigning Lot Number', 10, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('A2', 'Schedule pick date change', 20, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('A3', 'do not use', 30, 0);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('A31', 'CSR - no impact', 40, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('A32', 'FMB - no impact', 50, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('A33', 'RM issue - no impact', 60, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('A34', 'Equipment Issues - no impact', 70, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('A35', 'Capacity Issues - no impact', 80, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('A36', 'Labor Issues / RH - no impact', 90, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('A4', 'Logistic review', 100, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('A5', 'Int''l. Doc. Conv. Cor.', 110, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('A6', 'Scheduler Assign Dates', 120, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('C0', 'No effect / Pas effet client', 130, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('C1', 'Credit Hold / Paiement', 140, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('C2', 'Cust Req / Demande client', 150, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('C3', 'Branch Plant Change', 160, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('C4', 'Groupage', 170, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('C5', 'Order Entry Error / CSR', 180, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('C6', 'Communication', 190, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('C7', 'Customer Supplied Raw Mat.', 200, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('F1', 'FMB / Scale Up Issues', 210, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('L1', 'Incorrect Item Set Up in JDE', 220, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('L2', 'Raw Material not ordered / RM', 230, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('LFC', 'RM not orderd due to incorrect FCST', 240, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('L3', 'RM Delivery Issue / qt RM', 250, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('LIC', 'Intercompany', 260, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('LCM', 'CM', 270, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('L4', 'Shipping Error', 280, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('L5', 'Weather/Storm Related Delays', 290, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('LQW', 'Lower Quality Sales', 300, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('P3', 'Equipment Issues', 310, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('P4', 'Capacity Issues / capacite', 320, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('P5', 'Labor Issues / RH', 330, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('P6', 'SS Shortage / Inv Issues', 340, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('P7', 'Intermediate Delay', 350, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('P8', 'Lead Time Delay', 360, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('P9', 'Pilot Plant Lead Time Delay', 370, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('PD1', '1st Prod Delay / delai prod', 380, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('PD2', '2nd Prod Delay / delai prod', 390, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('PD3', 'Multiple Production Delays', 400, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('Q1', 'Non Conf Batch / Non FTRB', 410, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('Q2', 'RM Qual Issue / qualite RM', 420, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('SS', 'Ship Short', 430, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('T0', 'MM Carrier Issues / logistique (No OTIF)', 440, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('T1', 'MM Carrier Issues / logistique', 450, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('T2', 'Cust Carrier issues / EXW', 460, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('T3', 'MM Carrier Weather Delay', 470, 1);
INSERT OR IGNORE INTO dropdown_reason_codes (code, label, sort_order, active) VALUES ('T4', 'Tanker Line Full', 480, 1);