
select distinct "BILL_OF_MATERIAL"."BRANCH_PLANT" "Branch_Plant"
 from ("DW_LEGACY"."ORGANIZATION" "ORGANIZATION_ALIAS" INNER JOIN "DW_LEGACY"."ITEM" "ITEM" on "ORGANIZATION_ALIAS"."ORGANIZATION_DIM_ID"="ITEM"."BRANCH_PLANT") LEFT OUTER JOIN "DW_LEGACY"."BILL_OF_MATERIAL" "BILL_OF_MATERIAL" on "ITEM"."ITEM_SID"="BILL_OF_MATERIAL"."BILL_OF_MATERIAL_KIT__IT_SID"
 where "BILL_OF_MATERIAL"."TYPE_OF_BILL"=N'M' and "ITEM"."STOCK_TYPE_CODE"=N'M' and "BILL_OF_MATERIAL"."EFFETIVE_THROUGH_DATE">SYSDATE and "ORGANIZATION_ALIAS"."BRANCH_TYPE"<>N'LAB'



