table 'P15 Cost Source'
	lineageTag: 18001000-0000-4000-8000-000000000001

	column k_date
		dataType: string
		lineageTag: 18001001-0000-4000-8000-000000000001
		summarizeBy: none
		sourceColumn: k_date

		annotation SummarizationSetBy = Automatic

	column bu
		dataType: string
		lineageTag: 18001001-0000-4000-8000-000000000002
		summarizeBy: none
		sourceColumn: bu

		annotation SummarizationSetBy = Automatic

	column item2
		dataType: string
		lineageTag: 18001001-0000-4000-8000-000000000003
		summarizeBy: none
		sourceColumn: item2

		annotation SummarizationSetBy = Automatic

	column lot
		dataType: string
		lineageTag: 18001001-0000-4000-8000-000000000004
		summarizeBy: none
		sourceColumn: lot

		annotation SummarizationSetBy = Automatic

	column cost_method
		dataType: string
		lineageTag: 18001001-0000-4000-8000-000000000005
		summarizeBy: none
		sourceColumn: cost_method

		annotation SummarizationSetBy = Automatic

	column snap_unit
		dataType: double
		lineageTag: 18001001-0000-4000-8000-000000000006
		summarizeBy: none
		sourceColumn: snap_unit

		annotation SummarizationSetBy = User

	column costhist_unit
		dataType: double
		lineageTag: 18001001-0000-4000-8000-000000000007
		summarizeBy: none
		sourceColumn: costhist_unit

		annotation SummarizationSetBy = User

	column qoh
		dataType: double
		lineageTag: 18001001-0000-4000-8000-000000000008
		summarizeBy: none
		sourceColumn: qoh

		annotation SummarizationSetBy = User

	column fx_rate
		dataType: double
		lineageTag: 18001001-0000-4000-8000-000000000009
		summarizeBy: none
		sourceColumn: fx_rate

		annotation SummarizationSetBy = User

	column costhist_usd
		dataType: double
		lineageTag: 18001001-0000-4000-8000-00000000000a
		summarizeBy: none
		sourceColumn: costhist_usd

		annotation SummarizationSetBy = User

	column cognos_usd
		dataType: double
		lineageTag: 18001001-0000-4000-8000-00000000000b
		summarizeBy: none
		sourceColumn: cognos_usd

		annotation SummarizationSetBy = User

	partition 'P15 Cost Source' = m
		mode: import
		source =
				let
				    Source = Sql.Database("EDWPROD", "EDW"),
				    Data = Value.NativeQuery(
				        Source,
				        "
				        SET NOCOUNT ON;
				        SELECT k.d AS k_date, k.bu, k.item2, k.lot,
				               LTRIM(RTRIM(ic.CostMethod)) AS cost_method,
				               snap.AmountUnitCost AS snap_unit,
				               ic.AmountUnitCost AS costhist_unit,
				               snap.QuantityOnHandPrimaryUOM AS qoh,
				               CASE WHEN co.CurrencyCode = 'USD' THEN 1.0 ELSE fx.[Exchange Rate] END AS fx_rate,
				               snap.QuantityOnHandPrimaryUOM * ic.AmountUnitCost
				                   * CASE WHEN co.CurrencyCode = 'USD' THEN 1.0 ELSE fx.[Exchange Rate] END AS costhist_usd,
				               k.cognos AS cognos_usd
				        FROM (VALUES
				            ('2026-03-18','SING','104DPM.S','617059', 16.2),
				            ('2026-03-18','SING','104PA.S','611047', 1371.709728),
				            ('2026-03-18','CIN2','100FGK','617238', 23919.18),
				            ('2026-03-18','AUB2','127PAR.E','618031', 17134.383984),
				            ('2026-03-18','AUBA','104DPM.E','603660', 3224.534461204)
				        ) k(d, bu, item2, lot, cognos)
				        JOIN BIQL.DimItem it ON it.ItemNum2nd = k.item2
				        JOIN dbo.FactInventorySnapshot_History snap
				             ON snap.ItemSKey = it.ItemSKey
				            AND LTRIM(RTRIM(snap.BusinessUnit)) = k.bu
				            AND LTRIM(RTRIM(snap.LotNum)) = k.lot
				            AND (CASE WHEN snap.CompanySKey = 2 THEN DATEADD(DAY,1,CAST(k.d AS date)) ELSE CAST(k.d AS date) END)
				                BETWEEN snap.StartDate AND ISNULL(snap.StopDate,'9999-12-31')
				        JOIN BIQL.DimCompany co ON co.CompanySKey = snap.CompanySKey
				        LEFT JOIN BIQL.DimCurrencyExchangeRatesUSDDaily fx
				               ON fx.CurrencyCodeFrom = co.CurrencyCode AND fx.CalendarDate = CAST(k.d AS date)
				        LEFT JOIN dbo.DimItemCost_History ic
				               ON ic.ItemNumShort = snap.ItemNumShort
				              AND ic.BusinessUnit = snap.BusinessUnit
				              AND LTRIM(RTRIM(ic.LotNum)) = k.lot
				              AND ic.CostMethod = '07'
				              AND CAST(k.d AS date) BETWEEN ic.StartDate AND ISNULL(ic.StopDate,'9999-12-31')
				        ",
				        null,
				        [EnableFolding = false]
				    ),
				    Typed = Table.TransformColumnTypes(Data, {
							{"k_date", type text}, {"bu", type text}, {"item2", type text},
							{"lot", type text}, {"cost_method", type text},
							{"snap_unit", type number}, {"costhist_unit", type number}, {"qoh", type number},
							{"fx_rate", type number}, {"costhist_usd", type number}, {"cognos_usd", type number}
				    }, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table
