table 'P16 Cost Lookup'
	lineageTag: 18001100-0000-4000-8000-000000000001

	column bu
		dataType: string
		lineageTag: 18001101-0000-4000-8000-000000000001
		summarizeBy: none
		sourceColumn: bu

		annotation SummarizationSetBy = Automatic

	column item2
		dataType: string
		lineageTag: 18001101-0000-4000-8000-000000000002
		summarizeBy: none
		sourceColumn: item2

		annotation SummarizationSetBy = Automatic

	column lot
		dataType: string
		lineageTag: 18001101-0000-4000-8000-000000000003
		summarizeBy: none
		sourceColumn: lot

		annotation SummarizationSetBy = Automatic

	column item_cost_skey
		dataType: int64
		lineageTag: 18001101-0000-4000-8000-000000000004
		summarizeBy: none
		sourceColumn: item_cost_skey

		annotation SummarizationSetBy = Automatic

	column snap_unit
		dataType: double
		lineageTag: 18001101-0000-4000-8000-000000000005
		summarizeBy: none
		sourceColumn: snap_unit

		annotation SummarizationSetBy = User

	column qoh
		dataType: double
		lineageTag: 18001101-0000-4000-8000-000000000006
		summarizeBy: none
		sourceColumn: qoh

		annotation SummarizationSetBy = User

	column cognos_usd
		dataType: double
		lineageTag: 18001101-0000-4000-8000-000000000007
		summarizeBy: none
		sourceColumn: cognos_usd

		annotation SummarizationSetBy = User

	column costlookup_hist_json
		dataType: string
		lineageTag: 18001101-0000-4000-8000-000000000008
		summarizeBy: none
		sourceColumn: costlookup_hist_json

		annotation SummarizationSetBy = Automatic

	column costlookup_cur_json
		dataType: string
		lineageTag: 18001101-0000-4000-8000-000000000009
		summarizeBy: none
		sourceColumn: costlookup_cur_json

		annotation SummarizationSetBy = Automatic

	partition 'P16 Cost Lookup' = m
		mode: import
		source =
				let
				    Source = Sql.Database("EDWPROD", "EDW"),
				    Data = Value.NativeQuery(
				        Source,
				        "
				        SET NOCOUNT ON;
				        SELECT k.bu, k.item2, k.lot,
				               snap.ItemCostSKey AS item_cost_skey,
				               snap.AmountUnitCost AS snap_unit,
				               snap.QuantityOnHandPrimaryUOM AS qoh,
				               k.cognos AS cognos_usd,
				               (SELECT clh.* FROM BIQL.FactInventorySnapshotItemCostLookup_History clh
				                 WHERE clh.ItemCostSKey = snap.ItemCostSKey FOR JSON PATH) AS costlookup_hist_json,
				               (SELECT clc.* FROM BIQL.FactInventorySnapshotItemCostLookup clc
                                 WHERE clc.ItemCostSKey = snap.ItemCostSKey FOR JSON PATH) AS costlookup_cur_json
				        FROM (VALUES
				            ('2026-03-18','SING','104DPM.S','617059','B01', 16.2),
				            ('2026-03-18','SING','104PA.S','611047','RM1', 1371.709728),
				            ('2026-03-18','CIN2','100FGK','617238','F43', 23919.18),
				            ('2026-03-18','AUB2','127PAR.E','618031','JOST', 17134.383984),
				            ('2026-03-18','AUBA','104DPM.E','603660','ACD0208', 3224.534461204)
				        ) k(d, bu, item2, lot, loc, cognos)
				        JOIN BIQL.DimItem it ON it.ItemNum2nd = k.item2
				        JOIN dbo.FactInventorySnapshot_History snap
				             ON snap.ItemSKey = it.ItemSKey
				            AND LTRIM(RTRIM(snap.BusinessUnit)) = k.bu
				            AND LTRIM(RTRIM(snap.LotNum)) = k.lot
				            AND LTRIM(RTRIM(snap.Location)) = k.loc
				            AND (CASE WHEN snap.CompanySKey = 2 THEN DATEADD(DAY,1,CAST(k.d AS date)) ELSE CAST(k.d AS date) END)
				                BETWEEN snap.StartDate AND ISNULL(snap.StopDate,'9999-12-31')
				        ",
				        null,
				        [EnableFolding = false]
				    ),
				    Typed = Table.TransformColumnTypes(Data, {
							{"bu", type text}, {"item2", type text}, {"lot", type text},
							{"item_cost_skey", Int64.Type}, {"snap_unit", type number}, {"qoh", type number},
							{"cognos_usd", type number}, {"costlookup_hist_json", type text}, {"costlookup_cur_json", type text}
				    }, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table
