EVALUATE
VAR Bulks = { "161017CX", "161190PX", "171143PX", "171228PX.E", "181020CX.E", "181136IX", "181192IX", "181193EU.E", "191011CX", "191026CX.E", "191245PX", "23409A", "ABEX2525", "APT10", "APT11", "DMAEMA", "EMA3065", "ET2012.E", "ET2022.E", "ET4075.E", "ET440.E", "FERSUL7W", "HP1432AT", "HP1632", "MD4020", "MD4020C", "MD4020S", "MD4021", "MD4021C", "MD4021S", "MD4022", "MD4022C", "MD4023", "MD4023C", "MDU20", "MDU2012.E", "MDU2012B.E", "MDU4075.E", "MDU4075B.E", "MDU440.E", "MDU440B.E", "MPEG2000", "MW40504", "MW40514", "NP4LF", "NP4LF.S", "OMS", "PUD1.E", "STODSO", "U1001", "U101", "U201", "U2022", "U2022EU.E", "U2023", "U204", "U204EU.E", "U470", "U501", "U501B", "U502", "U502.E", "U502X1.E", "U601", "U701", "U802", "U802.E", "WAV501", "WD40", "WD40T" }
VAR PartsLines =
    ADDCOLUMNS (
        FILTER (
            'Work Order Parts List',
            TRIM ( RELATED ( 'Item Branch'[Item Bulk] ) ) IN Bulks
                && 'Work Order Parts List'[QuantityOrdered] + 'Work Order Parts List'[QuantityTransaction] > 0
                && ( RELATED ( 'Work Order'[Start Date] ) >= DATE ( 2020, 1, 1 ) || RELATED ( 'Work Order'[Completed Date] ) >= DATE ( 2020, 1, 1 ) )
                && RELATED ( 'Work Order'[Work Order Type] ) = "WO"
        ),
        "@ParentItemBranchSKey", LOOKUPVALUE ( 'Work Order Detail'[ItemBranchSKey], 'Work Order Detail'[WorkOrderSKey], 'Work Order Parts List'[WorkOrderSKey] ),
        "@ParentBranchSKey", LOOKUPVALUE ( 'Work Order Detail'[BranchSKey], 'Work Order Detail'[WorkOrderSKey], 'Work Order Parts List'[WorkOrderSKey] ),
        "@CompletionDate", IF ( RELATED ( 'Work Order'[Completed Date] ) <= DATE ( 1900, 12, 31 ), BLANK (), RELATED ( 'Work Order'[Completed Date] ) )
    )
RETURN
    SELECTCOLUMNS (
        PartsLines,
        "Branch Plant", LOOKUPVALUE ( Branch[Branch Plant], Branch[BranchSKey], [@ParentBranchSKey] ),
        "Global Bulk Item", LOOKUPVALUE ( 'Item Branch'[Item Global Bulk], 'Item Branch'[ItemBranchSKey], [@ParentItemBranchSKey] ),
        "Bulk Item", LOOKUPVALUE ( 'Item Branch'[Item Bulk], 'Item Branch'[ItemBranchSKey], [@ParentItemBranchSKey] ),
        "2nd Item Number", RELATED ( 'Work Order'[Parent Item Num 2nd] ),
        "WO Number", RELATED ( 'Work Order'[Work Order Num] ),
        "Start Date", RELATED ( 'Work Order'[Start Date] ),
        "Completion Date", [@CompletionDate],
        "Year", YEAR ( [@CompletionDate] ),
        "Month", MONTH ( [@CompletionDate] ),
        "WO Status", RELATED ( 'Work Order'[Work Order Status] ),
        "Component Branch Plant", TRIM ( 'Work Order Parts List'[BusinessUnit] ),
        "Component 2nd Item Number", 'Work Order Parts List'[Component Item Num 2nd],
        "Component UOM", 'Work Order Parts List'[UOM],
        "Issued Quantity (Line)", 'Work Order Parts List'[QuantityTransaction],
        "Quantity Ordered (Line)", 'Work Order Parts List'[QuantityOrdered],
        "Component Global Bulk Item", RELATED ( 'Item Branch'[Item Global Bulk] ),
        "Component Bulk Item", RELATED ( 'Item Branch'[Item Bulk] ),
        "Component Item 2nd Item Number", RELATED ( 'Item Branch'[Item Num 2nd] ),
        "Stock Type Code", RELATED ( 'Item Branch'[Stocking Type] )
    )
