table 'PO Receipts'
	lineageTag: eef843c4-6424-4f0b-a9ea-92bf42fde3d6

	column 'Line Key'
		dataType: string
		lineageTag: 10246d01-9396-4596-b499-fa25b028336b
		summarizeBy: none
		sourceColumn: Line Key

		annotation SummarizationSetBy = Automatic

	column 'Receipt Date'
		dataType: dateTime
		formatString: MMM d, yyyy
		lineageTag: cbc24a86-86fc-462a-9428-8d3c5f7b9043
		summarizeBy: none
		sourceColumn: Receipt Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'PO Receipts' = m
		mode: import
		source =
				let
				    Source = Sql.Database("ODSPROD", "ODS"),
				    Data = Value.NativeQuery(
				        Source,
				        "
				        SELECT
				            LTRIM(RTRIM(r.PRKCOO)) + '|' + CAST(r.PRDOCO AS varchar(20)) + '|' + LTRIM(RTRIM(r.PRDCTO)) + '|' + CAST(r.PRLNID AS varchar(20)) AS [Line Key],
				            MAX(CASE WHEN r.PRRCDJ>0 THEN DATEADD(DAY,(r.PRRCDJ%1000)-1,DATEFROMPARTS(1900+(r.PRRCDJ/1000),1,1)) END) AS [Receipt Date]
				        FROM PRODDTA.F43121 r
				        WHERE EXISTS (SELECT 1 FROM PRODDTA.F4311 d
				                      WHERE d.PDKCOO = r.PRKCOO AND d.PDDOCO = r.PRDOCO
				                        AND d.PDDCTO = r.PRDCTO AND d.PDLNID = r.PRLNID
				                        AND LTRIM(RTRIM(d.PDMCU)) IN ('CINC','CIN2','CIN4')
				                        AND LTRIM(RTRIM(d.PDDCTO)) IN ('OP','OD'))
				        GROUP BY LTRIM(RTRIM(r.PRKCOO)), r.PRDOCO, LTRIM(RTRIM(r.PRDCTO)), r.PRLNID
				        ",
				        null,
				        [EnableFolding = true]
				    ),
				    Typed = Table.TransformColumnTypes(
				        Data,
				        {
				            {"Line Key", type text},
				            {"Receipt Date", type date}
				        },
				        "en-US"
				    )
				in
				    Typed

	annotation PBI_ResultType = Table

