table Sales_Orders_Static
	lineageTag: ac3cccf5-4973-4795-b4d4-2b417d89ebeb

	column 'Order Number'
		dataType: int64
		formatString: 0
		lineageTag: 8bcf848e-d16f-4739-a4bd-c834503d354c
		summarizeBy: none
		sourceColumn: Order Number

		annotation SummarizationSetBy = Automatic

	column 'Line Number'
		dataType: double
		lineageTag: e220d660-0959-4790-b605-9eca07b4c4b5
		summarizeBy: none
		sourceColumn: Line Number

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Ordered Date'
		dataType: dateTime
		formatString: d MMM, yyyy
		lineageTag: 0f5f10a9-ae3a-4ba8-9b67-0ecc7261d1d5
		summarizeBy: none
		sourceColumn: Ordered Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Promised Ship Date'
		dataType: dateTime
		formatString: d MMM, yyyy
		lineageTag: 5f73b020-4d52-430b-901b-cc2705077ef1
		summarizeBy: none
		sourceColumn: Promised Ship Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Customer Name'
		dataType: string
		lineageTag: 1bed8bf0-51e1-4a26-866c-2eeb00afce11
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column '2nd Item Number'
		dataType: string
		lineageTag: 98b1feef-f6d3-456d-8943-1474e6fbfa19
		summarizeBy: none
		sourceColumn: 2nd Item Number

		annotation SummarizationSetBy = Automatic

	column 'Description 1'
		dataType: string
		lineageTag: 9faef635-ac58-437a-bb6b-1e82996342c5
		summarizeBy: none
		sourceColumn: Description 1

		annotation SummarizationSetBy = Automatic

	column 'Description 1 (2)'
		dataType: string
		lineageTag: 6a2fa519-9762-4d87-ad0f-19bbac603a40
		summarizeBy: none
		sourceColumn: Description 1 (2)

		annotation SummarizationSetBy = Automatic

	column 'Delivery Instructions Line 1'
		dataType: string
		lineageTag: 2d716623-1d05-44b7-b76d-ca33cf28b8ea
		summarizeBy: none
		sourceColumn: Delivery Instructions Line 1

		annotation SummarizationSetBy = Automatic

	column 'Delivery Instructions Line 2'
		dataType: string
		lineageTag: 3294e0b1-939e-46ae-abd3-4da91d8dd018
		summarizeBy: none
		sourceColumn: Delivery Instructions Line 2

		annotation SummarizationSetBy = Automatic

	column 'Next Status'
		dataType: string
		lineageTag: e14458e6-f2df-4b68-bf44-acc69093b26b
		summarizeBy: none
		sourceColumn: Next Status

		annotation SummarizationSetBy = Automatic

	column 'Customer Segmentation'
		dataType: string
		lineageTag: c24a91a5-e9fe-4e0b-be83-bb5202df08f0
		summarizeBy: none
		sourceColumn: Customer Segmentation

		annotation SummarizationSetBy = Automatic

	column 'Make Site'
		dataType: string
		lineageTag: 218fcde1-6a99-43e4-8331-bb1f90478616
		summarizeBy: none
		sourceColumn: Make Site

		annotation SummarizationSetBy = Automatic

	column 'Lead Time Order to Ship'
		dataType: int64
		formatString: 0
		lineageTag: c986e016-d175-4640-a802-218291cb5080
		summarizeBy: none
		sourceColumn: Lead Time Order to Ship

		annotation SummarizationSetBy = Automatic

	column 'Ship Site'
		dataType: string
		lineageTag: 609e1c5b-aa7e-434b-95f9-e4efd5046be3
		summarizeBy: none
		sourceColumn: Ship Site

		annotation SummarizationSetBy = Automatic

	column 'Carrier Name'
		dataType: string
		lineageTag: 57b2ed65-64ed-4ec3-8a6b-6189908ac6b5
		summarizeBy: none
		sourceColumn: Carrier Name

		annotation SummarizationSetBy = Automatic

	column 'Freight Handling Code'
		dataType: string
		lineageTag: 9a014bcc-da10-4112-80ab-aa5c8b6e5f40
		summarizeBy: none
		sourceColumn: Freight Handling Code

		annotation SummarizationSetBy = Automatic

	column 'CSR Name' =
			VAR reps = FILTER('CSR Assignments', 'CSR Assignments'[Ship To] = 'Sales_Orders_Static'[Ship To Key])
			VAR pick = MINX(reps, 'CSR Assignments'[Rep AN8])
			RETURN MAXX(FILTER(reps, 'CSR Assignments'[Rep AN8] = pick), 'CSR Assignments'[CSR Name])
		dataType: string
		lineageTag: 496638cb-d6ca-4f5f-baaa-963c7d2f0f16
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Ordered Qty (units)'
		dataType: double
		formatString: #,##0
		lineageTag: 805a25de-b93d-4d46-bd97-ed7e97a4827b
		summarizeBy: none
		sourceColumn: Ordered Qty (units)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Trans UOM'
		dataType: string
		lineageTag: 6fe45940-ebe6-4e89-bf5c-2dc542f36cd8
		summarizeBy: none
		sourceColumn: Trans UOM

		annotation SummarizationSetBy = Automatic

	column 'Primary UOM'
		dataType: string
		lineageTag: 71c7be85-2c49-4a59-a79e-77de75a1832e
		summarizeBy: none
		sourceColumn: Primary UOM

		annotation SummarizationSetBy = Automatic

	column 'Sales Factor' = IF('Sales_Orders_Static'[Trans UOM] = 'Sales_Orders_Static'[Primary UOM], 1, COALESCE(RELATED('UOM Conversions'[Factor]), 1))
		dataType: double
		lineageTag: 23ccf52b-8048-4618-8cfe-85ee1254bd73
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Ordered Quantity' = 'Sales_Orders_Static'[Ordered Qty (units)] * 'Sales_Orders_Static'[Sales Factor]
		dataType: double
		formatString: #,##0
		lineageTag: 67bfbf54-09ee-41e5-9974-f2f811dad0e6
		summarizeBy: sum

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'LB Factor' = IF('Sales_Orders_Static'[Primary UOM] = "LB", 1, COALESCE(RELATED('UOM To LB'[Factor]), 1))
		dataType: double
		lineageTag: f6a4fbe7-924c-4f6a-bad0-535dbd900827
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Ordered Quantity LBs' = 'Sales_Orders_Static'[Ordered Quantity] * 'Sales_Orders_Static'[LB Factor]
		dataType: double
		formatString: #,##0
		lineageTag: ba29ddfc-1df9-435c-ba6e-f9503b9a9eda
		summarizeBy: sum

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'TM Name' =
			VAR reps = FILTER('TM Assignments', 'TM Assignments'[Ship To] = 'Sales_Orders_Static'[Ship To Key])
			VAR pick = MINX(reps, 'TM Assignments'[Rep AN8])
			RETURN MAXX(FILTER(reps, 'TM Assignments'[Rep AN8] = pick), 'TM Assignments'[TM Name])
		dataType: string
		lineageTag: 9b320677-468a-4c3f-abe0-fe816299ef62
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Item Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e26e98df-1726-423e-90d3-8202b34df06f
		summarizeBy: none
		sourceColumn: Item Key

		annotation SummarizationSetBy = Automatic

	column 'Ship To Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 83e63ed5-c172-4537-ad49-035676b60e6a
		summarizeBy: none
		sourceColumn: Ship To Key

		annotation SummarizationSetBy = Automatic

	column 'Conv Key'
		dataType: string
		isHidden
		lineageTag: ae87dcfe-47f9-4b57-9936-3c1c40ba8ffa
		summarizeBy: none
		sourceColumn: Conv Key

		annotation SummarizationSetBy = Automatic

	column 'LB Key'
		dataType: string
		isHidden
		lineageTag: 4a78c406-aba5-4b6a-a2bd-eb59bf0e64ba
		summarizeBy: none
		sourceColumn: LB Key

		annotation SummarizationSetBy = Automatic

	partition Sales_Orders_Static = m
		mode: import
		source =
				let
				    Source = Sql.Database("ODSPROD", "ODS"),
				    Data = Value.NativeQuery(
				        Source,
				        "
				        SELECT
				            o.SDDOCO                          AS [Order Number],
				            o.SDLNID / 1000.0                 AS [Line Number],
				            o.Ordered_Date                    AS [Ordered Date],
				            o.Promised_Ship_Date              AS [Promised Ship Date],
				            LTRIM(RTRIM(shipto.ABALPH))       AS [Customer Name],
				            LTRIM(RTRIM(o.SDLITM))            AS [2nd Item Number],
				            LTRIM(RTRIM(o.SDDSC1))            AS [Description 1],
				            LTRIM(RTRIM(o.SDDSC1))            AS [Description 1 (2)],
				            LTRIM(RTRIM(h.SHDEL1))            AS [Delivery Instructions Line 1],
				            LTRIM(RTRIM(h.SHDEL2))            AS [Delivery Instructions Line 2],
				            o.SDNXTR                          AS [Next Status],
				            o.SDUORG / 10000.0                AS [Ordered Qty (units)],
				            LTRIM(RTRIM(o.SDUOM))             AS [Trans UOM],
				            LTRIM(RTRIM(im.IMUOM1))           AS [Primary UOM],
				            LTRIM(RTRIM(shipto.ABAC06))       AS [Customer Segmentation],
				            CASE
				                WHEN LTRIM(RTRIM(o.SDMCU))='CIN2' AND LTRIM(RTRIM(COALESCE(it.IBSTKT, im.IMSTKT))) IN ('S','M','Q','P') THEN 'Kemper'
				                WHEN LTRIM(RTRIM(o.SDMCU))='CIN2' AND LTRIM(RTRIM(COALESCE(it.IBSTKT, im.IMSTKT))) IN ('D')             THEN 'Shell'
				                WHEN LTRIM(RTRIM(o.SDMCU))='CINC' AND LTRIM(RTRIM(COALESCE(it.IBSTKT, im.IMSTKT))) IN ('S','M','Q','P') THEN 'Shell'
				                ELSE 'OTHER'
				            END                               AS [Make Site],
				            it.IBLTLV                         AS [Lead Time Order to Ship],
				            CASE
				                WHEN LTRIM(RTRIM(o.SDMCU))='CIN2' THEN 'Kemper'
				                WHEN LTRIM(RTRIM(o.SDMCU))='CINC' THEN 'Shell'
				                ELSE 'OTHER'
				            END                               AS [Ship Site],
				            LTRIM(RTRIM(car.ABALPH))          AS [Carrier Name],
				            LTRIM(RTRIM(o.SDFRTH))            AS [Freight Handling Code],
				            o.SDITM                           AS [Item Key],
				            o.SDSHAN                          AS [Ship To Key],
				            CAST(o.SDITM AS varchar(20)) + '|' + LTRIM(RTRIM(o.SDUOM)) + '|' + LTRIM(RTRIM(im.IMUOM1)) AS [Conv Key],
				            CAST(o.SDITM AS varchar(20)) + '|' + LTRIM(RTRIM(im.IMUOM1)) AS [LB Key]
				        FROM (
				            SELECT
				                SDKCOO, SDDOCO, SDDCTO, SDSFXO, SDLNID, SDMCU, SDLITM, SDITM, SDNXTR,
				                SDDSC1, SDUORG, SDUOM, SDSHAN, SDFRTH, SDCARS,
				                CASE WHEN SDTRDJ>0 THEN DATEADD(DAY,(SDTRDJ%1000)-1,DATEFROMPARTS(1900+(SDTRDJ/1000),1,1)) END AS Ordered_Date,
				                CASE WHEN SDPDDJ>0 THEN DATEADD(DAY,(SDPDDJ%1000)-1,DATEFROMPARTS(1900+(SDPDDJ/1000),1,1)) END AS Promised_Ship_Date
				            FROM (
				                SELECT SDKCOO, SDDOCO, SDDCTO, SDSFXO, SDLNID, SDMCU, SDLITM, SDITM, SDNXTR,
				                       SDDSC1, SDUORG, SDUOM, SDSHAN, SDFRTH, SDCARS, SDTRDJ, SDPDDJ
				                FROM PRODDTA.F4211
				                UNION ALL
				                SELECT h.SDKCOO, h.SDDOCO, h.SDDCTO, h.SDSFXO, h.SDLNID, h.SDMCU, h.SDLITM, h.SDITM, h.SDNXTR,
				                       h.SDDSC1, h.SDUORG, h.SDUOM, h.SDSHAN, h.SDFRTH, h.SDCARS, h.SDTRDJ, h.SDPDDJ
				                FROM PRODDTA.F42119 h
				                WHERE NOT EXISTS (SELECT 1 FROM PRODDTA.F4211 c
				                                  WHERE c.SDKCOO = h.SDKCOO AND c.SDDOCO = h.SDDOCO
				                                    AND c.SDDCTO = h.SDDCTO AND c.SDLNID = h.SDLNID
				                                    AND c.SDSFXO = h.SDSFXO)
				            ) u
				        ) o
				        LEFT JOIN PRODDTA.F4201 h ON h.SHKCOO = o.SDKCOO AND h.SHDOCO = o.SDDOCO
				                                 AND h.SHDCTO = o.SDDCTO AND h.SHSFXO = o.SDSFXO
				        INNER JOIN PRODDTA.F0101 shipto ON o.SDSHAN = shipto.ABAN8
				        LEFT JOIN PRODDTA.F4102 it ON LTRIM(RTRIM(o.SDMCU))  = LTRIM(RTRIM(it.IBMCU))
				                                  AND LTRIM(RTRIM(o.SDLITM)) = LTRIM(RTRIM(it.IBLITM))
				        LEFT JOIN PRODDTA.F4101 im  ON im.IMITM = o.SDITM
				        LEFT JOIN PRODDTA.F554101 tag ON tag.IMITM = o.SDITM
				        LEFT JOIN PRODDTA.F0101 car ON o.SDCARS = car.ABAN8
				        WHERE o.Promised_Ship_Date BETWEEN DATEADD(DAY,-365, CAST(GETDATE() AS date))
				                                       AND DATEADD(DAY, 30, CAST(GETDATE() AS date))
				          AND LTRIM(RTRIM(o.SDMCU)) IN ('CINC','CIN2','CIN4')
				          AND CASE WHEN ISNULL(LTRIM(RTRIM(tag.IMGBLK)),'-')='-'
				                   THEN LTRIM(RTRIM(o.SDLITM)) ELSE LTRIM(RTRIM(tag.IMGBLK)) END
				              NOT IN ('IGST','CGST','SGST','CVD','ADD')
				        ",
				        null,
				        [EnableFolding = true]
				    ),
				    Typed = Table.TransformColumnTypes(
				        Data,
				        {
				            {"Order Number", Int64.Type},
				            {"Line Number", type number},
				            {"Ordered Date", type date},
				            {"Promised Ship Date", type date},
				            {"Customer Name", type text},
				            {"2nd Item Number", type text},
				            {"Description 1", type text},
				            {"Description 1 (2)", type text},
				            {"Delivery Instructions Line 1", type text},
				            {"Delivery Instructions Line 2", type text},
				            {"Next Status", type text},
				            {"Ordered Qty (units)", type number},
				            {"Trans UOM", type text},
				            {"Primary UOM", type text},
				            {"Customer Segmentation", type text},
				            {"Make Site", type text},
				            {"Lead Time Order to Ship", Int64.Type},
				            {"Ship Site", type text},
				            {"Carrier Name", type text},
				            {"Freight Handling Code", type text},
				            {"Item Key", Int64.Type},
				            {"Ship To Key", Int64.Type},
				            {"Conv Key", type text},
				            {"LB Key", type text}
				        },
				        "en-US"
				    )
				in
				    Typed

	annotation PBI_ResultType = Table

