table 'UOM To LB'
	lineageTag: 7cbb5c4d-e96f-4438-aafd-89cf77ad42d2

	column 'LB Key'
		dataType: string
		lineageTag: a199ca6f-696f-4c42-8b97-268438655d38
		summarizeBy: none
		sourceColumn: LB Key

		annotation SummarizationSetBy = Automatic

	column 'Item Key'
		dataType: int64
		formatString: 0
		lineageTag: 0406546a-7d67-4a1b-940a-901432a72bcf
		summarizeBy: none
		sourceColumn: Item Key

		annotation SummarizationSetBy = Automatic

	column 'From UOM'
		dataType: string
		lineageTag: 6ff731e4-2207-4e4e-93ac-599a44642b5d
		summarizeBy: none
		sourceColumn: From UOM

		annotation SummarizationSetBy = Automatic

	column Factor
		dataType: double
		lineageTag: 27ad4f6e-dbc7-4691-8528-43b7ee15aa62
		summarizeBy: none
		sourceColumn: Factor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	partition 'UOM To LB' = m
		mode: import
		source =
				let
				    Source = Sql.Database("ODSPROD", "ODS"),
				    Data = Value.NativeQuery(
				        Source,
				        "
				        SELECT
				            CAST(UMITM AS varchar(20)) + '|' + LTRIM(RTRIM(UMUM)) AS [LB Key],
				            UMITM                       AS [Item Key],
				            LTRIM(RTRIM(UMUM))          AS [From UOM],
				            MAX(UMCONV) / 10000000.0    AS [Factor]
				        FROM PRODDTA.F41002
				        WHERE LTRIM(RTRIM(UMRUM)) = 'LB'
				        GROUP BY UMITM, LTRIM(RTRIM(UMUM))
				        ",
				        null,
				        [EnableFolding = true]
				    ),
				    Typed = Table.TransformColumnTypes(
				        Data,
				        {
				            {"LB Key", type text},
				            {"Item Key", Int64.Type},
				            {"From UOM", type text},
				            {"Factor", type number}
				        },
				        "en-US"
				    )
				in
				    Typed

	annotation PBI_ResultType = Table

