table Shortage_Detail
	lineageTag: 99999999-9999-4999-8999-999999999999

	column RM
		dataType: string
		lineageTag: 11111111-1111-4111-8111-111111111111
		summarizeBy: none
		sourceColumn: RM

		annotation SummarizationSetBy = Automatic

	column 'Short Qty'
		dataType: double
		formatString: #,0
		lineageTag: 22222222-2222-4222-8222-222222222222
		summarizeBy: none
		sourceColumn: Short Qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column Item
		dataType: string
		lineageTag: 33333333-3333-4333-8333-333333333333
		summarizeBy: none
		sourceColumn: Item

		annotation SummarizationSetBy = Automatic

	column 'Branch Plant'
		dataType: string
		lineageTag: 44444444-4444-4444-8444-444444444444
		summarizeBy: none
		sourceColumn: Branch Plant

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 55555555-5555-4555-8555-555555555555
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Lot Number'
		dataType: string
		lineageTag: 66666666-6666-4666-8666-666666666666
		summarizeBy: none
		sourceColumn: Lot Number

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: 77777777-7777-4777-8777-777777777777
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column 'Qty On Hand'
		dataType: double
		formatString: #,0
		lineageTag: 88888888-8888-4888-8888-888888888888
		summarizeBy: sum
		sourceColumn: Qty On Hand

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	partition Shortage_Detail = m
		mode: import
		source =
				let
				    Source = Sql.Database("ODSPROD", "ODS"),
				    Data = Value.NativeQuery(
				        Source,
				        "
				        SELECT
				            short.RM                    AS [RM],
				            short.ShortQty              AS [Short Qty],
				            ioh.Item2nd                 AS [Item],
				            ioh.BranchPlant             AS [Branch Plant],
				            ioh.Status                  AS [Status],
				            ioh.LotNumber               AS [Lot Number],
				            ioh.Location                AS [Location],
				            ioh.QtyOnHand               AS [Qty On Hand]
				        FROM (
				            SELECT
				                LTRIM(RTRIM(ib.IBMCU))   AS BranchPlant,
				                LTRIM(RTRIM(ib.IBLITM))  AS Item2nd,
				                LTRIM(RTRIM(il.LILOCN))  AS Location,
				                LTRIM(RTRIM(il.LILOTN))  AS LotNumber,
				                il.LILOTS                AS Status,
				                SUM(il.LIPQOH / 10000.0) AS QtyOnHand
				            FROM PRODDTA.F4102 ib
				            JOIN PRODDTA.F41021 il ON ib.IBITM = il.LIITM AND ib.IBMCU = il.LIMCU
				            WHERE (il.LIPQOH / 10000.0) > 0
				              AND LTRIM(RTRIM(ib.IBMCU)) IN ('CIN2','CINC')
				              AND LTRIM(RTRIM(ib.IBLITM)) NOT LIKE '%H2O%'
				            GROUP BY LTRIM(RTRIM(ib.IBMCU)), LTRIM(RTRIM(ib.IBLITM)),
				                     LTRIM(RTRIM(il.LILOCN)), LTRIM(RTRIM(il.LILOTN)), il.LILOTS
				        ) ioh
				        JOIN (
				            SELECT
				                p.Component2nd AS RM,
				                CASE WHEN AVG(iohc.QtyOnHand) IS NULL OR AVG(iohc.QtyOnHand) = 0
				                     THEN SUM(p.OpenRM)
				                     ELSE SUM(p.OpenRM) - AVG(iohc.QtyOnHand)
				                END AS ShortQty
				            FROM (
				                SELECT LTRIM(RTRIM(wp2.WMCPIL)) AS Component2nd,
				                       SUM((wp2.WMUORG - wp2.WMTRQT) / 10000.0) AS OpenRM
				                FROM PRODDTA.F4801 wo2
				                JOIN PRODDTA.F3111 wp2 ON wo2.WADOCO = wp2.WMDOCO
				                JOIN PRODDTA.F4102 ib2 ON wp2.WMMCU = ib2.IBMCU AND wp2.WMCPIT = ib2.IBITM
				                CROSS JOIN (SELECT CAST(GETDATE() AS date) AS Today) t2
				                CROSS APPLY (SELECT (((DATEDIFF(DAY, '2003-01-06', t2.Today) % 7) + 7) % 7) + 1 AS DowMon1) dw2
				                CROSS APPLY (SELECT CASE WHEN dw2.DowMon1 IN (4,5) THEN 4 WHEN dw2.DowMon1 = 6 THEN 3 ELSE 2 END AS DaysFwd) fw2
				                WHERE LTRIM(RTRIM(wo2.WAMMCU)) = 'CINC'
				                  AND wo2.WASRST NOT IN ('93','94','95','97','99','MM','CD')
				                  AND ((wp2.WMUORG - wp2.WMTRQT) / 10000.0) > 0
				                  AND LTRIM(RTRIM(wo2.WALITM)) NOT LIKE '%-%'
				                  AND LTRIM(RTRIM(wp2.WMCPIL)) NOT LIKE '%H2O%'
				                  AND ib2.IBPRP4 IN ('RRC','REC','RCB','TOL','PKG','RBW')
				                  AND (CASE WHEN wp2.WMDRQJ > 0
				                            THEN DATEADD(DAY, (wp2.WMDRQJ % 1000) - 1, DATEFROMPARTS(1900 + (wp2.WMDRQJ / 1000), 1, 1))
				                       END)
				                      BETWEEN DATEADD(DAY, -7, t2.Today) AND DATEADD(DAY, fw2.DaysFwd, t2.Today)
				                GROUP BY LTRIM(RTRIM(wp2.WMCPIL))
				            ) p
				            LEFT JOIN (
				                SELECT LTRIM(RTRIM(ib3.IBLITM)) AS Component2nd, SUM(il3.LIPQOH / 10000.0) AS QtyOnHand
				                FROM PRODDTA.F4102 ib3
				                JOIN PRODDTA.F41021 il3 ON ib3.IBITM = il3.LIITM AND ib3.IBMCU = il3.LIMCU
				                WHERE (il3.LIPQOH / 10000.0) > 0
				                  AND LTRIM(RTRIM(ib3.IBMCU)) = 'CINC'
				                  AND LTRIM(RTRIM(ib3.IBLITM)) NOT LIKE '%H2O%'
				                  AND il3.LILOTS IN (' ','-')
				                GROUP BY LTRIM(RTRIM(ib3.IBLITM)), il3.LILOTS
				            ) iohc ON p.Component2nd = iohc.Component2nd
				            WHERE p.Component2nd <> ' '
				            GROUP BY p.Component2nd
				            HAVING CASE WHEN AVG(iohc.QtyOnHand) IS NULL         THEN 'SHORT'
				                        WHEN AVG(iohc.QtyOnHand) = 0             THEN 'SHORT'
				                        WHEN AVG(iohc.QtyOnHand) < SUM(p.OpenRM) THEN 'SHORT'
				                        ELSE 'OK' END = 'SHORT'
				        ) short ON ioh.Item2nd = short.RM
				        ",
				        null,
				        [EnableFolding = true]
				    ),
				    Typed = Table.TransformColumnTypes(
				        Data,
				        {
				            {"RM", type text},
				            {"Short Qty", type number},
				            {"Item", type text},
				            {"Branch Plant", type text},
				            {"Status", type text},
				            {"Lot Number", type text},
				            {"Location", type text},
				            {"Qty On Hand", type number}
				        }
				    )
				in
				    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

