table Inv_Summary_OH_Expiry
	lineageTag: 8c90a5fe-350b-402e-9999-4e1d09d0f4e2

	column 'Branch Plant'
		dataType: string
		lineageTag: a26470f6-4a68-41c5-a4dd-f420fc1b6eba
		summarizeBy: none
		sourceColumn: Branch Plant

		annotation SummarizationSetBy = Automatic

	column 'Global Bulk Item'
		dataType: string
		lineageTag: 51c21d4e-d3d2-482e-be29-9bfff2a5e902
		summarizeBy: none
		sourceColumn: Global Bulk Item

		annotation SummarizationSetBy = Automatic

	column 'Bulk Item'
		dataType: string
		lineageTag: e5d92292-c2f7-4e91-a12f-b291a42990b2
		summarizeBy: none
		sourceColumn: Bulk Item

		annotation SummarizationSetBy = Automatic

	column '2nd Item Number'
		dataType: string
		lineageTag: 45c83336-4710-4d84-8487-be4672b0a11b
		summarizeBy: none
		sourceColumn: 2nd Item Number

		annotation SummarizationSetBy = Automatic

	column 'Lot Number'
		dataType: string
		lineageTag: 03bbc36f-3ecf-4bb5-acee-9e81df8bf8a1
		summarizeBy: none
		sourceColumn: Lot Number

		annotation SummarizationSetBy = Automatic

	column 'Lot Number1'
		dataType: string
		lineageTag: 0f346b7a-793c-465c-b4b7-f3ec03596145
		summarizeBy: none
		sourceColumn: Lot Number1

		annotation SummarizationSetBy = Automatic

	column 'Supplier Lot Number'
		dataType: string
		lineageTag: 49c52e12-53ab-42d3-bc01-398f8102326c
		summarizeBy: none
		sourceColumn: Supplier Lot Number

		annotation SummarizationSetBy = Automatic

	column 'On Hand Date'
		dataType: dateTime
		formatString: d MMM, yyyy
		lineageTag: a237550c-f3fa-439a-9388-b40d6bc31c6c
		summarizeBy: none
		sourceColumn: On Hand Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Expiration Date Month'
		dataType: dateTime
		formatString: d MMM, yyyy
		lineageTag: 99cbb801-fbb8-416e-b0bb-5c8beadbdd35
		summarizeBy: none
		sourceColumn: Expiration Date Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TIME
		dataType: dateTime
		formatString: General Date
		lineageTag: f70b580a-e6e9-4b5b-a7c3-7147c5ddc6c5
		summarizeBy: none
		sourceColumn: TIME

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Inv_Summary_OH_Expiry = m
		mode: import
		source =
				let
				    Source = Sql.Database("ODSPROD", "ODS"),
				    Data = Value.NativeQuery(
				        Source,
				        "
				        SELECT DISTINCT
				            Inventory6.Branch_Plant          AS [Branch Plant],
				            Inventory6.Global_Bulk_Item      AS [Global Bulk Item],
				            Inventory6.Bulk_Item             AS [Bulk Item],
				            Inventory6.C_2nd_Item_Number     AS [2nd Item Number],
				            Inventory6.Lot_Number            AS [Lot Number],
				            Quality7.Lot_Number              AS [Lot Number1],
				            Quality7.Supplier_Lot_Number     AS [Supplier Lot Number],
				            Quality7.On_Hand_Date            AS [On Hand Date],
				            Quality7.Expiration_Date_Month   AS [Expiration Date Month],
				            Inventory6.TIME24                AS [TIME]
				        FROM
				        (
				            SELECT
				                T0.C0  AS Branch_Plant,
				                T0.C1  AS Global_Bulk_Item,
				                T0.C2  AS Bulk_Item,
				                T0.C3  AS C_2nd_Item_Number,
				                T0.C14 AS Lot_Number,
				                T0.C23 AS TIME24
				            FROM
				            (
				                SELECT
				                    LTRIM(RTRIM(LTRIM(RTRIM(ib.IBMCU))))    AS C0,
				                    LTRIM(RTRIM(tag.IMGBLK))                AS C1,
				                    LTRIM(RTRIM(tag.IMBULK))                AS C2,
				                    LTRIM(RTRIM(LTRIM(RTRIM(ib.IBLITM))))   AS C3,
				                    LTRIM(RTRIM(loc.LILOTN))                AS C14,
				                    CAST(GETDATE() AS date)                 AS C23
				                FROM PRODDTA.F4102 ib,
				                     PRODDTA.F554101 tag,
				                     PRODDTA.F41021 loc,
				                     PRODDTA.F4101 im,
				                     (
				                        SELECT
				                            f.IBITM, f.IBMCU, e.IELEDG,
				                            SUM(CASE WHEN e.IECOST='A1 ' THEN e.IECSL/10000.0 ELSE 0 END) AS A1_Unit_Cost,
				                            SUM(CASE WHEN e.IECOST='B1 ' THEN e.IECSL/10000.0 ELSE 0 END) AS B1_Unit_Cost,
				                            SUM(CASE WHEN e.IECOST='C1 ' THEN e.IECSL/10000.0 ELSE 0 END) AS C1_Unit_Cost,
				                            SUM(CASE WHEN e.IECOST='C2 ' THEN e.IECSL/10000.0 ELSE 0 END) AS C2_Unit_Cost
				                        FROM PRODDTA.F4102 f,
				                             PRODDTA.F4105 c
				                             LEFT OUTER JOIN PRODDTA.F30026 e
				                                 ON c.COITM=e.IEITM AND c.COMCU=e.IEMMCU AND c.COLEDG=e.IELEDG
				                        WHERE f.IBITM=c.COITM AND f.IBMCU=c.COMCU AND c.COCSIN='I'
				                        GROUP BY f.IBITM, f.IBMCU, e.IELEDG
				                     ) cost
				                WHERE loc.LIPQOH/10000.0 > 0
				                  AND ib.IBITM = im.IMITM
				                  AND im.IMITM = tag.IMITM
				                  AND ib.IBITM = loc.LIITM
				                  AND ib.IBMCU = loc.LIMCU
				                  AND ib.IBITM = cost.IBITM
				                  AND ib.IBMCU = cost.IBMCU
				                GROUP BY
				                    LTRIM(RTRIM(LTRIM(RTRIM(ib.IBMCU)))),
				                    LTRIM(RTRIM(tag.IMGBLK)),
				                    LTRIM(RTRIM(tag.IMBULK)),
				                    LTRIM(RTRIM(LTRIM(RTRIM(ib.IBLITM)))),
				                    ib.IBPRP1, ib.IBPRP2, ib.IBPRP4, ib.IBSAFE/10000.0, ib.IBSLD, ib.IBSTKT,
				                    ib.IBGLPT, ib.IBLTLV, ib.IBLTMF,
				                    LTRIM(RTRIM(loc.LILOCN)), LTRIM(RTRIM(loc.LILOTN)), loc.LILOTS, im.IMUOM1
				            ) T0
				        ) Inventory6
				        INNER JOIN
				        (
				            SELECT DISTINCT
				                LTRIM(RTRIM(lm.IOLOTN)) AS Lot_Number,
				                NULLIF(LTRIM(RTRIM(lm.IORLOT)), 'NULL') AS Supplier_Lot_Number,
				                lm.Expiration_Date_Month AS Expiration_Date_Month,
				                lm.On_Hand_Date          AS On_Hand_Date
				            FROM
				            (
				                SELECT
				                    IOLOTN, IORLOT,
				                    CASE WHEN IOMMEJ>0 THEN DATEADD(DAY,(IOMMEJ%1000)-1,DATEFROMPARTS(1900+(IOMMEJ/1000),1,1)) ELSE NULL END AS Expiration_Date_Month,
				                    CASE WHEN IOOHDJ>0 THEN DATEADD(DAY,(IOOHDJ%1000)-1,DATEFROMPARTS(1900+(IOOHDJ/1000),1,1)) ELSE NULL END AS On_Hand_Date
				                FROM PRODDTA.F4108
				            ) lm
				            WHERE lm.Expiration_Date_Month IS NOT NULL
				        ) Quality7
				            ON Inventory6.Lot_Number = Quality7.Lot_Number
				        ",
				        null,
				        [EnableFolding = true]
				    ),
				    Typed = Table.TransformColumnTypes(
				        Data,
				        {
				            {"Branch Plant", type text}, {"Global Bulk Item", type text}, {"Bulk Item", type text},
				            {"2nd Item Number", type text}, {"Lot Number", type text}, {"Lot Number1", type text},
				            {"Supplier Lot Number", type text}, {"On Hand Date", type date},
				            {"Expiration Date Month", type date}, {"TIME", type date}
				        },
				        "en-US"
				    )
				in
				    Typed

	annotation PBI_ResultType = Table

