table PO_Summary
	lineageTag: 5d4b2828-26c6-43b3-89c1-77305efcaae1

	column Company
		dataType: string
		lineageTag: 578f114c-2e00-41a5-a009-98a7d9592366
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	column 'Branch Plant'
		dataType: string
		lineageTag: 322cd76c-f509-4773-abfa-a5741187cba8
		summarizeBy: none
		sourceColumn: Branch Plant

		annotation SummarizationSetBy = Automatic

	column '2nd Item Number'
		dataType: string
		lineageTag: a7bd3596-a355-46fb-836b-5e9bb2b43bc0
		summarizeBy: none
		sourceColumn: 2nd Item Number

		annotation SummarizationSetBy = Automatic

	column 'Purchase Order Number'
		dataType: int64
		formatString: 0
		lineageTag: 9e83bed5-0225-428e-8b3a-ce6d325fc58b
		summarizeBy: none
		sourceColumn: Purchase Order Number

		annotation SummarizationSetBy = User

	column 'Reference 2'
		dataType: string
		lineageTag: 1fa08614-aafb-4245-98fc-a5ffcf6f4af5
		summarizeBy: none
		sourceColumn: Reference 2

		annotation SummarizationSetBy = Automatic

	column 'Reporting Code 3'
		dataType: string
		lineageTag: dfcb4460-4ed5-410d-aa02-6d2c4c8f7c02
		summarizeBy: none
		sourceColumn: Reporting Code 3

		annotation SummarizationSetBy = Automatic

	column 'Open Quantity'
		dataType: double
		formatString: #,0
		lineageTag: e5663a29-bc91-4389-a9ab-a950e186c301
		summarizeBy: sum
		sourceColumn: Open Quantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Primary Quantity'
		dataType: double
		formatString: #,0
		lineageTag: d63f22a3-0556-4508-a9b0-d068bc7dd00a
		summarizeBy: sum
		sourceColumn: Primary Quantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Primary UOM'
		dataType: string
		lineageTag: 29d469f6-1d64-452e-a61e-2c63be32663d
		summarizeBy: none
		sourceColumn: Primary UOM

		annotation SummarizationSetBy = Automatic

	column 'Secondary Quantity'
		dataType: double
		formatString: #,0
		lineageTag: 7a7f15fa-70e7-4d02-af23-e1e043287417
		summarizeBy: sum
		sourceColumn: Secondary Quantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Secondary UOM'
		dataType: string
		lineageTag: 51b9648f-82ad-48a0-bb20-8ddc1b012308
		summarizeBy: none
		sourceColumn: Secondary UOM

		annotation SummarizationSetBy = Automatic

	column 'Last Status'
		dataType: string
		lineageTag: cfbbdc28-df1b-473a-8e0a-b995f9ad7e44
		summarizeBy: none
		sourceColumn: Last Status

		annotation SummarizationSetBy = Automatic

	column 'Next Status'
		dataType: string
		lineageTag: aa971ccb-5edf-4f54-bf3e-a5f5bcd2ab8a
		summarizeBy: none
		sourceColumn: Next Status

		annotation SummarizationSetBy = Automatic

	column 'Requested Date'
		dataType: dateTime
		formatString: d MMM, yyyy
		lineageTag: 87c6827b-f9fb-4e48-bc97-7a3bbcdfa319
		summarizeBy: none
		sourceColumn: Requested Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Promised Date'
		dataType: dateTime
		formatString: d MMM, yyyy
		lineageTag: 54af7f50-9d9f-47b7-8f0b-b2be03a00869
		summarizeBy: none
		sourceColumn: Promised Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Vendor Code'
		dataType: int64
		formatString: 0
		lineageTag: 675de90a-c03a-481c-beeb-e9ff900b5d88
		summarizeBy: none
		sourceColumn: Vendor Code

		annotation SummarizationSetBy = User

	column 'Vendor Name'
		dataType: string
		lineageTag: f36cef8a-2c66-45e6-8646-92fa70caa705
		summarizeBy: none
		sourceColumn: Vendor Name

		annotation SummarizationSetBy = Automatic

	column 'Freeze Code Flag'
		dataType: string
		lineageTag: 3fcca79f-7b9d-4b5c-9ebe-a093ad94d3f8
		summarizeBy: none
		sourceColumn: Freeze Code Flag

		annotation SummarizationSetBy = Automatic

	column 'Branch Plant1'
		dataType: string
		lineageTag: d82da613-7a1f-4664-8db6-95092a98ae6a
		summarizeBy: none
		sourceColumn: Branch Plant1

		annotation SummarizationSetBy = Automatic

	column 'Global Bulk Item'
		dataType: string
		lineageTag: 9541c383-e28b-479e-89c2-f42369fd0f11
		summarizeBy: none
		sourceColumn: Global Bulk Item

		annotation SummarizationSetBy = Automatic

	column 'Bulk Item'
		dataType: string
		lineageTag: 0761f522-22a1-4448-aec6-73bc732ece3f
		summarizeBy: none
		sourceColumn: Bulk Item

		annotation SummarizationSetBy = Automatic

	column '2nd Item Number1'
		dataType: string
		lineageTag: 9a625b04-c5c3-41a4-90b4-148080ef8d1f
		summarizeBy: none
		sourceColumn: 2nd Item Number1

		annotation SummarizationSetBy = Automatic

	column 'Commodity Class'
		dataType: string
		lineageTag: 8cfb948c-ef74-4a17-93d3-d06fb031882b
		summarizeBy: none
		sourceColumn: Commodity Class

		annotation SummarizationSetBy = Automatic

	column 'Sub Class'
		dataType: string
		lineageTag: a66a4b05-a696-4254-8a28-9a29c978cccb
		summarizeBy: none
		sourceColumn: Sub Class

		annotation SummarizationSetBy = Automatic

	column 'Master Planning Family'
		dataType: string
		lineageTag: 6313d828-3335-4a6a-8b3d-eb24915df63a
		summarizeBy: none
		sourceColumn: Master Planning Family

		annotation SummarizationSetBy = Automatic

	column 'GL Category'
		dataType: string
		lineageTag: 5f64f0cf-ac80-4043-b299-34113f7b0b66
		summarizeBy: none
		sourceColumn: GL Category

		annotation SummarizationSetBy = Automatic

	column 'Primary Supplier'
		dataType: int64
		formatString: 0
		lineageTag: 2623020f-b103-4c83-a322-f533a790a22f
		summarizeBy: none
		sourceColumn: Primary Supplier

		annotation SummarizationSetBy = User

	column 'Safety Stock'
		dataType: double
		lineageTag: a28ea953-7ae0-4c33-976d-2bf4de2e9b1e
		summarizeBy: none
		sourceColumn: Safety Stock

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Leadtime Level'
		dataType: double
		lineageTag: cfe0d4c6-f7e0-443c-b08d-79e6433886dc
		summarizeBy: none
		sourceColumn: Leadtime Level

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isDecimal":true}

	partition PO_Summary = m
		mode: import
		source =
				let
				    Source = Sql.Database("ODSPROD", "ODS"),
				    Data = Value.NativeQuery(
				        Source,
				        "
				        SELECT
				            PO5.Company                     AS [Company],
				            PO5.Branch_Plant                AS [Branch Plant],
				            PO5.C_2nd_Item_Number           AS [2nd Item Number],
				            PO5.Purchase_Order_Number       AS [Purchase Order Number],
				            PO5.Reference_2                 AS [Reference 2],
				            PO5.Reporting_Code_3            AS [Reporting Code 3],
				            SUM(PO5.Open_Quantity)          AS [Open Quantity],
				            SUM(PO5.Primary_Quantity)       AS [Primary Quantity],
				            Item6.Primary_UOM               AS [Primary UOM],
				            SUM(PO5.Secondary_Quantity)     AS [Secondary Quantity],
				            Item6.Secondary_UOM             AS [Secondary UOM],
				            PO5.Last_Status                 AS [Last Status],
				            PO5.Next_Status                 AS [Next Status],
				            PO5.Requested_Date              AS [Requested Date],
				            PO5.Promised_Date               AS [Promised Date],
				            SUM(PO5.Vendor_Code)            AS [Vendor Code],
				            PO5.Vendor_Name                 AS [Vendor Name],
				            PO5.Freeze_Code_Flag            AS [Freeze Code Flag],
				            Item6.Branch_Plant              AS [Branch Plant1],
				            Item6.Global_Bulk_Item          AS [Global Bulk Item],
				            Item6.Bulk_Item                 AS [Bulk Item],
				            Item6.C_2nd_Item_Number         AS [2nd Item Number1],
				            Item6.Commodity_Class           AS [Commodity Class],
				            Item6.Sub_Class                 AS [Sub Class],
				            Item6.Master_Planning_Family    AS [Master Planning Family],
				            Item6.GL_Category               AS [GL Category],
				            Item6.Primary_Supplier          AS [Primary Supplier],
				            Item6.Safety_Stock              AS [Safety Stock],
				            Item6.Leadtime_Level            AS [Leadtime Level]
				        FROM
				        (
				            SELECT DISTINCT
				                LTRIM(RTRIM(LTRIM(RTRIM(ib.IBMCU))))    AS Branch_Plant,
				                LTRIM(RTRIM(LTRIM(RTRIM(tag.IMGBLK))))  AS Global_Bulk_Item,
				                LTRIM(RTRIM(LTRIM(RTRIM(tag.IMBULK))))  AS Bulk_Item,
				                LTRIM(RTRIM(LTRIM(RTRIM(ib.IBLITM))))   AS C_2nd_Item_Number,
				                ib.IBPRP1                               AS Commodity_Class,
				                ib.IBPRP2                               AS Sub_Class,
				                ib.IBPRP4                               AS Master_Planning_Family,
				                ib.IBGLPT                               AS GL_Category,
				                ib.IBVEND                               AS Primary_Supplier,
				                ib.IBSAFE/10000.0                       AS Safety_Stock,
				                ib.IBLTLV                               AS Leadtime_Level,
				                im.IMUOM1                               AS Primary_UOM,
				                im.IMUOM2                               AS Secondary_UOM
				            FROM PRODDTA.F4102 ib, PRODDTA.F554101 tag, PRODDTA.F4101 im
				            WHERE ib.IBITM = im.IMITM AND im.IMITM = tag.IMITM
				        ) Item6
				        INNER JOIN
				        (
				            SELECT
				                pod.PDKCOO                          AS Company,
				                LTRIM(RTRIM(pod.PDMCU))             AS Branch_Plant,
				                LTRIM(RTRIM(pod.PDLITM))            AS C_2nd_Item_Number,
				                pod.PDDOCO                          AS Purchase_Order_Number,
				                pod.PDDRQJ                          AS Requested_Date,
				                pod.PDVR02                          AS Reference_2,
				                pod.PDPDP3                          AS Reporting_Code_3,
				                SUM(pod.PDUOPN/10000.0)             AS Open_Quantity,
				                SUM(pod.PDPQOR/10000.0)             AS Primary_Quantity,
				                SUM(pod.PDSQOR/10000.0)             AS Secondary_Quantity,
				                pod.PDLTTR                          AS Last_Status,
				                pod.PDNXTR                          AS Next_Status,
				                pod.PDPDDJ                          AS Promised_Date,
				                SUM(pod.PDAN8)                      AS Vendor_Code,
				                LTRIM(RTRIM(ab.ABALPH))             AS Vendor_Name,
				                pod.PDUNCD                          AS Freeze_Code_Flag
				            FROM
				            (
				                SELECT
				                    PDKCOO, PDDOCO, PDDCTO, PDMCU, PDAN8,
				                    CASE WHEN PDDRQJ>0 THEN DATEADD(DAY,(PDDRQJ%1000)-1,DATEFROMPARTS(1900+(PDDRQJ/1000),1,1)) ELSE NULL END AS PDDRQJ,
				                    CASE WHEN PDPDDJ>0 THEN DATEADD(DAY,(PDPDDJ%1000)-1,DATEFROMPARTS(1900+(PDPDDJ/1000),1,1)) ELSE NULL END AS PDPDDJ,
				                    PDVR02, PDLITM, PDNXTR, PDLTTR, PDPDP3, PDUOPN, PDPQOR, PDSQOR,
				                    ISNULL(NULLIF(LTRIM(RTRIM(PDUNCD)),''),'-') AS PDUNCD
				                FROM PRODDTA.F4311
				            ) pod,
				            PRODDTA.F0101 ab
				            WHERE pod.PDPDDJ >= DATEADD(DAY,-365,CAST(GETDATE() AS date))
				              AND pod.PDDCTO = 'OP'
				              AND pod.PDAN8 = ab.ABAN8
				            GROUP BY
				                pod.PDKCOO, LTRIM(RTRIM(pod.PDMCU)), LTRIM(RTRIM(pod.PDLITM)), pod.PDDOCO,
				                pod.PDDCTO, pod.PDDRQJ, pod.PDVR02, pod.PDPDP3, pod.PDLTTR, pod.PDNXTR,
				                pod.PDPDDJ, LTRIM(RTRIM(ab.ABALPH)), pod.PDUNCD
				        ) PO5
				            ON Item6.Branch_Plant = PO5.Branch_Plant
				           AND Item6.C_2nd_Item_Number = PO5.C_2nd_Item_Number
				        GROUP BY
				            PO5.Company, PO5.Branch_Plant, PO5.C_2nd_Item_Number, PO5.Purchase_Order_Number,
				            PO5.Requested_Date, PO5.Reference_2, PO5.Reporting_Code_3, PO5.Last_Status,
				            PO5.Next_Status, PO5.Promised_Date, PO5.Vendor_Name, PO5.Freeze_Code_Flag,
				            Item6.Branch_Plant, Item6.Global_Bulk_Item, Item6.Bulk_Item, Item6.C_2nd_Item_Number,
				            Item6.Commodity_Class, Item6.Sub_Class, Item6.Master_Planning_Family, Item6.GL_Category,
				            Item6.Primary_Supplier, Item6.Safety_Stock, Item6.Leadtime_Level,
				            Item6.Primary_UOM, Item6.Secondary_UOM
				        ",
				        null,
				        [EnableFolding = true]
				    ),
				    Typed = Table.TransformColumnTypes(
				        Data,
				        {
				            {"Company", type text}, {"Branch Plant", type text}, {"2nd Item Number", type text},
				            {"Purchase Order Number", Int64.Type}, {"Reference 2", type text}, {"Reporting Code 3", type text},
				            {"Open Quantity", type number}, {"Primary Quantity", type number}, {"Primary UOM", type text},
				            {"Secondary Quantity", type number}, {"Secondary UOM", type text}, {"Last Status", type text},
				            {"Next Status", type text}, {"Requested Date", type date}, {"Promised Date", type date},
				            {"Vendor Code", Int64.Type}, {"Vendor Name", type text}, {"Freeze Code Flag", type text},
				            {"Branch Plant1", type text}, {"Global Bulk Item", type text}, {"Bulk Item", type text},
				            {"2nd Item Number1", type text}, {"Commodity Class", type text}, {"Sub Class", type text},
				            {"Master Planning Family", type text}, {"GL Category", type text}, {"Primary Supplier", Int64.Type},
				            {"Safety Stock", type number}, {"Leadtime Level", type number}
				        },
				        "en-US"
				    )
				in
				    Typed

	annotation PBI_ResultType = Table

