table CM_Inventory_on_Hand
	lineageTag: 85e3c226-726c-45aa-ab57-03eefe9e45ea

	column REGION
		dataType: string
		lineageTag: eb53627d-a049-4de0-accb-0e58b6d9366c
		summarizeBy: none
		sourceColumn: REGION

		annotation SummarizationSetBy = Automatic

	column 'Branch Plant'
		dataType: string
		lineageTag: d04f82d1-c56f-42da-9d32-5ee0fa045f74
		summarizeBy: none
		sourceColumn: Branch Plant

		annotation SummarizationSetBy = Automatic

	column 'Bulk Item'
		dataType: string
		lineageTag: f3ff4634-fdf8-4574-8049-95c5368639e6
		summarizeBy: none
		sourceColumn: Bulk Item

		annotation SummarizationSetBy = Automatic

	column '2nd Item Number'
		dataType: string
		lineageTag: 69e1b8c3-8bdd-4b5b-93fd-bac5c8441bca
		summarizeBy: none
		sourceColumn: 2nd Item Number

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 806d4e49-2a07-403e-83c6-34800a0af94b
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'KG/EA OH'
		dataType: double
		formatString: #,0
		lineageTag: dd86f089-a760-44bd-b457-b92684ae962b
		summarizeBy: none
		sourceColumn: KG/EA OH

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'LB/EA OH'
		dataType: double
		formatString: #,0
		lineageTag: 9d7cb3a4-77b5-4059-8d24-ae4bc17b269b
		summarizeBy: none
		sourceColumn: LB/EA OH

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Hard Commit'
		dataType: double
		formatString: #,0
		lineageTag: 13ba4378-6c2d-4156-ab1f-754f285dfe6e
		summarizeBy: none
		sourceColumn: Hard Commit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Primary UOM'
		dataType: string
		lineageTag: 1bdd0325-3016-42e8-acf3-2ad8bccab6e9
		summarizeBy: none
		sourceColumn: Primary UOM

		annotation SummarizationSetBy = Automatic

	partition CM_Inventory_on_Hand = m
		mode: import
		source =
				let
				    Source = Sql.Database("ODSPROD", "ODS"),
				    Data = Value.NativeQuery(
				        Source,
				        "
				        SELECT
				            CASE LTRIM(RTRIM(ib.IBMCU))
				                 WHEN 'CINC' THEN 'Americas'
				                 WHEN 'CIN2' THEN 'Americas'
				                 WHEN 'CIN4' THEN 'Americas'
				                 WHEN 'GRAN' THEN 'Americas'
				                 WHEN 'DANC' THEN 'Americas'
				                 WHEN 'AUBA' THEN 'Aubange'
				                 WHEN 'AUB2' THEN 'Aubange'
				                 WHEN 'SHAN' THEN 'Shanghai'
				                 WHEN 'SING' THEN 'Singapore'
				                 WHEN 'SNG4' THEN 'Singapore'
				                 WHEN 'MUM3' THEN 'Mumbai'
				                 ELSE 'OTHER'
				            END                                     AS [REGION],
				            LTRIM(RTRIM(ib.IBMCU))                  AS [Branch Plant],
				            LTRIM(RTRIM(tag.IMBULK))                AS [Bulk Item],
				            LTRIM(RTRIM(ib.IBLITM))                 AS [2nd Item Number],
				            LTRIM(RTRIM(loc.LILOTS))                AS [Status],
				            CASE WHEN MIN(im.IMUOM1) = 'LB' THEN SUM(loc.LIPQOH/10000.0) * 0.453593
				                 WHEN MIN(im.IMUOM1) = 'KG' THEN SUM(loc.LIPQOH/10000.0)
				                 ELSE SUM(loc.LIPQOH/10000.0)
				            END                                     AS [KG/EA OH],
				            CASE WHEN MIN(im.IMUOM1) = 'KG' THEN SUM(loc.LIPQOH/10000.0) / 0.453593
				                 WHEN MIN(im.IMUOM1) = 'LB' THEN SUM(loc.LIPQOH/10000.0)
				                 ELSE SUM(loc.LIPQOH/10000.0)
				            END                                     AS [LB/EA OH],
				            SUM(loc.LIHCOM/10000.0)                 AS [Hard Commit],
				            im.IMUOM1                               AS [Primary UOM]
				        FROM PRODDTA.F4102 ib
				        JOIN PRODDTA.F4101   im  ON ib.IBITM = im.IMITM
				        JOIN PRODDTA.F554101 tag ON im.IMITM = tag.IMITM
				        JOIN PRODDTA.F41021  loc ON ib.IBITM = loc.LIITM
				                                AND ib.IBMCU = loc.LIMCU
				        WHERE loc.LIPQOH/10000.0 > 0
				          AND LTRIM(RTRIM(tag.IMBULK)) IN ('161017CX', '161190PX', '171143PX', '171228PX.E', '181020CX.E', '181136IX', '181192IX', '181193EU.E', '191011CX', '191026CX.E', '191245PX', '23409A', 'ABEX2525', 'APT10', 'APT11', 'DMAEMA', 'EMA3065', 'ET2012.E', 'ET2022.E', 'ET4075.E', 'ET440.E', 'FERSUL7W', 'HP1432AT', 'HP1632', 'MD4020', 'MD4020C', 'MD4020S', 'MD4021', 'MD4021C', 'MD4021S', 'MD4022', 'MD4022C', 'MD4023', 'MD4023C', 'MDU20', 'MDU2012.E', 'MDU2012B.E', 'MDU4075.E', 'MDU4075B.E', 'MDU440.E', 'MDU440B.E', 'MPEG2000', 'MW40504', 'MW40514', 'NP4LF', 'NP4LF.S', 'OMS', 'PUD1.E', 'STODSO', 'U1001', 'U101', 'U201', 'U2022', 'U2022EU.E', 'U2023', 'U204', 'U204EU.E', 'U470', 'U501', 'U501B', 'U502', 'U502.E', 'U502X1.E', 'U601', 'U701', 'U802', 'U802.E', 'WAV501', 'WD40', 'WD40T', 'DPE3500', '191245PX', '201118CX.E', 'ACRYLA', 'ACTMBS', 'AMDBIO', 'AMMPERSU', 'APT10', 'BLACKAN', 'BPADA', 'CALDB45', 'DMAEMA', 'DPE3500', 'EMA3065', 'FERSUL7W', 'HP1432AT', 'HP1632', 'MD4020', 'MD4021', 'MD4022', 'MD4023', 'MDU20', 'MDU2012B.E', 'MDU4075B.E', 'MEHQ.E', 'PEG1450', 'STYRENE', 'TBHP70', 'U101', 'U201', 'U2022', 'U2022EU.E', 'U2023', 'U470', 'U501', 'U501B', 'U502', 'U502.E', 'U505.E', 'U601', 'U701', 'U802', 'U802.E', 'UNYTEC201', 'VER100', 'WAV501', 'WD40', 'JS037', 'HP401', 'HSCF410')
				        GROUP BY
				            LTRIM(RTRIM(ib.IBMCU)),
				            LTRIM(RTRIM(tag.IMBULK)),
				            LTRIM(RTRIM(ib.IBLITM)),
				            LTRIM(RTRIM(loc.LILOTS)),
				            im.IMUOM1,
				            CASE LTRIM(RTRIM(ib.IBMCU))
				                 WHEN 'CINC' THEN 'Americas'
				                 WHEN 'CIN2' THEN 'Americas'
				                 WHEN 'CIN4' THEN 'Americas'
				                 WHEN 'GRAN' THEN 'Americas'
				                 WHEN 'DANC' THEN 'Americas'
				                 WHEN 'AUBA' THEN 'Aubange'
				                 WHEN 'AUB2' THEN 'Aubange'
				                 WHEN 'SHAN' THEN 'Shanghai'
				                 WHEN 'SING' THEN 'Singapore'
				                 WHEN 'SNG4' THEN 'Singapore'
				                 WHEN 'MUM3' THEN 'Mumbai'
				                 ELSE 'OTHER'
				            END
				        ",
				        null,
				        [EnableFolding = true]
				    ),
				    Typed = Table.TransformColumnTypes(
				        Data,
				        {
				            {"REGION", type text},
				            {"Branch Plant", type text},
				            {"Bulk Item", type text},
				            {"2nd Item Number", type text},
				            {"Status", type text},
				            {"KG/EA OH", type number},
				            {"LB/EA OH", type number},
				            {"Hard Commit", type number},
				            {"Primary UOM", type text}
				        },
				        "en-US"
				    )
				in
				    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

