table Inventory_Availability
	lineageTag: 3d5813f4-c0a8-4caf-a3cd-f8ac84758430

	measure 'Available Total' = SUM('Inventory_Availability'[AVAIL])
		formatString: #,0
		lineageTag: da422b77-4831-434c-b017-87c7ba33e020

	measure 'Inventory Lot Count' = DISTINCTCOUNT('Inventory_Availability'[AVAIL])
		formatString: 0
		lineageTag: 33923fdb-cd56-415e-b88d-2ebeb8f6fc5a

	column Plant
		dataType: string
		lineageTag: 274542e6-a521-4993-8e3d-3d1ad752a044
		summarizeBy: none
		sourceColumn: Plant

		annotation SummarizationSetBy = Automatic

	column Item
		dataType: string
		lineageTag: dcd72550-3ee8-4a2a-8a15-b2f9486db5fa
		summarizeBy: none
		sourceColumn: Item

		annotation SummarizationSetBy = Automatic

	column 'On Hand'
		dataType: double
		formatString: #,0
		lineageTag: cb499826-7dc5-4a96-92cd-30da30ed68c2
		summarizeBy: none
		sourceColumn: On Hand

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column Commit
		dataType: double
		formatString: #,0
		lineageTag: a72aa14f-ca79-4366-bb72-71713a848fad
		summarizeBy: none
		sourceColumn: Commit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column AVAIL
		dataType: double
		formatString: #,0
		lineageTag: 173ae146-3ede-475a-a9db-1665ecd6c28c
		summarizeBy: none
		sourceColumn: AVAIL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column Location
		dataType: string
		lineageTag: 865a0820-4817-4479-9704-8ce95006519e
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column Lot#
		dataType: string
		lineageTag: 364f2cde-5e79-4be4-931f-4a2caed1da36
		summarizeBy: none
		sourceColumn: Lot#

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 88ffc819-ebb0-41b2-9220-cf0f248c79b9
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Bulk
		dataType: string
		lineageTag: 9cfbd98d-dfa9-42a1-8d0f-ab72601372da
		summarizeBy: none
		sourceColumn: Bulk

		annotation SummarizationSetBy = Automatic

	partition Inventory_Availability = m
		mode: import
		source =
				let
				    Source = Sql.Database("ODSPROD", "ODS"),
				    Data = Value.NativeQuery(
				        Source,
				        "
				        SELECT
				            LTRIM(RTRIM(ib.IBMCU))                                   AS [Plant],
				            LTRIM(RTRIM(ib.IBLITM))                                  AS [Item],
				            il.LIPQOH / 10000.0                                      AS [On Hand],
				            il.LIHCOM / 10000.0                                      AS [Commit],
				            (CASE WHEN (il.LILOTS IS NULL OR LTRIM(RTRIM(il.LILOTS)) = '')
				                  THEN (il.LIPQOH - il.LIHCOM) / 10000.0
				                  ELSE 0 END)                                        AS [AVAIL],
				            il.LILOCN                                                AS [Location],
				            LTRIM(RTRIM(il.LILOTN))                                  AS [Lot#],
				            il.LILOTS                                                AS [Status],
				            LTRIM(RTRIM(tag.IMBULK))                                 AS [Bulk]
				        FROM PRODDTA.F4102 ib
				        INNER JOIN PRODDTA.F41021 il  ON ib.IBMCU = il.LIMCU AND ib.IBITM = il.LIITM
				        INNER JOIN PRODDTA.F4101 im   ON ib.IBITM = im.IMITM
				        INNER JOIN PRODDTA.F554101 tag ON im.IMITM = tag.IMITM
				        WHERE LTRIM(RTRIM(ib.IBMCU)) IN ('CINC','CIN2','CIN4')
				          AND il.LIPQOH / 10000.0 > 0
				          AND ( LTRIM(RTRIM(il.LILOTS)) <> '' OR (il.LIPQOH - il.LIHCOM) / 10000.0 > 0 )
				        ",
				        null,
				        [EnableFolding = true]
				    ),
				    Typed = Table.TransformColumnTypes(
				        Data,
				        {
				            {"Plant", type text},
				            {"Item", type text},
				            {"On Hand", type number},
				            {"Commit", type number},
				            {"AVAIL", type number},
				            {"Location", type text},
				            {"Lot#", type text},
				            {"Status", type text},
				            {"Bulk", type text}
				        }
				    )
				in
				    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

