table Shell_Kemper_All
	lineageTag: bc929a69-05cb-4968-b85c-10269bb8206a

	measure 'Number of Errors (All)' = CALCULATE(COUNTROWS('Shell_Kemper_All'), 'Shell_Kemper_All'[Owner] = "ERROR")
		formatString: 0
		lineageTag: d92dcae2-cc8a-4018-9a44-9e3bda1aa45f

	measure 'Row Background Color (All)' = IF(SELECTEDVALUE('Shell_Kemper_All'[Owner]) = "ERROR", "#FF0000")
		lineageTag: 1564f47f-5467-4e11-b661-868a896272fa

	measure 'Row Font Color (All)' = IF(SELECTEDVALUE('Shell_Kemper_All'[Owner]) = "ERROR", "#FFFFFF")
		lineageTag: e6dbd514-65c0-4f7e-aa3c-0d3ff8c3f466

	measure 'Error Card BG (All)' = IF([Number of Errors (All)] > 0, "#FF0000")
		lineageTag: 709da70a-54cf-465b-901b-b5e31571cc3b

	measure 'Error Card Font (All)' = IF([Number of Errors (All)] > 0, "#FFFFFF", "#000000")
		lineageTag: c5902455-0631-4374-bf32-4867fbbd8025

	column 'Promised Ship'
		dataType: dateTime
		formatString: MMM d, yyyy
		lineageTag: 33183774-a4fa-495d-8bf4-e3baa07b5ba5
		summarizeBy: none
		sourceColumn: Promised Ship

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Requested
		dataType: dateTime
		formatString: MMM d, yyyy
		lineageTag: 76531e27-b4a7-4c0d-96fc-98aa2e7e0e09
		summarizeBy: none
		sourceColumn: Requested

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Plant
		dataType: string
		lineageTag: f78df960-1894-497d-ac75-4d0b1185f1f3
		summarizeBy: none
		sourceColumn: Plant

		annotation SummarizationSetBy = Automatic

	column 'Ship To'
		dataType: string
		lineageTag: ba6f7864-d610-4509-9477-db3f49a49af6
		summarizeBy: none
		sourceColumn: Ship To

		annotation SummarizationSetBy = Automatic

	column CS
		dataType: string
		lineageTag: c83f3ab1-4301-4993-8673-4afbd8fe4c20
		summarizeBy: none
		sourceColumn: CS

		annotation SummarizationSetBy = Automatic

	column Order#
		dataType: int64
		formatString: 0
		lineageTag: 9a0536ff-e19d-45f0-b58a-8390a513e964
		summarizeBy: none
		sourceColumn: Order#

		annotation SummarizationSetBy = Automatic

	column Line#
		dataType: double
		lineageTag: a6bfc289-6358-49d5-b484-4a83ae777eae
		summarizeBy: none
		sourceColumn: Line#

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column Bulk
		dataType: string
		lineageTag: eb2a4673-6782-4534-b977-57efafc8dbb3
		summarizeBy: none
		sourceColumn: Bulk

		annotation SummarizationSetBy = Automatic

	column Item
		dataType: string
		lineageTag: cf3ffaca-e1ed-46fa-bd37-b964cb94aa3b
		summarizeBy: none
		sourceColumn: Item

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 5c7f8271-2f91-4c9b-82ea-e169a751e652
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column Owner
		dataType: string
		lineageTag: 8ef2bb26-b8da-4858-9492-43b7fe5b9228
		summarizeBy: none
		sourceColumn: Owner

		annotation SummarizationSetBy = Automatic

	column Planner
		dataType: int64
		formatString: 0
		lineageTag: f9ed2e17-fb9b-456c-af23-21ed53959003
		summarizeBy: none
		sourceColumn: Planner

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: f24ecd3a-125a-4b34-9029-a2a955332df4
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Primary Qty'
		dataType: double
		formatString: #,0
		lineageTag: 09d44848-6f98-42e5-985d-781293deff31
		summarizeBy: none
		sourceColumn: Primary Qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Primary UOM'
		dataType: string
		lineageTag: 20d71068-a955-4e1b-8b6d-444b2fdfb143
		summarizeBy: none
		sourceColumn: Primary UOM

		annotation SummarizationSetBy = Automatic

	column 'Secondary Qty'
		dataType: double
		formatString: #,0
		lineageTag: 11d0e4dc-1b4c-44ae-ad08-9f763fead889
		summarizeBy: none
		sourceColumn: Secondary Qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Secondary UOM'
		dataType: string
		lineageTag: 4d7178d9-448a-471e-8640-84043b0ad8b0
		summarizeBy: none
		sourceColumn: Secondary UOM

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: MMM d, yyyy
		lineageTag: a624db0a-e754-4ee2-b08c-5771b4b96ced
		summarizeBy: none
		sourceColumn: Order Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'CSR Name'
		dataType: string
		lineageTag: b7420a0d-caf4-401b-98df-8243092778d6
		summarizeBy: none
		sourceColumn: CSR Name

		annotation SummarizationSetBy = Automatic

	column 'Work Ctr'
		dataType: string
		lineageTag: fbf2943e-db9d-46c4-9ced-222d3e778e04
		summarizeBy: none
		sourceColumn: Work Ctr

		annotation SummarizationSetBy = Automatic

	column MPF
		dataType: string
		lineageTag: b931a98d-b7ff-4ee8-b923-d2a90af840d1
		summarizeBy: none
		sourceColumn: MPF

		annotation SummarizationSetBy = Automatic

	partition Shell_Kemper_All = m
		mode: import
		source =
				let
				    Source = Sql.Database("ODSPROD", "ODS"),
				    Data = Value.NativeQuery(
				        Source,
				        "
				        SELECT
				            mb.Promised_Ship_Date                                     AS [Promised Ship],
				            mb.Requested_Date                                         AS [Requested],
				            mb.Branch_Plant                                           AS [Plant],
				            mb.Customer_Name                                          AS [Ship To],
				            mb.Customer_Segmentation                                  AS [CS],
				            mb.Order_Number                                           AS [Order#],
				            mb.Order_Line                                             AS [Line#],
				            mb.Bulk_Item                                              AS [Bulk],
				            mb.C_2nd_Item_Number                                      AS [Item],
				            CASE mb.C_2nd_Item_Number
				                 WHEN 'NEWITEMFG'  THEN mb.Description_1
				                 WHEN 'NEWITEMPKG' THEN mb.Description_1
				                 ELSE ' '
				            END                                                       AS [Description],
				            CASE mb.Planner
				                 WHEN '324363' THEN 'Eric'
				                 WHEN '20444'  THEN 'Eric'
				                 WHEN '20445'  THEN 'Lance'
				                 WHEN '291740' THEN 'Mark Tilley'
				                 WHEN '328907' THEN 'Lance'
				                 WHEN '333530' THEN 'Lance'
				                 WHEN '316775' THEN 'Lance'
				                 WHEN '334927' THEN 'Tammy'
				                 WHEN '290808' THEN 'David Kramer'
				                 WHEN '335951' THEN 'Lance'
				                 WHEN '300021' THEN 'Tammy'
				                 WHEN '324287' THEN 'Brent'
				                 ELSE 'ERROR'
				            END                                                       AS [Owner],
				            mb.Planner                                                AS [Planner],
				            mb.Next_Status                                            AS [Status],
				            AVG(mb.Primary_Quantity_Ordered)                          AS [Primary Qty],
				            mb.Primary_UOM                                            AS [Primary UOM],
				            AVG(mb.Secondary_Quantity_Ordered)                        AS [Secondary Qty],
				            mb.Secondary_UOM                                          AS [Secondary UOM],
				            mb.Order_Date                                             AS [Order Date],
				            mb.CSR_Name                                               AS [CSR Name],
				            r.Work_Center                                             AS [Work Ctr],
				            mb.MPF                                                    AS [MPF]
				        FROM (
				            SELECT
				                m8.Branch_Plant, m8.CSR_Name, m8.Order_Number, m8.Order_Line,
				                m8.Customer_PO, m8.Customer_Name, m8.Customer_Segmentation,
				                m8.C_2nd_Item_Number, m8.Last_Status, m8.Next_Status, m8.Order_Date,
				                SUM(m8.Primary_Quantity_Ordered)   AS Primary_Quantity_Ordered,
				                m8.Primary_UOM, m8.Requested_Date, m8.Promised_Ship_Date,
				                SUM(m8.Secondary_Quantity_Ordered) AS Secondary_Quantity_Ordered,
				                m8.Secondary_UOM, m8.MPF, m8.Description_1,
				                i9.Bulk_Item, i9.Planner
				            FROM (
				                SELECT
				                    so.SDKCOO                          AS Order_Company,
				                    LTRIM(RTRIM(so.SDMCU))             AS Branch_Plant,
				                    LTRIM(RTRIM(csr.ABALPH))           AS CSR_Name,
				                    so.SDDOCO                          AS Order_Number,
				                    so.SDLNID / 1000.0                 AS Order_Line,
				                    so.SDVR01                          AS Customer_PO,
				                    LTRIM(RTRIM(cust.ABALPH))          AS Customer_Name,
				                    LTRIM(RTRIM(cust.ABAC06))          AS Customer_Segmentation,
				                    LTRIM(RTRIM(so.SDLITM))            AS C_2nd_Item_Number,
				                    so.SDLTTR                          AS Last_Status,
				                    so.SDNXTR                          AS Next_Status,
				                    (CASE WHEN so.SDTRDJ > 0
				                          THEN DATEADD(DAY, (so.SDTRDJ % 1000) - 1, DATEFROMPARTS(1900 + (so.SDTRDJ / 1000), 1, 1))
				                     END)                              AS Order_Date,
				                    SUM(so.SDPQOR / 10000.0)           AS Primary_Quantity_Ordered,
				                    so.SDUOM1                          AS Primary_UOM,
				                    (CASE WHEN so.SDDRQJ > 0
				                          THEN DATEADD(DAY, (so.SDDRQJ % 1000) - 1, DATEFROMPARTS(1900 + (so.SDDRQJ / 1000), 1, 1))
				                     END)                              AS Requested_Date,
				                    (CASE WHEN so.SDPDDJ > 0
				                          THEN DATEADD(DAY, (so.SDPDDJ % 1000) - 1, DATEFROMPARTS(1900 + (so.SDPDDJ / 1000), 1, 1))
				                     END)                              AS Promised_Ship_Date,
				                    SUM(so.SDSQOR / 10000.0)           AS Secondary_Quantity_Ordered,
				                    so.SDUOM2                          AS Secondary_UOM,
				                    so.SDPRP4                          AS MPF,
				                    LTRIM(RTRIM(so.SDDSC1))            AS Description_1
				                FROM PRODDTA.F4211 so
				                INNER JOIN PRODDTA.F0101 cust ON so.SDSHAN = cust.ABAN8
				                LEFT OUTER JOIN (
				                    SELECT cm.CMAN8, ab.ABALPH
				                    FROM PRODDTA.F42140 cm
				                    JOIN PRODDTA.F0101 ab ON cm.CMSLSM = ab.ABAN8
				                    WHERE cm.CMRTYPE = 'CSR'
				                ) csr ON so.SDSHAN = csr.CMAN8
				                WHERE so.SDNXTR IN ('525','530','535','540','545','550')
				                  AND so.SDKCOO = '00010'
				                GROUP BY
				                    so.SDKCOO, LTRIM(RTRIM(so.SDMCU)), LTRIM(RTRIM(csr.ABALPH)),
				                    so.SDDOCO, so.SDLNID / 1000.0, so.SDVR01,
				                    LTRIM(RTRIM(cust.ABALPH)), LTRIM(RTRIM(cust.ABAC06)),
				                    LTRIM(RTRIM(so.SDLITM)), so.SDLTTR, so.SDNXTR,
				                    (CASE WHEN so.SDTRDJ > 0
				                          THEN DATEADD(DAY, (so.SDTRDJ % 1000) - 1, DATEFROMPARTS(1900 + (so.SDTRDJ / 1000), 1, 1))
				                     END),
				                    so.SDUOM1,
				                    (CASE WHEN so.SDDRQJ > 0
				                          THEN DATEADD(DAY, (so.SDDRQJ % 1000) - 1, DATEFROMPARTS(1900 + (so.SDDRQJ / 1000), 1, 1))
				                     END),
				                    (CASE WHEN so.SDPDDJ > 0
				                          THEN DATEADD(DAY, (so.SDPDDJ % 1000) - 1, DATEFROMPARTS(1900 + (so.SDPDDJ / 1000), 1, 1))
				                     END),
				                    so.SDUOM2, so.SDPRP4, LTRIM(RTRIM(so.SDDSC1))
				            ) m8
				            INNER JOIN (
				                SELECT DISTINCT
				                    LTRIM(RTRIM(ib.IBMCU))   AS Branch_Plant,
				                    LTRIM(RTRIM(tag.IMBULK)) AS Bulk_Item,
				                    LTRIM(RTRIM(ib.IBLITM))  AS C_2nd_Item_Number,
				                    ib.IBANPL                AS Planner
				                FROM PRODDTA.F4102 ib
				                JOIN PRODDTA.F4101 im  ON ib.IBITM = im.IMITM
				                JOIN PRODDTA.F554101 tag ON im.IMITM = tag.IMITM
				            ) i9
				              ON m8.Branch_Plant = i9.Branch_Plant
				             AND m8.C_2nd_Item_Number = i9.C_2nd_Item_Number
				            GROUP BY
				                m8.Order_Company, m8.Branch_Plant, m8.CSR_Name, m8.Order_Number,
				                m8.Order_Line, m8.Customer_PO, m8.Customer_Name, m8.Customer_Segmentation,
				                m8.C_2nd_Item_Number, m8.Last_Status, m8.Next_Status, m8.Order_Date,
				                m8.Primary_UOM, m8.Requested_Date, m8.Promised_Ship_Date,
				                m8.Secondary_UOM, m8.MPF, m8.Description_1,
				                i9.Branch_Plant, i9.Bulk_Item, i9.C_2nd_Item_Number, i9.Planner
				        ) mb
				        FULL OUTER JOIN (
				            SELECT DISTINCT
				                LTRIM(RTRIM(cp.CWMMCU)) AS Item_Branch,
				                LTRIM(RTRIM(ib.IBLITM)) AS C_2nd_Item_Number,
				                LTRIM(RTRIM(cp.CWMCU))  AS Work_Center
				            FROM PRODDTA.F3312 cp
				            JOIN PRODDTA.F4102 ib ON cp.CWITM = ib.IBITM AND cp.CWWMCU = ib.IBMCU
				            JOIN PRODDTA.F3313 cl ON cp.CWMCU  = cl.CRMCU
				                                 AND cp.CWCAPM = cl.CRCAPM
				                                 AND cp.CWDRQJ = cl.CRSTRT
				                                 AND cp.CWWMCU = cl.CRWMCU
				            WHERE LTRIM(RTRIM(cp.CWMMCU)) IN ('CINC','CIN2')
				              AND LTRIM(RTRIM(ib.IBLITM)) NOT LIKE '%-%'
				              AND LTRIM(RTRIM(cp.CWMCU)) IN
				                  ('SREC23','SREC37','SREC48','SREC72','SREC130','SDMD','SPEC','SPREC',
				                   'SECG','SE2','SCOLD','SPDMD','SPCOLD','SLAB','SRENAME','SREPACK',
				                   'SHILDA','KLAB','KBB','KSB','KWG','KBOT','KREPACK','KRENAME')
				              AND cp.CWDOCO = 0
				              AND (CASE WHEN cp.CWDRQJ > 0
				                        THEN DATEADD(DAY, (cp.CWDRQJ % 1000) - 1, DATEFROMPARTS(1900 + (cp.CWDRQJ / 1000), 1, 1))
				                        ELSE DATEFROMPARTS(1900, 1, 1)
				                   END) > DATEADD(DAY, 31, CAST(GETDATE() AS date))
				        ) r
				          ON mb.Bulk_Item = r.C_2nd_Item_Number
				        WHERE mb.C_2nd_Item_Number IS NOT NULL
				        GROUP BY
				            mb.Branch_Plant, mb.CSR_Name, mb.Order_Number, mb.Order_Line,
				            mb.Customer_Name, mb.Customer_Segmentation, mb.C_2nd_Item_Number,
				            mb.Next_Status, mb.Primary_UOM, mb.Secondary_UOM, mb.Order_Date,
				            mb.Requested_Date, mb.Promised_Ship_Date, mb.MPF, mb.Bulk_Item,
				            r.Work_Center, mb.Planner,
				            CASE mb.Planner
				                 WHEN '324363' THEN 'Eric'      WHEN '20444'  THEN 'Eric'
				                 WHEN '20445'  THEN 'Lance'     WHEN '291740' THEN 'Mark Tilley'
				                 WHEN '328907' THEN 'Lance'     WHEN '333530' THEN 'Lance'
				                 WHEN '316775' THEN 'Lance'     WHEN '334927' THEN 'Tammy'
				                 WHEN '290808' THEN 'David Kramer' WHEN '335951' THEN 'Lance'
				                 WHEN '300021' THEN 'Tammy'     WHEN '324287' THEN 'Brent'
				                 ELSE 'ERROR'
				            END,
				            CASE mb.C_2nd_Item_Number
				                 WHEN 'NEWITEMFG'  THEN mb.Description_1
				                 WHEN 'NEWITEMPKG' THEN mb.Description_1
				                 ELSE ' '
				            END
				        ",
				        null,
				        [EnableFolding = true]
				    ),
				    Typed = Table.TransformColumnTypes(
				        Data,
				        {
				            {"Promised Ship", type date},
				            {"Requested", type date},
				            {"Plant", type text},
				            {"Ship To", type text},
				            {"CS", type text},
				            {"Order#", Int64.Type},
				            {"Line#", type number},
				            {"Bulk", type text},
				            {"Item", type text},
				            {"Description", type text},
				            {"Owner", type text},
				            {"Planner", Int64.Type},
				            {"Status", type text},
				            {"Primary Qty", type number},
				            {"Primary UOM", type text},
				            {"Secondary Qty", type number},
				            {"Secondary UOM", type text},
				            {"Order Date", type date},
				            {"CSR Name", type text},
				            {"Work Ctr", type text},
				            {"MPF", type text}
				        }
				    )
				in
				    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

