table 'Reason Codes'
	lineageTag: 3de6b8a3-9e1d-41c1-ab59-05a7e881c7d0

	column Code
		dataType: string
		lineageTag: 3f4d7671-3e18-4ac4-98a7-e8ca8a49cd24
		summarizeBy: none
		sourceColumn: Code

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: a8c420b4-96ef-4b43-b9db-1c29c81a06c1
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column Description_1
		dataType: string
		lineageTag: 7c486455-8f27-40f3-a380-b393bb95769e
		summarizeBy: none
		sourceColumn: Description_1

		annotation SummarizationSetBy = Automatic

	column OTIF
		dataType: string
		lineageTag: 3bb04f90-85d4-457c-a886-985c3fc70dbc
		summarizeBy: none
		sourceColumn: OTIF

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: a8f86400-17f6-4c2d-b0e5-8e48a1adbbf4
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'OTIF Y/N' = IF('Reason Codes'[OTIF]="X" || 'Reason Codes'[OTIF]= "X ", "Y","N")
		lineageTag: bd4fe419-e89f-4f4b-b934-1b690a49a4d2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Revision Reason & Description' = 'Reason Codes'[Code] & " - " & 'Reason Codes'[Description]
		lineageTag: bbcf773d-6960-4585-b557-9e23118a302f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// OTIF-hit exemption criteria, editable in the Reason Code Editor visual (D1 reason_dim).
	column 'Exemption Criteria'
		dataType: string
		lineageTag: 47afceea-4626-445a-b18d-4bdcee61fc9f
		summarizeBy: none
		sourceColumn: Exemption Criteria

	/// Dimension-row validity (0 = retired / 'do not use'). Independent of the OTIF flag.
	column Active
		dataType: boolean
		lineageTag: 622a071a-b044-47bf-8464-4d4339351281
		summarizeBy: none
		sourceColumn: Active

	partition 'Reason Codes' = m
		mode: import
		source =
				let
				    BaseUrl = "https://michelman-writeback.michelman-bi.workers.dev",
				    Secret  = "2dd9c06c0d1c63e82ee7740c3ac61be1c5ec14c2455bbd45e97c67995a5ecf2c",
				    Headers = [ #"x-secret" = Secret ],
				    // Cache-buster: Web.Contents caches by URL, so without a varying query param a
				    // refresh can serve a stale reason dim after a Reason Code Editor change.
				    Stamp = Text.From(Int64.From(Duration.TotalSeconds(DateTimeZone.UtcNow() - #datetimezone(2020,1,1,0,0,0,0,0)))),
				    // Reason-code dimension loaded from D1 (worker /reason-dim) — REPLACES the
				    // SharePoint spreadsheet. Maintained in the Reason Code Editor visual.
				    Raw = Json.Document(Web.Contents(BaseUrl, [RelativePath = "reason-dim", Query = [ _cb = Stamp ], Headers = Headers])),
				    AsTable = Table.FromRecords(Raw),
				    // Effective OTIF flag drives FactScheduleChange[Is OTIF Relevant]: "X" iff otif=true.
				    Renamed = Table.RenameColumns(AsTable, {{"code","Code"},{"description","Description"},{"longDescription","Description_1"},{"exemptionCriteria","Exemption Criteria"},{"category","Category"},{"active","Active"}}),
				    AddOtif = Table.AddColumn(Renamed, "OTIF", each if [otif] = true then "X" else "", type text),
				    Selected = Table.SelectColumns(AddOtif, {"Code","Description","Description_1","OTIF","Category","Exemption Criteria","Active"}),
				    Typed = Table.TransformColumnTypes(Selected, {{"Code", type text},{"Description", type text},{"Description_1", type text},{"OTIF", type text},{"Category", type text},{"Exemption Criteria", type text},{"Active", type logical}}),
				    Filtered = Table.SelectRows(Typed, each [Code] <> null and Text.Trim([Code]) <> "")
				in
				    Filtered

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

