table FactSalesDetail
	lineageTag: b8b0720f-9250-48fc-8769-ecf8dd16b18c

	/// Region for the order company: 10 Americas, 20 EMEA, 30/34/35 Asia, anything else Unmapped. Join key to 'Dim Region'[Region].
	column Region =
			SWITCH (
			    VALUE ( 'FactSalesDetail'[Order Company] ),
			    10, "Americas",
			    20, "EMEA",
			    30, "Asia",
			    34, "Asia",
			    35, "Asia",
			    "Unmapped"
			)
		lineageTag: 65933f8c-5840-4383-951c-c620f0b06ee3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Order Num'
		dataType: string
		lineageTag: 001028e4-4f79-488c-a402-df95c4126894
		summarizeBy: none
		sourceColumn: Order Num

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Order Company'
		dataType: string
		lineageTag: 95b25c2b-5851-4182-9cd0-350357fcebe5
		summarizeBy: none
		sourceColumn: Order Company

		annotation SummarizationSetBy = Automatic

	column 'Order Type'
		dataType: string
		lineageTag: 7706d233-0aae-49bf-b641-c4acabde71fa
		summarizeBy: none
		sourceColumn: Order Type

		annotation SummarizationSetBy = Automatic

	column 'Order Suffix'
		dataType: string
		lineageTag: db598c56-78bc-4e30-92a1-7fc23c088b95
		summarizeBy: none
		sourceColumn: Order Suffix

		annotation SummarizationSetBy = Automatic

	column 'Line Num'
		dataType: double
		formatString: 0.000
		lineageTag: bf3e53a8-94b8-46a6-8562-54c6bd779368
		summarizeBy: sum
		sourceColumn: Line Num

		annotation SummarizationSetBy = Automatic

	column 'Line Type'
		dataType: string
		lineageTag: 5ca5d608-5f12-4af8-a297-b7c1f4a3af4d
		summarizeBy: none
		sourceColumn: Line Type

		annotation SummarizationSetBy = Automatic

	column 'Actual Ship Date'
		dataType: dateTime
		formatString: m/d/yy
		lineageTag: 03b86d24-d828-4dbf-9153-c32f4f552d7e
		summarizeBy: none
		sourceColumn: Actual Ship Date

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

		annotation UnderlyingDateTimeDataType = Date

	column 'Qty Ordered'
		dataType: double
		formatString: #,##0
		lineageTag: 7d14e818-ab01-48f0-86e4-00e5ec024164
		summarizeBy: sum
		sourceColumn: Qty Ordered

		annotation SummarizationSetBy = Automatic

	column 'Qty Shipped'
		dataType: double
		formatString: #,##0
		lineageTag: aad01150-f435-4348-8a46-88a31d45bae1
		summarizeBy: sum
		sourceColumn: Qty Shipped

		annotation SummarizationSetBy = Automatic

	column 'Qty Cancelled'
		dataType: double
		lineageTag: b3f1b91c-f338-4d23-9f6c-d8f0f1bf8b1e
		summarizeBy: sum
		sourceColumn: Qty Cancelled

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Promised Delivery Date'
		dataType: dateTime
		formatString: m/d/yy
		lineageTag: 43d4073b-16af-4c67-8ead-70fec20cdae8
		summarizeBy: none
		sourceColumn: Promised Delivery Date

		variation Variation
			isDefault
			relationship: db565d02-fba9-44f6-9af8-dd9bf39a7858
			defaultHierarchy: LocalDateTable_d88802b0-b5e3-4797-8662-ad27309d85f5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

		annotation UnderlyingDateTimeDataType = Date

	column 'Requested Date'
		dataType: dateTime
		formatString: m/d/yy
		lineageTag: 7c5d2c5a-2573-4c35-8f9a-d07c63c67875
		summarizeBy: none
		sourceColumn: Requested Date

		variation Variation
			isDefault
			relationship: 9a97c9a8-757b-4f83-8145-bf208c37649d
			defaultHierarchy: LocalDateTable_4bf7e9d2-8adb-466d-8ac2-fd9f503cf7ac.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

		annotation UnderlyingDateTimeDataType = Date

	column 'Promised Shipment Date'
		dataType: dateTime
		formatString: m/d/yy
		lineageTag: fcd59819-4e00-459e-8a5c-b5076756d0cf
		summarizeBy: none
		sourceColumn: Promised Shipment Date

		variation Variation
			isDefault
			relationship: 68476c34-2555-412e-82da-89df2c38cd2a
			defaultHierarchy: LocalDateTable_d4236cc6-26db-4ccf-aa36-b8f9b45bcdcf.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

		annotation UnderlyingDateTimeDataType = Date

	column 'Original Promised Delivery Date'
		dataType: dateTime
		formatString: m/d/yy
		lineageTag: d514da0b-d5f0-4013-b3b6-7d9634d6af23
		summarizeBy: none
		sourceColumn: Original Promised Delivery Date

		variation Variation
			isDefault
			relationship: 47bd4713-117a-402e-9f98-90829cceddd8
			defaultHierarchy: LocalDateTable_0eeb6476-51d6-40d1-a1b7-d3b41e9a0cbe.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Product Description'
		dataType: string
		lineageTag: 569e48d6-55a3-4f95-b952-cd41842c2acc
		summarizeBy: none
		sourceColumn: Product Description

	column 'Product Description 2'
		dataType: string
		lineageTag: 24a7af13-2809-4c5d-8911-437baf4df69d
		summarizeBy: none
		sourceColumn: Product Description 2

	column 'Item Num 2nd'
		dataType: string
		lineageTag: bd2ac56f-b454-46c0-bddc-3d4109a9d3bd
		summarizeBy: none
		sourceColumn: Item Num 2nd

	column 'Ext Price'
		dataType: double
		lineageTag: 2e700c68-c6e1-4a1f-b6be-c2a9ddfc57d2
		summarizeBy: sum
		sourceColumn: Ext Price

	/// Line-grain key: Order Company, Order Num, Order Type, Order Suffix and Line Num joined by a pipe. Counted by [Order Lines].
	column OrderKey = ```
			
			    'FactSalesDetail'[Order Company] & "|"
			    & FORMAT('FactSalesDetail'[Order Num],"0") & "|"
			    & 'FactSalesDetail'[Order Type] & "|"
			    & 'FactSalesDetail'[Order Suffix] & "|"
			    & FORMAT('FactSalesDetail'[Line Num],"0")
			```
		lineageTag: 0da1872a-abce-4605-a10e-5966c5b075bf
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Constant 0.99, for a fixed reference line on order charts.
	column 'Target Line' = .99
		formatString: 0%;-0%;0%
		lineageTag: d4a25b86-bf5a-4977-8c73-201cebdac45c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// 1 when the line has no OTIF-relevant revision, else 0. Stored flag behind the static on-time measures.
	column 'On Time' = IF(CALCULATE(COUNTROWS(FactScheduleChange),FactScheduleChange[Is OTIF Relevant]=true)>0,0,1)
		formatString: 0
		lineageTag: feb97855-2598-4903-9344-1c99dbf43398
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// 1 when the line has at least one OTIF-relevant revision, else 0. Complement of [On Time].
	column Late = IF(CALCULATE(COUNTROWS(FactScheduleChange),FactScheduleChange[Is OTIF Relevant]=true)>0,1,0)
		formatString: 0
		lineageTag: cc97c313-5230-4aa9-b666-310ef2b0515d
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'GL Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 542aae0e-c11a-4bc3-94cf-d5b25b771b38
		summarizeBy: none
		sourceColumn: GL Date

		variation Variation
			isDefault
			relationship: 24abf97a-c702-42a8-b409-e4e6d7b09a8a
			defaultHierarchy: LocalDateTable_72f5362f-44d4-4aee-9670-ad25b3d08d31.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Business Unit'
		dataType: string
		lineageTag: 6616ef33-afaa-4cb1-ac5d-cc9763737204
		summarizeBy: none
		sourceColumn: Business Unit

		annotation SummarizationSetBy = Automatic

	column 'Status Code Last'
		dataType: string
		lineageTag: 4150e44e-6578-4b64-9e83-122687d0e67a
		summarizeBy: none
		sourceColumn: Status Code Last

		annotation SummarizationSetBy = Automatic

	column 'Invoice Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: a5ce6376-9873-4228-b479-d1db768182d7
		summarizeBy: none
		sourceColumn: Invoice Date

		variation Variation
			isDefault
			relationship: ddb0eb11-18e6-4049-a18d-4cc9b258911a
			defaultHierarchy: LocalDateTable_e5c26f2e-4779-47cd-b30c-024ab4d9444e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Order Date'
		dataType: dateTime
		formatString: m/d/yy
		lineageTag: 529def87-2f7e-4681-9285-4169f8fd829d
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: fd35a0cc-6e13-4387-8635-517cb7955585
			defaultHierarchy: LocalDateTable_e6eec35d-782d-4c61-a7fb-60d04ee0ebaf.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Revision Reason'
		dataType: string
		lineageTag: 896bc289-9603-41e1-a913-68b7e9d6f0de
		summarizeBy: none
		sourceColumn: Revision Reason

		annotation SummarizationSetBy = Automatic

	column 'Flag Positive Volume'
		dataType: int64
		formatString: 0
		lineageTag: 8220fbe9-786d-410b-9074-c55c21bce4ca
		summarizeBy: sum
		sourceColumn: Flag Positive Volume

		annotation SummarizationSetBy = Automatic

	column 'Flag Line Type S'
		dataType: int64
		formatString: 0
		lineageTag: 8b0042bf-a11b-41b5-ae0a-ca40b0d04899
		summarizeBy: sum
		sourceColumn: Flag Line Type S

		annotation SummarizationSetBy = Automatic

	column 'Flag Not Sched'
		dataType: int64
		formatString: 0
		lineageTag: 6f98e8a2-ad07-44b2-b529-14c6d71ce613
		summarizeBy: sum
		sourceColumn: Flag Not Sched

		annotation SummarizationSetBy = Automatic

	column 'Flag Updated In Cognos Window'
		dataType: int64
		formatString: 0
		lineageTag: 4cd7aa54-7583-4650-92fd-41dcb05d9b3b
		summarizeBy: sum
		sourceColumn: Flag Updated In Cognos Window

		annotation SummarizationSetBy = Automatic

	column 'Flag Not India Tax'
		dataType: int64
		formatString: 0
		lineageTag: 4f4f30c0-a11f-40fd-9ef5-3dfc6c3d2f68
		summarizeBy: sum
		sourceColumn: Flag Not India Tax

		annotation SummarizationSetBy = Automatic

	column 'Line Type Desc'
		dataType: string
		lineageTag: 4293479b-b0ce-4fad-b110-f99c8d66269f
		summarizeBy: none
		sourceColumn: Line Type Desc

		annotation SummarizationSetBy = Automatic

	column 'Record Type'
		dataType: string
		lineageTag: f7cb2b34-18c5-407d-9a5a-6ff0f106420a
		summarizeBy: none
		sourceColumn: Record Type

		annotation SummarizationSetBy = Automatic

	column Cancelled_Flag
		dataType: int64
		formatString: 0
		lineageTag: ee0ed31a-d4bc-4b2a-b7b4-84ae0a18bae7
		summarizeBy: sum
		sourceColumn: Cancelled_Flag

		annotation SummarizationSetBy = Automatic

	column LotSKey
		dataType: int64
		formatString: 0
		lineageTag: 7bebd26c-6152-43dc-9a23-5f31824e101b
		summarizeBy: count
		sourceColumn: LotSKey

		annotation SummarizationSetBy = Automatic

	column 'Lot Num'
		dataType: string
		lineageTag: bfb4ad8d-4847-4b6f-81ff-231cad354c2a
		summarizeBy: none
		sourceColumn: Lot Num

		annotation SummarizationSetBy = Automatic

	column ShipToCustomerSKey
		dataType: int64
		formatString: 0
		lineageTag: d2e65973-9a32-4134-ae8b-ed1935e10a09
		summarizeBy: count
		sourceColumn: ShipToCustomerSKey

		annotation SummarizationSetBy = Automatic

	column 'Scheduled Pick Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6ef748c7-8855-4457-b315-21c7425e1d46
		summarizeBy: none
		sourceColumn: Scheduled Pick Date

		variation Variation
			isDefault
			relationship: 2b54426c-0702-4c0f-9ae6-8d60f4d42b48
			defaultHierarchy: LocalDateTable_312c60d9-476c-4691-b62c-7ef5ea247995.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Item Num'
		dataType: int64
		formatString: 0
		lineageTag: c7393103-55c2-47d5-a12d-9b223593309b
		summarizeBy: sum
		sourceColumn: Item Num

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: 22d9942b-da1f-4e06-832e-652e6bdcdf00
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column 'Business Unit Revenue'
		dataType: string
		lineageTag: bdcd8469-ff4f-4d92-83c2-6e3eb2742630
		summarizeBy: none
		sourceColumn: Business Unit Revenue

		annotation SummarizationSetBy = Automatic

	column 'Order Taken By'
		dataType: string
		lineageTag: e737351b-7d71-4a67-be1a-8f97d644155d
		summarizeBy: none
		sourceColumn: Order Taken By

		annotation SummarizationSetBy = Automatic

	column 'Ordered By'
		dataType: string
		lineageTag: 2123c142-8e5e-47a2-b5c7-dc91fed79f67
		summarizeBy: none
		sourceColumn: Ordered By

		annotation SummarizationSetBy = Automatic

	column 'Shipment Num'
		dataType: int64
		formatString: 0
		lineageTag: 446aaa94-134c-48ac-8678-6860968fa973
		summarizeBy: sum
		sourceColumn: Shipment Num

		annotation SummarizationSetBy = Automatic

	column 'Bill Of Lading'
		dataType: string
		lineageTag: be7bdac3-2eac-4793-8cb2-9b97b347743f
		summarizeBy: none
		sourceColumn: Bill Of Lading

		annotation SummarizationSetBy = Automatic

	column 'Order Line ID'
		dataType: string
		lineageTag: e1e0eb7e-4c3d-4821-931d-1634b9deee6f
		summarizeBy: none
		sourceColumn: Order Line ID

		annotation SummarizationSetBy = Automatic

	column 'Order Header ID'
		dataType: string
		lineageTag: a245f151-4de8-4afa-8593-418ae0de70bd
		summarizeBy: none
		sourceColumn: Order Header ID

		annotation SummarizationSetBy = Automatic

	column 'Serial Num Lot'
		dataType: string
		lineageTag: fe5a1b78-cf7d-4746-8132-0234393a262c
		summarizeBy: none
		sourceColumn: Serial Num Lot

		annotation SummarizationSetBy = Automatic

	column 'Amount Open'
		dataType: double
		lineageTag: c9f20fac-fef7-4a5c-9a5a-81663f49fe78
		summarizeBy: sum
		sourceColumn: Amount Open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Qty Backordered'
		dataType: double
		lineageTag: 69d539ff-261b-443a-b807-9b1bd347ff39
		summarizeBy: sum
		sourceColumn: Qty Backordered

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Qty Open'
		dataType: double
		lineageTag: abe4d1b8-a24c-49ff-9b6e-30cdd7650a69
		summarizeBy: sum
		sourceColumn: Qty Open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Qty Shipped To Date'
		dataType: double
		lineageTag: 9d007149-9b14-483c-a9a3-b423957bb84e
		summarizeBy: sum
		sourceColumn: Qty Shipped To Date

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Gross Weight'
		dataType: double
		lineageTag: b9bfabe4-3cee-446d-a42c-9d3f0d5eea91
		summarizeBy: sum
		sourceColumn: Gross Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unit Weight'
		dataType: double
		lineageTag: 085d1c0d-5fdb-483a-af9a-fdc0bb6415bd
		summarizeBy: sum
		sourceColumn: Unit Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Hold Code'
		dataType: string
		lineageTag: e749811d-e2be-4ae3-9737-1393eed4c1e8
		summarizeBy: none
		sourceColumn: Hold Code

		annotation SummarizationSetBy = Automatic

	column 'Reason Code'
		dataType: string
		lineageTag: d3921d6e-2122-4589-b0a0-6223ac5021c7
		summarizeBy: none
		sourceColumn: Reason Code

		annotation SummarizationSetBy = Automatic

	column 'Reason Code Desc'
		dataType: string
		lineageTag: 19de1dc5-a876-4b09-9e4a-3f4930d622cd
		summarizeBy: none
		sourceColumn: Reason Code Desc

		annotation SummarizationSetBy = Automatic

	column 'Mode Of Transport'
		dataType: string
		lineageTag: 3813e432-fd6b-4725-9d66-6c8095dcdf06
		summarizeBy: none
		sourceColumn: Mode Of Transport

		annotation SummarizationSetBy = Automatic

	column 'Carrier Num'
		dataType: int64
		formatString: 0
		lineageTag: cc3e6dac-aad6-4ac0-b5e2-35c8782d7e03
		summarizeBy: sum
		sourceColumn: Carrier Num

		annotation SummarizationSetBy = Automatic

	column 'Freight Handling Code'
		dataType: string
		lineageTag: ada6de0c-23f3-45bb-a446-d25b0dc53ce8
		summarizeBy: none
		sourceColumn: Freight Handling Code

		annotation SummarizationSetBy = Automatic

	column 'Cancel Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: fa7d95bb-bb0f-44ab-bd4b-4fffb310624a
		summarizeBy: none
		sourceColumn: Cancel Date

		variation Variation
			isDefault
			relationship: 7d7eafbf-82fe-43b9-a1f3-2651c573acc9
			defaultHierarchy: LocalDateTable_05ed4563-576e-401d-a78b-f21012367a09.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ShipToAddressSKey
		dataType: int64
		formatString: 0
		lineageTag: ce6eb2ed-479b-4c00-84af-910c0d21550a
		summarizeBy: none
		sourceColumn: ShipToAddressSKey

		annotation SummarizationSetBy = Automatic

	column SoldToAddressSKey
		dataType: int64
		formatString: 0
		lineageTag: ecb449bd-1360-4e6b-a193-3fdb5abb984b
		summarizeBy: none
		sourceColumn: SoldToAddressSKey

		annotation SummarizationSetBy = Automatic

	column SoldToCustomerSKey
		dataType: int64
		formatString: 0
		lineageTag: 26b0b9b2-c875-49c4-aa65-0a0316360337
		summarizeBy: count
		sourceColumn: SoldToCustomerSKey

		annotation SummarizationSetBy = Automatic

	column ParentCustomerSKey
		dataType: int64
		formatString: 0
		lineageTag: 337fb18c-c032-4269-8f05-c790031a12fa
		summarizeBy: count
		sourceColumn: ParentCustomerSKey

		annotation SummarizationSetBy = Automatic

	column ItemSKey
		dataType: int64
		formatString: 0
		lineageTag: 235e4939-0cc9-4c1b-b575-27ec977b6c61
		summarizeBy: count
		sourceColumn: ItemSKey

		annotation SummarizationSetBy = Automatic

	column 'Updated Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3574903c-f979-482f-9edd-d702d30468bb
		summarizeBy: none
		sourceColumn: Updated Date

		variation Variation
			isDefault
			relationship: ea6bc5a7-c477-44e8-afcb-a36dce4cdb48
			defaultHierarchy: LocalDateTable_bbd50264-c981-4764-b26f-0335ae087307.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Updated By'
		dataType: string
		lineageTag: a9b126c0-9e59-4a93-beeb-81adcd6a4dad
		summarizeBy: none
		sourceColumn: Updated By

		annotation SummarizationSetBy = Automatic

	column 'Conversion Factor LB'
		dataType: double
		lineageTag: 0d342cb9-42c8-40fa-8ce6-baa92dfbb258
		summarizeBy: sum
		sourceColumn: Conversion Factor LB

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Sales Factor'
		dataType: double
		lineageTag: 3cec0312-4337-4caf-8be6-af9a53d1a4b2
		summarizeBy: sum
		sourceColumn: Sales Factor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Total forward promised-date movement, in days, across the line's OTIF-relevant revisions. Negative moves are excluded, so pull-ins do not offset slips.
	column 'Days Moved' = CALCULATE(SUM(FactScheduleChange[Days Moved]),FactScheduleChange[OTIF Relevant]=1,FactScheduleChange[Days Moved]>0)
		formatString: 0
		lineageTag: f6b28436-146b-447e-b5c7-9799c2074695
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// Actual lead time in days: Actual Ship Date minus Order Date.
	column 'Actual Order to Ship LT' = 'FactSalesDetail'[Actual Ship Date] - 'FactSalesDetail'[Order Date]
		dataType: int64
		formatString: 0
		lineageTag: 7ca40ef9-22d1-40f8-a12c-0bcb5bfffa2a
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	/// Comma-separated list of the line's OTIF-relevant revision reasons, each followed by its total days moved.
	column 'Revision Reasons' =
			
			VAR RelevantRows =
			    FILTER (
			        RELATEDTABLE ( FactScheduleChange ),
			        FactScheduleChange[Is OTIF Relevant] = TRUE()
			            && NOT ISBLANK ( FactScheduleChange[RevisionReason] )
			    )
			VAR ReasonSummary =
			    GROUPBY (
			        RelevantRows,
			        FactScheduleChange[RevisionReason],
			        "TotalDaysMoved",
			            SUMX ( CURRENTGROUP (), FactScheduleChange[Days Moved] )
			    )
			RETURN
			    CONCATENATEX (
			        ReasonSummary,
			        FactScheduleChange[RevisionReason]
			            & " ("
			            & [TotalDaysMoved]
			            & " Days)",
			        ", ",
			        FactScheduleChange[RevisionReason],
			        ASC
			    )
		lineageTag: f29352e6-d5fe-4ec2-9911-c99a78eb2c14
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// 1 when Actual Ship Date is on or before Requested Date, else 0. An unshipped line carries the JDE empty ship date, which precedes any requested date and so scores as 1.
	column 'Shipped as Requested' = IF('FactSalesDetail'[Actual Ship Date]<='FactSalesDetail'[Requested Date],1,0)
		formatString: 0
		lineageTag: f331e23a-59e2-4227-93f3-8d344962ff65
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// On-time flag scored on the original JDE reason codes, ignoring Revision Log Editor overrides and exclusions.
	column 'On Time (As Reported)' = IF(CALCULATE(COUNTROWS(FactScheduleChange),FactScheduleChange[Is OTIF Relevant (As Reported)]=true)>0,0,1)
		dataType: int64
		formatString: 0
		lineageTag: eec51f0a-c39b-4ca4-acce-d7d0a2d315ef
		summarizeBy: sum

	/// Line number formatted to three decimals, matching the line-number component of the revision ledger's OrderLineID.
	column 'Line Num Text' = FORMAT ( 'FactSalesDetail'[Line Num], "0.000" )
		dataType: string
		lineageTag: 83f4ece4-2053-4439-8697-47f3978217bb
		summarizeBy: none

	/// JDE transaction unit of measure for the line (F4211.SDUOM, EDW dbo.FactSalesDetail.UOMTransaction).
	/// Shown beside Qty Ordered / Qty Shipped so quantities are readable and never totalled across mixed UoMs.
	column UoM
		dataType: string
		lineageTag: 5a1c9d70-6b2e-4f18-9c3a-7e10d4b8f2a6
		summarizeBy: none
		sourceColumn: UoM

		annotation SummarizationSetBy = Automatic

	/// Sold-To name pulled from the related dimension row, so it can sit in a wide grid without a dimension hop in the group-by.
	column 'Sold-To Name' = RELATED('Sold-To'[Sold-To Name])
		dataType: string
		lineageTag: 53b461d0-11f5-453c-acab-922cf692a51b
		summarizeBy: none

	/// Ship-To name pulled from the related dimension row, so it can sit in a wide grid without a dimension hop in the group-by.
	column 'Ship-To Name' = RELATED('Ship-To'[Ship-To Name])
		dataType: string
		lineageTag: 69a77626-02ce-4e12-8049-8c5ca83e1962
		summarizeBy: none

	/// Customer tier (Bronze/Silver/Gold/Platinum) pulled from the related Sold-To row, so tier is available fact-side without a dimension hop.
	column 'Customer Segmentation' = RELATED('Sold-To'[Customer Segmentation])
		dataType: string
		lineageTag: 1ef898c8-5511-4d9c-899c-07317cdbbbf0
		summarizeBy: none

	/// Strategic or STD, pulled from the related Sold-To row.
	column 'SLO Segmentation' = RELATED('Sold-To'[SLO Segmentation])
		dataType: string
		lineageTag: b9389102-d8b9-4fc5-afcf-7221313e43ca
		summarizeBy: none

	/// Line number with any split suffix removed: FLOOR([Line Num]), so 1.001 and 1.002 both roll up to 1.000. Descriptive only — nothing is collapsed on it yet.
	column 'Parent Line Num'
		dataType: double
		formatString: 0.000
		lineageTag: 4a6c8e15-9b73-42d0-8f21-6e5a3c9b7d84
		summarizeBy: none
		sourceColumn: Parent Line Num

		annotation SummarizationSetBy = Automatic

	/// [Order Line ID] with the line number floored to its parent, so split children share one key. On a non-split line this is IDENTICAL to [Order Line ID]. Group by this instead of [Order Line ID] to see one row per commercial line.
	column 'Parent Order Line ID'
		dataType: string
		lineageTag: 7d2b5f91-6a48-4c37-b90e-3f8c1e4a6b25
		summarizeBy: none
		sourceColumn: Parent Order Line ID

		annotation SummarizationSetBy = Automatic

	/// 1 = this row is a split child (line number has a non-zero fraction, e.g. 1.001). Note freight also lands here: the BILLABLE FREIGHT line sits at .010. Use [Is Parent Row] to filter, not this column.
	column 'Is Split Child'
		dataType: int64
		formatString: 0
		lineageTag: 2f9a7c63-5d81-4b0e-a374-8c6b2e1f9d47
		summarizeBy: none
		sourceColumn: Is Split Child

		annotation SummarizationSetBy = Automatic

	/// Master Planning Family code (JDE F4102.IBPRP4, UDC 41/P4), folded fact-side from BIQL.TbItemBranch at (ItemSKey, Business Unit). 3-char code, trimmed at source. Use with [Master Planning Family Desc]; e.g. exclude 'PKG' to drop packaging/quilts.
	column 'Master Planning Family'
		dataType: string
		lineageTag: 8c1f4a72-3d6b-4e59-9a10-5b7e2c8d4f13
		summarizeBy: none
		sourceColumn: Master Planning Family

		annotation SummarizationSetBy = Automatic

	/// Decode of [Master Planning Family] via UDC 41/P4 (F0005.DRDL01). Blank where the UDC has no entry for the code.
	column 'Master Planning Family Desc'
		dataType: string
		lineageTag: 5e93b1d0-7c24-4f88-b6a3-1d0f9e6a72c5
		summarizeBy: none
		sourceColumn: Master Planning Family Desc

		annotation SummarizationSetBy = Automatic

	/// 1 = this row is the PARENT of its split family: the lowest [Line Num] within [Parent Order Line ID]. That is the .000 row where one exists, and the lowest child for the 117 families that have none - so no family is ever dropped. The report-level filter keeps only these rows, collapsing splits to one row per commercial line with every field already carrying the parent's own value. Freight sits at .010 and is therefore never the parent. Do NOT filter on [Is Split Child] = 0 instead: that would delete those 117 families entirely.
	column 'Is Parent Row' =
			VAR MinLine =
			    CALCULATE (
			        MIN ( 'FactSalesDetail'[Line Num] ),
			        ALLEXCEPT ( 'FactSalesDetail', 'FactSalesDetail'[Parent Order Line ID] )
			    )
			RETURN
			    IF ( 'FactSalesDetail'[Line Num] = MinLine, 1, 0 )
		formatString: 0
		lineageTag: 1d4f7a26-9c53-4e81-b072-5f8a3c6d9e14
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Qty Ordered summed across the whole split family, FREIGHT EXCLUDED ([Line Type] = "FS"). Carried identically on every row of the family, so it is only meaningful alongside [Is Parent Row] = 1 - without that filter it repeats the family total once per child and inflates. Safe to sum: excluding freight, no multi-row family disagrees on Item or UoM (verified 2026-08-04).
	column 'Qty Ordered (Family)' =
			CALCULATE (
			    SUM ( 'FactSalesDetail'[Qty Ordered] ),
			    ALLEXCEPT ( 'FactSalesDetail', 'FactSalesDetail'[Parent Order Line ID] ),
			    'FactSalesDetail'[Line Type] <> "FS"
			)
		formatString: #,##0
		lineageTag: 2e5a8b37-0d64-4f92-a183-6b9c4d7e0f25
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// Qty Shipped summed across the split family, freight excluded. See [Qty Ordered (Family)] for the caveat - only valid with [Is Parent Row] = 1.
	column 'Qty Shipped (Family)' =
			CALCULATE (
			    SUM ( 'FactSalesDetail'[Qty Shipped] ),
			    ALLEXCEPT ( 'FactSalesDetail', 'FactSalesDetail'[Parent Order Line ID] ),
			    'FactSalesDetail'[Line Type] <> "FS"
			)
		formatString: #,##0
		lineageTag: 3f6b9c48-1e75-4a03-b294-7c0d5e8f1a36
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// Qty Open summed across the split family, freight excluded. See [Qty Ordered (Family)] for the caveat - only valid with [Is Parent Row] = 1.
	column 'Qty Open (Family)' =
			CALCULATE (
			    SUM ( 'FactSalesDetail'[Qty Open] ),
			    ALLEXCEPT ( 'FactSalesDetail', 'FactSalesDetail'[Parent Order Line ID] ),
			    'FactSalesDetail'[Line Type] <> "FS"
			)
		formatString: #,##0
		lineageTag: 4a7c0d59-2f86-4b14-c3a5-8d1e6f902b47
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// Qty Backordered summed across the split family, freight excluded. See [Qty Ordered (Family)] for the caveat - only valid with [Is Parent Row] = 1.
	column 'Qty Backordered (Family)' =
			CALCULATE (
			    SUM ( 'FactSalesDetail'[Qty Backordered] ),
			    ALLEXCEPT ( 'FactSalesDetail', 'FactSalesDetail'[Parent Order Line ID] ),
			    'FactSalesDetail'[Line Type] <> "FS"
			)
		formatString: #,##0
		lineageTag: 5b8d1e6a-3097-4c25-d4b6-9e2f7a013c58
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column OnTime = IF(CALCULATE(COUNTROWS(FactScheduleChange),FactScheduleChange[Is OTIF Relevant]=true)>0,"No","Yes")
		lineageTag: a9b489d8-5f11-4635-ae71-66f4ba9352b9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// JDE next status for the line. 999 = closed; anything below is an open line.
	column 'Status Code Next'
		dataType: string
		lineageTag: da664f56-715f-444a-9d7a-39adf90de227
		summarizeBy: none
		sourceColumn: Status Code Next

		annotation SummarizationSetBy = Automatic

	/// 1 = the invoiced population (GL-posted, GL Date on or after 1/1/2024) every shipped OTIF number reads; page-level filters hold Flag = 1 on every page except OTIF Backlog (Open Orders). 0 = open order line (Status Code Next below 999), which carries the JDE 1900 GL-date placeholder until invoicing.
	column 'Flag In Population' = IF ( 'FactSalesDetail'[GL Date] >= DATE ( 2024, 1, 1 ), 1, 0 )
		formatString: 0
		lineageTag: 97f6c57c-6db8-4e04-9c7f-3842a6784479
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition FactSalesDetail = m
		mode: import
		source =
				// Orders (denominator) — EDW Fact/Dim star
				// Source: EDWPROD.michem.com / EDW / dbo.FactSalesDetail. The orders feed is
				// current (through 2026); only Salesforce is stale. "Orders" = distinct
				// [Order Num] (a measure). Column aliases match Complaints.xlsx 'Sales Orders'.
				//
				// CONNECTION: native query (Sql.Database with [Query=...]). This matches the
				// deployed PBIP partition (Executive Dashboard.SemanticModel ... Orders.tmdl) and
				// binds to the shared on-prem data gateway for scheduled refresh in the Power BI
				// Service. The SELECT is the source-of-truth column set (wider than the old
				// navigation-pattern draft — notably it keeps [Order Line ID] and the
				// item/customer/shipment columns). Note: a native query is a fixed passthrough,
				// so downstream PQ steps past Typed may not fold — keep transforms in the SQL.
				//
				// SERVER must match the gateway's registered data source string — registered
				// as the short name "EDWPROD" — and resolve where the PBIX refreshes in Desktop
				// (the jump box; the short name resolves there via DNS suffix). Gateway creds:
				// Windows auth, UPN "ZackB@michem.com" (NOT the michelman.com mail address, NOT
				// "Zack.bishop" — the AD account is ZackB and the AD domain is michem.com).
				//
				// Notes:
				//  - SSAS helper cols (Order Exclude / Filter Active Types / Exclude Freight)
				//    don't exist in the raw fact — apply the equivalent on Order Type / Line
				//    Type / Cancelled_Flag (kept raw, filtered in the measure; Greg to lock).
				//  - WINDOW: GLDate >= 2024-01-01 keeps the invoiced (GL-posted) population; OR
				//    StatusCodeNext <> '999' adds the open order lines (~800 orders / ~1.2k lines), which carry the JDE
				//    1900 GLDate placeholder until invoicing. [Flag In Population] (DAX) = 1 marks
				//    the invoiced population; page-level filters hold Flag = 1 on every page except
				//    OTIF Backlog (Open Orders), so shipped numbers read the invoiced population.
				//    The Executive Dashboard partition keeps the invoiced-only window — open lines
				//    stay out of revenue reporting.
				//  - RecordType 'GL Detail' rows (= Line Type 'AA') are dropped at source. The
				//    "IS NULL OR" guard keeps NULL RecordType rows under SQL's three-valued logic.
				//  - [Business Unit Revenue] = JDE revenue business unit (MCU): first 2 digits =
				//    company (10 = Americas, 20 = Europe); remainder = cost center / product line.
				//
				// COGNOS FILTERSETS AS SOFT FLAGS (added 2026-06-28): the IT-provided Cognos query
				//   hard-filters five conditions. Per request these are NOT hard-filtered here —
				//   each is emitted as a 1/0 [Flag ...] column so the report can reproduce the
				//   Cognos population exactly via slicer (Flag = 1 on all five) without losing rows.
				//   GLDate >= 2024-01-01 stays the only hard bound (analogous to keeping the floor).
				//   FactSalesDetail carries every source column, so these are EXACT, not proxies:
				//     [Flag Positive Volume]          (QuantityOrdered*ConversionFactorLB*SalesFactor) > 0
				//     [Flag Line Type S]              LineType = 'S'
				//     [Flag Not Sched]                UserID <> 'SCHED'   (UserID = JDE SDUSER, last-updated-by)
				//     [Flag Updated In Cognos Window] UpdatedDate in 2024-01-01..2025-02-24
				//     [Flag Not India Tax]            ItemNum2nd not in IGST/CGST/SGST/CVD/ADD
				//   ⚠ India-tax: Cognos keys off decode(GLOBAL_BULK_ITEM,'-',ITEM_NUMBER_2ND,
				//     GLOBAL_BULK_ITEM); FactSalesDetail has no GlobalBulkItem column, so we test
				//     ItemNum2nd directly. Equivalent unless a bulk item overrides the 2nd item #.
				//   Supporting raw cols [Updated Date]/[Updated By]/[Conversion Factor LB]/
				//   [Sales Factor]/[Revision Reason] are surfaced so the flags are auditable and
				//   [Revision Reason] is available alongside [Order Line ID] for FactScheduleChange.
				//
				// MASTER PLANNING FAMILY (added 2026-08-04): [Master Planning Family] + its decode are
				//   folded on as FACT columns, not via a new dimension + relationship. MPF is
				//   F4102.IBPRP4 (item BRANCH, not item master), decoded by UDC 41/P4, and is exposed
				//   only on the BIQL view — dbo.DimItemBranch does not carry the enrichment columns
				//   (CLAUDE.md §4). Its grain is (ItemSKey, Business Unit), BOTH of which this SELECT
				//   already carries, so the fold is a LEFT JOIN with no new source.
				//   Fact-side by design: a 1:1 dimension hop in a wide-grid group-by is what caused the
				//   OOM documented in CLAUDE.md §7, and the fix there was exactly this — push the
				//   attribute onto FactSalesDetail. It also means zero DAX changes and no bidirectional
				//   filter risk.
				//   ⚠ FAN-OUT GUARD: the join target is a GROUP BY derived table, so it emits at most one
				//   row per (ItemSKey, BU) and this join therefore cannot change the fact row count.
				//   TbItemBranch is not documented as unique on that pair — report 14
				//   (Inventory.commented.m) deduped it defensively with ROW_NUMBER for the same reason.
				//   A GROUP BY derived table is hash-aggregated once; it is NOT the correlated per-row
				//   lookup (OUTER APPLY / ROW_NUMBER) that hung report 14 twice, per CLAUDE.md §7.
				//   MIN() is the tie-break. Run edw_schema/probe9_mpf_itembranch.sql on the jumpbox
				//   BEFORE the first refresh: probe 3 says whether duplicate pairs exist at all, probe 4
				//   whether any DISAGREE on MPF (only then is MIN an arbitrary pick needing a real rule).
				//   Both sides are nchar(12) so ANSI padding makes '=' trailing-space-insensitive; the
				//   TRIMs are belt-and-braces and match report 14's pairing.
				//   NOT hard-filtered. The ask that motivated this is excluding MPF = 'PKG' (packaging /
				//   quilts), but per the soft-flag convention above no rows are dropped here — slice it
				//   in the report. Lock the exclusion list first, then promote it to a [Flag ...] column.
				//
				// SPLIT LINES (added 2026-08-04, descriptive columns only): JDE splits a sales order
				//   line into 1.000 / 1.001 / 1.002 (LineNum is decimal(9,3)). Ivan's concern is that
				//   these inflate the OTIF line count and late-line count when they are commercially one
				//   line. Three descriptive columns are added — [Parent Line Num],
				//   [Parent Order Line ID], [Is Split Child] — and NOTHING is collapsed or filtered.
				//   The grain is deliberately UNCHANGED: [Order Line ID] is the join key for
				//   FactScheduleChange, the key LineComments rides on, and is embedded inside RevisionKey,
				//   which is what every writeback row in D1 is keyed by (writeback/ARCHITECTURE.md).
				//   Re-graining the fact would orphan every existing revision override and line comment.
				//   The parent roll-up therefore belongs in DAX measures over [Parent Order Line ID],
				//   which can sit beside the existing line-grain measures for comparison.
				//   Agreed rule (Zack, 2026-08-04): take the PARENT row's values for everything, and only
				//   order qty aggregates across the family.
				//   ⚠ That rule is only safe if split children agree with the parent on the OTIF dates —
				//   a split often exists BECAUSE the delivery split, in which case the child carries its
				//   own later promised date and parent-only would hide the late remainder. Probe 4 of
				//   edw_schema/probe10_line_splits.sql measures exactly this. Measures are on hold until
				//   it comes back. Probe 2 also confirms how much of the fractional-line population is
				//   kit components rather than splits.
				let
				    Source = Sql.Database(
				        "EDWPROD",
				        "EDW",
				        [Query = "
				SELECT
				    OrderNum                 AS [Order Num],
				    OrderCompany             AS [Order Company],
				    OrderType                AS [Order Type],
				    OrderSuffix              AS [Order Suffix],
				    LineNum                  AS [Line Num],
				    LineType                 AS [Line Type],
				    LineTypeDesc             AS [Line Type Desc],
				    RecordType               AS [Record Type],
				    Cancelled_Flag,
				    StatusCodeLast           AS [Status Code Last],
				    StatusCodeNext           AS [Status Code Next],  -- 999 = closed; anything below is an open line
				    GLDate                   AS [GL Date],
				    ActualShipDate           AS [Actual Ship Date],
				    OrderDate                AS [Order Date],
				    QuantityOrdered          AS [Qty Ordered],
				    QuantityShipped          AS [Qty Shipped],
				    QuantityCanceledScrapped AS [Qty Cancelled],
				    UOMTransaction           AS [UoM],
				    LotSKey,
				    LotNum                   AS [Lot Num],
				    ShipToCustomerSKey,
				    PromisedDeliveryDate         AS [Promised Delivery Date],
				    RequestedDate                AS [Requested Date],
				    PromisedShipmentDate         AS [Promised Shipment Date],
				    OriginalPromisedDeliveryDate AS [Original Promised Delivery Date],
				    ScheduledPickDate            AS [Scheduled Pick Date],
				    Description1             AS [Product Description],
				    Description2             AS [Product Description 2],
				    ItemNumShort             AS [Item Num],
				    ItemNum2nd               AS [Item Num 2nd],
				    Location                 AS [Location],
				    BusinessUnit             AS [Business Unit],
				    BusinessUnitRevenue      AS [Business Unit Revenue],
				    OrderTakenBy             AS [Order Taken By],
				    OrderedBy                AS [Ordered By],
				    ShipmentNum              AS [Shipment Num],
				    BillOfLading             AS [Bill Of Lading],
				    OrderLineID              AS [Order Line ID],
				    OrderHeaderID            AS [Order Header ID],
				    -- Split-line roll-up helpers. LineNum is decimal(9,3); 1.001/1.002 are JDE split
				    -- children of parent line 1.000. [Parent Order Line ID] is derived by string surgery
				    -- on the REAL OrderLineID rather than reconstructed from its parts, so the prefix
				    -- matches byte-for-byte whatever format EDW uses — and on a non-split line it comes
				    -- out identical to [Order Line ID], which is the built-in self-check.
				    -- An [Is Kit Line] flag was tried here (KitMasterLineNum/KitIdentifier <> 0) and
				    -- REMOVED 2026-08-04: it returned 1 on 91% of rows, so those EDW columns are not
				    -- zero-defaulted and the test was meaningless. It is also unnecessary — the real
				    -- confound inside a parent family turned out to be the FREIGHT line, not kits
				    -- (measured live: every family carries its product splits at .001-.00n and a
				    -- LineType 'FS' BILLABLE FREIGHT line at .010). Freight is already identifiable
				    -- via [Line Type] = 'FS'; exclude it from any parent roll-up. Verified in the
				    -- refreshed model: with FS rows excluded, ZERO of the 8,119 multi-row families
				    -- disagree on Item, UoM or Master Planning Family.
				    CAST(FLOOR(LineNum) AS decimal(9,3)) AS [Parent Line Num],
				    LEFT(LTRIM(RTRIM(OrderLineID)),
				         LEN(LTRIM(RTRIM(OrderLineID))) - CHARINDEX(',', REVERSE(LTRIM(RTRIM(OrderLineID)))))
				      + ',' + CAST(CAST(FLOOR(LineNum) AS decimal(9,3)) AS varchar(12)) AS [Parent Order Line ID],
				    CASE WHEN LineNum <> FLOOR(LineNum) THEN 1 ELSE 0 END AS [Is Split Child],
				    SerialNumLot             AS [Serial Num Lot],
				    AmountExtendedPrice      AS [Ext Price],
				    AmountOpen               AS [Amount Open],
				    QuantityBackordered      AS [Qty Backordered],
				    QuantityOpen             AS [Qty Open],
				    QuantityShippedtoDate    AS [Qty Shipped To Date],
				    GrossWeight              AS [Gross Weight],
				    UnitWeight               AS [Unit Weight],
				    HoldOrdersCode           AS [Hold Code],
				    ReasonCode               AS [Reason Code],
				    ReasonCodeDesc           AS [Reason Code Desc],
				    ModeOfTransport          AS [Mode Of Transport],
				    CarrierNum               AS [Carrier Num],
				    FreightHandlingCode      AS [Freight Handling Code],
				    CancelDate               AS [Cancel Date],
				    InvoiceDate              AS [Invoice Date],
				    ShipToAddressSKey,
				    SoldToAddressSKey,
				    SoldToCustomerSKey,
				    ParentCustomerSKey,
				    f.ItemSKey,
				    -- Master Planning Family (F4102.IBPRP4, UDC 41/P4) folded from BIQL.TbItemBranch
				    -- at (ItemSKey, Business Unit). Dedup guaranteed by the GROUP BY in the join below.
				    ib.MasterPlanningFamily     AS [Master Planning Family],
				    ib.MasterPlanningFamilyDesc AS [Master Planning Family Desc],
				    -- Supporting raw columns for the Cognos flags below (and FactScheduleChange link)
				    UpdatedDate              AS [Updated Date],
				    UserID                   AS [Updated By],
				    ConversionFactorLB       AS [Conversion Factor LB],
				    SalesFactor              AS [Sales Factor],
				    RevisionReason           AS [Revision Reason],
				    -- Cognos filterset flags (soft): 1 = row matches the Cognos WHERE condition.
				    -- Slice Flag = 1 on all five to reproduce the Cognos population; none drop rows.
				    CASE WHEN (QuantityOrdered * ConversionFactorLB * SalesFactor) > 0 THEN 1 ELSE 0 END AS [Flag Positive Volume],
				    CASE WHEN LineType = 'S' THEN 1 ELSE 0 END AS [Flag Line Type S],
				    CASE WHEN LTRIM(RTRIM(UserID)) <> 'SCHED' THEN 1 ELSE 0 END AS [Flag Not Sched],
				    CASE WHEN UpdatedDate BETWEEN '2024-01-01' AND '2025-02-24' THEN 1 ELSE 0 END AS [Flag Updated In Cognos Window],
				    CASE WHEN LTRIM(RTRIM(ItemNum2nd)) NOT IN ('IGST','CGST','SGST','CVD','ADD') THEN 1 ELSE 0 END AS [Flag Not India Tax]
				FROM dbo.FactSalesDetail f
				LEFT JOIN (
				    SELECT ItemSKey,
				           LTRIM(RTRIM([Business Unit]))                    AS BU,
				           MIN(LTRIM(RTRIM([Master Planning Family])))      AS MasterPlanningFamily,
				           MIN(LTRIM(RTRIM([Master Planning Family Desc]))) AS MasterPlanningFamilyDesc
				    FROM BIQL.TbItemBranch
				    GROUP BY ItemSKey, LTRIM(RTRIM([Business Unit]))
				) ib ON ib.ItemSKey = f.ItemSKey
				    AND ib.BU       = LTRIM(RTRIM(f.BusinessUnit))
				WHERE (GLDate >= '2024-01-01' OR StatusCodeNext <> '999')
				  AND (RecordType IS NULL OR RecordType <> 'GL Detail')
				"]
				    ),
				    Typed = Table.TransformColumnTypes(
				        Source,
				        {
				            {"GL Date", type date},
				            {"Actual Ship Date", type date},
				            {"Order Date", type date},
				            {"Promised Delivery Date", type date},
				            {"Requested Date", type date},
				            {"Promised Shipment Date", type date},
				            {"Original Promised Delivery Date", type date},
				            {"Scheduled Pick Date", type date},
				            {"Cancel Date", type date},
				            {"Invoice Date", type date},
				            {"Updated Date", type date}
				        },
				        "en-US"
				    )
				in
				    Typed

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

