table 'CSR-Less Dropped Lines'
	lineageTag: 15000000-0000-0004-0000-000000000000

	column 'Lines Missing Header'
		dataType: int64
		formatString: 0
		lineageTag: 15000000-0000-0004-0001-000000000001
		summarizeBy: none
		sourceColumn: Lines Missing Header

		annotation SummarizationSetBy = Automatic

	column 'Lines Dropped No CSR'
		dataType: int64
		formatString: 0
		lineageTag: 15000000-0000-0004-0001-000000000002
		summarizeBy: none
		sourceColumn: Lines Dropped No CSR

		annotation SummarizationSetBy = Automatic

	column 'Open Lines Pre CSR'
		dataType: int64
		formatString: 0
		lineageTag: 15000000-0000-0004-0001-000000000003
		summarizeBy: none
		sourceColumn: Open Lines Pre CSR

		annotation SummarizationSetBy = Automatic

	partition 'CSR-Less Dropped Lines' = m
		mode: import
		source =
				let
				    Source = Sql.Database("ODSPROD", "ODS"),
				    Data = Value.NativeQuery(
				        Source,
				        "
				        SELECT
				            SUM(CASE WHEN hdr.SHDOCO IS NULL THEN 1 ELSE 0 END) AS [Lines Missing Header],
				            SUM(CASE WHEN csr.CMAN8 IS NULL THEN 1 ELSE 0 END)  AS [Lines Dropped No CSR],
				            COUNT(*)                                            AS [Open Lines Pre CSR]
				        FROM PRODDTA.F4211 o
				        LEFT JOIN PRODDTA.F4201 hdr ON o.SDKCOO=hdr.SHKCOO AND o.SDDOCO=hdr.SHDOCO AND o.SDDCTO=hdr.SHDCTO AND o.SDSFXO=hdr.SHSFXO
				        LEFT JOIN (SELECT DISTINCT CMAN8 FROM PRODDTA.F42140 WHERE CMRTYPE='CSR') csr ON o.SDSHAN = csr.CMAN8
				        WHERE o.SDNXTR < '570' AND o.SDKCOO='00010' AND o.SDLNTY NOT IN ('FS','T') AND o.SDDCTO <> 'SQ'
				        ",
				        null,
				        [EnableFolding = true]
				    ),
				    Typed = Table.TransformColumnTypes(
				        Data,
				        {
				            {"Lines Missing Header", Int64.Type},
				            {"Lines Dropped No CSR", Int64.Type},
				            {"Open Lines Pre CSR", Int64.Type}
				        },
				        "en-US"
				    )
				in
				    Typed

	annotation PBI_ResultType = Table

