table Inv_Summary
	lineageTag: 2a69796c-eaee-452c-a04b-d2f0e6f8c49c

	column 'Branch Plant'
		dataType: string
		lineageTag: c7f5a310-ea06-484f-8422-070f03010932
		summarizeBy: none
		sourceColumn: Branch Plant

		annotation SummarizationSetBy = Automatic

	column 'Global Bulk Item'
		dataType: string
		lineageTag: 22d8419f-6bd2-43a7-b794-e79b71f2075c
		summarizeBy: none
		sourceColumn: Global Bulk Item

		annotation SummarizationSetBy = Automatic

	column 'Bulk Item'
		dataType: string
		lineageTag: 9e7f89b6-6a75-4000-8cec-215259e42a1f
		summarizeBy: none
		sourceColumn: Bulk Item

		annotation SummarizationSetBy = Automatic

	column '2nd Item Number'
		dataType: string
		lineageTag: 6fe36081-b1e2-45fd-9dfe-4b6f856dc2cd
		summarizeBy: none
		sourceColumn: 2nd Item Number

		annotation SummarizationSetBy = Automatic

	column 'Commodity Class'
		dataType: string
		lineageTag: 951e2ca4-592e-4aeb-966d-a523fb2e0d34
		summarizeBy: none
		sourceColumn: Commodity Class

		annotation SummarizationSetBy = Automatic

	column 'Sub Class'
		dataType: string
		lineageTag: b6ff1a4d-f3fc-449f-b7d2-a37f5584505f
		summarizeBy: none
		sourceColumn: Sub Class

		annotation SummarizationSetBy = Automatic

	column 'Master Planning Family'
		dataType: string
		lineageTag: b9df561e-0cb0-425d-9d12-1362021b751f
		summarizeBy: none
		sourceColumn: Master Planning Family

		annotation SummarizationSetBy = Automatic

	column 'Safety Stock'
		dataType: double
		lineageTag: e7826a8b-935f-4561-8de8-ff247a6dfbc2
		summarizeBy: none
		sourceColumn: Safety Stock

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Shelf Life'
		dataType: double
		lineageTag: 779fb914-720e-4d45-a4e3-440dbd51e474
		summarizeBy: none
		sourceColumn: Shelf Life

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Stock Type'
		dataType: string
		lineageTag: 41a77aac-25f0-480c-bb70-622f742cc7f0
		summarizeBy: none
		sourceColumn: Stock Type

		annotation SummarizationSetBy = Automatic

	column 'GL Category'
		dataType: string
		lineageTag: a4f684db-0d79-4f41-b164-aba290f7f2d7
		summarizeBy: none
		sourceColumn: GL Category

		annotation SummarizationSetBy = Automatic

	column 'Leadtime Level'
		dataType: double
		lineageTag: cffe7588-fa3e-44ff-b1c7-7005fbfcf10e
		summarizeBy: none
		sourceColumn: Leadtime Level

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Leadtime MFG'
		dataType: double
		lineageTag: 8dce574e-2237-480c-a9eb-43605dc861d6
		summarizeBy: none
		sourceColumn: Leadtime MFG

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isDecimal":true}

	column Location
		dataType: string
		lineageTag: 5334c3ad-f4c6-4694-ac01-5afe85d1cb24
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column 'Lot Number'
		dataType: string
		lineageTag: 15471890-ed27-4803-ba7d-212f514139d5
		summarizeBy: none
		sourceColumn: Lot Number

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: ca2c47e7-03c0-48d4-a55a-b935eb2fbc8e
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Quantity On Hand'
		dataType: double
		formatString: #,0
		lineageTag: 3aba6f77-42ab-478d-856b-d9ee2251f75a
		summarizeBy: sum
		sourceColumn: Quantity On Hand

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Primary UOM'
		dataType: string
		lineageTag: e22165ee-78cc-47cc-8856-e0b19e7ed625
		summarizeBy: none
		sourceColumn: Primary UOM

		annotation SummarizationSetBy = Automatic

	column 'Hard Commit'
		dataType: double
		formatString: #,0
		lineageTag: 86215d79-db67-42e1-bcab-791149cac8bf
		summarizeBy: sum
		sourceColumn: Hard Commit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'A1 Cost'
		dataType: double
		formatString: $#,0
		lineageTag: 101c3aa1-5104-4359-b311-a573fcf6f1fb
		summarizeBy: sum
		sourceColumn: A1 Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'B1 Cost'
		dataType: double
		formatString: $#,0
		lineageTag: e9189985-6506-483a-bddf-f5334378cfe0
		summarizeBy: sum
		sourceColumn: B1 Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'C1 Cost'
		dataType: double
		formatString: $#,0
		lineageTag: 7664daa6-9274-4b1a-8711-fd5f2a378c62
		summarizeBy: sum
		sourceColumn: C1 Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'C2 Cost'
		dataType: double
		formatString: $#,0
		lineageTag: 7c57a18d-7990-4cd5-91ed-1dc3da5c3bdd
		summarizeBy: sum
		sourceColumn: C2 Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Lot Number1'
		dataType: string
		lineageTag: 28fd0c4b-db85-4a1b-9652-ab2dd3415255
		summarizeBy: none
		sourceColumn: Lot Number1

		annotation SummarizationSetBy = Automatic

	column 'Supplier Lot Number'
		dataType: string
		lineageTag: dd32a471-9292-4b28-a046-295d794d888a
		summarizeBy: none
		sourceColumn: Supplier Lot Number

		annotation SummarizationSetBy = Automatic

	column 'On Hand Date'
		dataType: dateTime
		formatString: d MMM, yyyy
		lineageTag: 5a3471a5-8121-4e8b-b0c7-bf6be77f8e2c
		summarizeBy: none
		sourceColumn: On Hand Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Expiration Date Month'
		dataType: dateTime
		formatString: d MMM, yyyy
		lineageTag: 89e409d5-3b95-4194-8e37-f7f748f25736
		summarizeBy: none
		sourceColumn: Expiration Date Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TIME
		dataType: dateTime
		formatString: General Date
		lineageTag: b6408762-3765-412a-9c38-a15f20ad600a
		summarizeBy: none
		sourceColumn: TIME

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Inv_Summary = m
		mode: import
		source =
				let
				    Source = Sql.Database("ODSPROD", "ODS"),
				    Data = Value.NativeQuery(
				        Source,
				        "
				        SELECT
				            Inventory6.Branch_Plant             AS [Branch Plant],
				            Inventory6.Global_Bulk_Item         AS [Global Bulk Item],
				            Inventory6.Bulk_Item                AS [Bulk Item],
				            Inventory6.C_2nd_Item_Number        AS [2nd Item Number],
				            Inventory6.Commodity_Class          AS [Commodity Class],
				            Inventory6.Sub_Class                AS [Sub Class],
				            Inventory6.Master_Planning_Family   AS [Master Planning Family],
				            Inventory6.Safety_Stock             AS [Safety Stock],
				            Inventory6.Shelf_Life               AS [Shelf Life],
				            Inventory6.Stock_Type               AS [Stock Type],
				            Inventory6.GL_Category              AS [GL Category],
				            Inventory6.Leadtime_Level           AS [Leadtime Level],
				            Inventory6.Leadtime_MFG             AS [Leadtime MFG],
				            Inventory6.Location                 AS [Location],
				            Inventory6.Lot_Number               AS [Lot Number],
				            Inventory6.Status                   AS [Status],
				            SUM(Inventory6.Quantity_On_Hand)    AS [Quantity On Hand],
				            Inventory6.Primary_UOM              AS [Primary UOM],
				            SUM(Inventory6.Hard_Commit)         AS [Hard Commit],
				            SUM(Inventory6.A1_Cost)             AS [A1 Cost],
				            SUM(Inventory6.B1_Cost)             AS [B1 Cost],
				            SUM(Inventory6.C1_Cost)             AS [C1 Cost],
				            SUM(Inventory6.C2_Cost)             AS [C2 Cost],
				            Quality7.Lot_Number                 AS [Lot Number1],
				            Quality7.Supplier_Lot_Number        AS [Supplier Lot Number],
				            Quality7.On_Hand_Date               AS [On Hand Date],
				            Quality7.Expiration_Date_Month      AS [Expiration Date Month],
				            Inventory6.TIME24                   AS [TIME]
				        FROM
				        (
				            SELECT
				                T0.C0  AS Branch_Plant,
				                T0.C1  AS Global_Bulk_Item,
				                T0.C2  AS Bulk_Item,
				                T0.C3  AS C_2nd_Item_Number,
				                T0.C4  AS Commodity_Class,
				                T0.C5  AS Sub_Class,
				                T0.C6  AS Master_Planning_Family,
				                T0.C7  AS Safety_Stock,
				                T0.C8  AS Shelf_Life,
				                T0.C9  AS Stock_Type,
				                T0.C10 AS GL_Category,
				                T0.C11 AS Leadtime_Level,
				                T0.C12 AS Leadtime_MFG,
				                T0.C13 AS Location,
				                T0.C14 AS Lot_Number,
				                T0.C15 AS Status,
				                SUM(T0.C16) OVER (PARTITION BY T0.C0,T0.C1,T0.C2,T0.C3,T0.C4,T0.C5,T0.C6,T0.C7,T0.C8,T0.C9,T0.C10,T0.C11,T0.C12,T0.C13,T0.C14,T0.C15,T0.C17) AS Quantity_On_Hand,
				                T0.C17 AS Primary_UOM,
				                SUM(T0.C18) OVER (PARTITION BY T0.C0,T0.C1,T0.C2,T0.C3,T0.C4,T0.C5,T0.C6,T0.C7,T0.C8,T0.C9,T0.C10,T0.C11,T0.C12,T0.C13,T0.C14,T0.C15,T0.C17) AS Hard_Commit,
				                SUM(T0.C19) OVER (PARTITION BY T0.C0,T0.C1,T0.C2,T0.C3,T0.C4,T0.C5,T0.C6,T0.C7,T0.C8,T0.C9,T0.C10,T0.C11,T0.C12,T0.C13,T0.C14,T0.C15,T0.C17) AS A1_Cost,
				                SUM(T0.C20) OVER (PARTITION BY T0.C0,T0.C1,T0.C2,T0.C3,T0.C4,T0.C5,T0.C6,T0.C7,T0.C8,T0.C9,T0.C10,T0.C11,T0.C12,T0.C13,T0.C14,T0.C15,T0.C17) AS B1_Cost,
				                SUM(T0.C21) OVER (PARTITION BY T0.C0,T0.C1,T0.C2,T0.C3,T0.C4,T0.C5,T0.C6,T0.C7,T0.C8,T0.C9,T0.C10,T0.C11,T0.C12,T0.C13,T0.C14,T0.C15,T0.C17) AS C1_Cost,
				                SUM(T0.C22) OVER (PARTITION BY T0.C0,T0.C1,T0.C2,T0.C3,T0.C4,T0.C5,T0.C6,T0.C7,T0.C8,T0.C9,T0.C10,T0.C11,T0.C12,T0.C13,T0.C14,T0.C15,T0.C17) AS C2_Cost,
				                T0.C23 AS TIME24
				            FROM
				            (
				                SELECT
				                    LTRIM(RTRIM(LTRIM(RTRIM(ib.IBMCU))))    AS C0,
				                    LTRIM(RTRIM(tag.IMGBLK))                AS C1,
				                    LTRIM(RTRIM(tag.IMBULK))                AS C2,
				                    LTRIM(RTRIM(LTRIM(RTRIM(ib.IBLITM))))   AS C3,
				                    ib.IBPRP1                               AS C4,
				                    ib.IBPRP2                               AS C5,
				                    ib.IBPRP4                               AS C6,
				                    ib.IBSAFE/10000.0                       AS C7,
				                    ib.IBSLD                                AS C8,
				                    ib.IBSTKT                               AS C9,
				                    ib.IBGLPT                               AS C10,
				                    ib.IBLTLV                               AS C11,
				                    ib.IBLTMF                               AS C12,
				                    LTRIM(RTRIM(loc.LILOCN))                AS C13,
				                    LTRIM(RTRIM(loc.LILOTN))                AS C14,
				                    loc.LILOTS                              AS C15,
				                    SUM(loc.LIPQOH/10000.0)                 AS C16,
				                    im.IMUOM1                               AS C17,
				                    SUM(loc.LIHCOM/10000.0)                 AS C18,
				                    SUM((loc.LIPQOH/10000.0)*cost.A1_Unit_Cost) AS C19,
				                    SUM((loc.LIPQOH/10000.0)*cost.B1_Unit_Cost) AS C20,
				                    SUM((loc.LIPQOH/10000.0)*cost.C1_Unit_Cost) AS C21,
				                    SUM((loc.LIPQOH/10000.0)*cost.C2_Unit_Cost) AS C22,
				                    CAST(GETDATE() AS date)                 AS C23
				                FROM PRODDTA.F4102 ib,
				                     PRODDTA.F554101 tag,
				                     PRODDTA.F41021 loc,
				                     PRODDTA.F4101 im,
				                     (
				                        SELECT
				                            f.IBITM, f.IBMCU, e.IELEDG,
				                            SUM(CASE WHEN e.IECOST='A1 ' THEN e.IECSL/10000.0 ELSE 0 END) AS A1_Unit_Cost,
				                            SUM(CASE WHEN e.IECOST='B1 ' THEN e.IECSL/10000.0 ELSE 0 END) AS B1_Unit_Cost,
				                            SUM(CASE WHEN e.IECOST='C1 ' THEN e.IECSL/10000.0 ELSE 0 END) AS C1_Unit_Cost,
				                            SUM(CASE WHEN e.IECOST='C2 ' THEN e.IECSL/10000.0 ELSE 0 END) AS C2_Unit_Cost
				                        FROM PRODDTA.F4102 f,
				                             PRODDTA.F4105 c
				                             LEFT OUTER JOIN PRODDTA.F30026 e
				                                 ON c.COITM=e.IEITM AND c.COMCU=e.IEMMCU AND c.COLEDG=e.IELEDG
				                        WHERE f.IBITM=c.COITM AND f.IBMCU=c.COMCU AND c.COCSIN='I'
				                        GROUP BY f.IBITM, f.IBMCU, e.IELEDG
				                     ) cost
				                WHERE loc.LIPQOH/10000.0 > 0
				                  AND ib.IBITM = im.IMITM
				                  AND im.IMITM = tag.IMITM
				                  AND ib.IBITM = loc.LIITM
				                  AND ib.IBMCU = loc.LIMCU
				                  AND ib.IBITM = cost.IBITM
				                  AND ib.IBMCU = cost.IBMCU
				                GROUP BY
				                    LTRIM(RTRIM(LTRIM(RTRIM(ib.IBMCU)))),
				                    LTRIM(RTRIM(tag.IMGBLK)),
				                    LTRIM(RTRIM(tag.IMBULK)),
				                    LTRIM(RTRIM(LTRIM(RTRIM(ib.IBLITM)))),
				                    ib.IBPRP1, ib.IBPRP2, ib.IBPRP4, ib.IBSAFE/10000.0, ib.IBSLD, ib.IBSTKT,
				                    ib.IBGLPT, ib.IBLTLV, ib.IBLTMF,
				                    LTRIM(RTRIM(loc.LILOCN)), LTRIM(RTRIM(loc.LILOTN)), loc.LILOTS, im.IMUOM1
				            ) T0
				        ) Inventory6
				        INNER JOIN
				        (
				            SELECT DISTINCT
				                LTRIM(RTRIM(lm.IOLOTN)) AS Lot_Number,
				                NULLIF(LTRIM(RTRIM(lm.IORLOT)), 'NULL') AS Supplier_Lot_Number,
				                lm.Expiration_Date_Month AS Expiration_Date_Month,
				                lm.On_Hand_Date          AS On_Hand_Date
				            FROM
				            (
				                SELECT
				                    IOLOTN, IORLOT,
				                    CASE WHEN IOMMEJ>0 THEN DATEADD(DAY,(IOMMEJ%1000)-1,DATEFROMPARTS(1900+(IOMMEJ/1000),1,1)) ELSE NULL END AS Expiration_Date_Month,
				                    CASE WHEN IOOHDJ>0 THEN DATEADD(DAY,(IOOHDJ%1000)-1,DATEFROMPARTS(1900+(IOOHDJ/1000),1,1)) ELSE NULL END AS On_Hand_Date
				                FROM PRODDTA.F4108
				            ) lm
				            WHERE lm.Expiration_Date_Month IS NOT NULL
				        ) Quality7
				            ON Inventory6.Lot_Number = Quality7.Lot_Number
				        GROUP BY
				            Inventory6.Branch_Plant, Inventory6.Global_Bulk_Item, Inventory6.Bulk_Item,
				            Inventory6.C_2nd_Item_Number, Inventory6.Commodity_Class, Inventory6.Sub_Class,
				            Inventory6.Master_Planning_Family, Inventory6.Safety_Stock, Inventory6.Shelf_Life,
				            Inventory6.Stock_Type, Inventory6.GL_Category, Inventory6.Leadtime_Level,
				            Inventory6.Leadtime_MFG, Inventory6.Location, Inventory6.Lot_Number, Inventory6.Status,
				            Inventory6.Primary_UOM, Quality7.Lot_Number, Quality7.Supplier_Lot_Number,
				            Quality7.On_Hand_Date, Quality7.Expiration_Date_Month, Inventory6.TIME24
				        ",
				        null,
				        [EnableFolding = true]
				    ),
				    Typed = Table.TransformColumnTypes(
				        Data,
				        {
				            {"Branch Plant", type text}, {"Global Bulk Item", type text}, {"Bulk Item", type text},
				            {"2nd Item Number", type text}, {"Commodity Class", type text}, {"Sub Class", type text},
				            {"Master Planning Family", type text}, {"Safety Stock", type number}, {"Shelf Life", type number},
				            {"Stock Type", type text}, {"GL Category", type text}, {"Leadtime Level", type number},
				            {"Leadtime MFG", type number}, {"Location", type text}, {"Lot Number", type text},
				            {"Status", type text}, {"Quantity On Hand", type number}, {"Primary UOM", type text},
				            {"Hard Commit", type number}, {"A1 Cost", type number}, {"B1 Cost", type number},
				            {"C1 Cost", type number}, {"C2 Cost", type number}, {"Lot Number1", type text},
				            {"Supplier Lot Number", type text}, {"On Hand Date", type date},
				            {"Expiration Date Month", type date}, {"TIME", type date}
				        },
				        "en-US"
				    )
				in
				    Typed

	annotation PBI_ResultType = Table

