table Sales_Summary
	lineageTag: e99c7b9e-6b24-4ac8-b940-7ef7fefa89c5

	column 'Order Company'
		dataType: string
		lineageTag: 2323e573-2e98-44eb-993e-d36e3809ebb0
		summarizeBy: none
		sourceColumn: Order Company

		annotation SummarizationSetBy = Automatic

	column 'Branch Plant'
		dataType: string
		lineageTag: 6b99d807-bf6e-49c9-bffc-b3cb0bb14d88
		summarizeBy: none
		sourceColumn: Branch Plant

		annotation SummarizationSetBy = Automatic

	column 'Global Bulk Item'
		dataType: string
		lineageTag: 29c42d79-08ca-45b7-a10d-3ad67a964bd0
		summarizeBy: none
		sourceColumn: Global Bulk Item

		annotation SummarizationSetBy = Automatic

	column 'Bulk Item'
		dataType: string
		lineageTag: ef094845-b08c-409e-aa98-03f243228824
		summarizeBy: none
		sourceColumn: Bulk Item

		annotation SummarizationSetBy = Automatic

	column '2nd Item Number'
		dataType: string
		lineageTag: d138f5a8-9487-4650-a6b8-bedcb16a0275
		summarizeBy: none
		sourceColumn: 2nd Item Number

		annotation SummarizationSetBy = Automatic

	column 'Order Number'
		dataType: int64
		formatString: 0
		lineageTag: 2f6e799f-3db2-4256-bc04-b245ed08e58c
		summarizeBy: none
		sourceColumn: Order Number

		annotation SummarizationSetBy = User

	column 'Order Line'
		dataType: double
		lineageTag: dab8b65f-b140-4008-9e2f-a31d1c3c15a6
		summarizeBy: none
		sourceColumn: Order Line

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Customer PO'
		dataType: string
		lineageTag: e0fc3d4b-c7e5-4a65-83ab-dbe519086d62
		summarizeBy: none
		sourceColumn: Customer PO

		annotation SummarizationSetBy = Automatic

	column 'Lot Number'
		dataType: string
		lineageTag: 8a97674e-69da-4fb3-896c-656184274084
		summarizeBy: none
		sourceColumn: Lot Number

		annotation SummarizationSetBy = Automatic

	column 'Hold Orders Code'
		dataType: string
		lineageTag: 8a9c2d2d-7714-41fb-872b-cb872ce44864
		summarizeBy: none
		sourceColumn: Hold Orders Code

		annotation SummarizationSetBy = Automatic

	column 'Last Status'
		dataType: string
		lineageTag: 67dc6997-d23c-4c7a-8cb2-77362e72ef7d
		summarizeBy: none
		sourceColumn: Last Status

		annotation SummarizationSetBy = Automatic

	column 'Next Status'
		dataType: string
		lineageTag: 38572c40-6366-4358-9e5d-308b5ca40cfa
		summarizeBy: none
		sourceColumn: Next Status

		annotation SummarizationSetBy = Automatic

	column 'Primary Quantity Ordered'
		dataType: double
		formatString: #,0
		lineageTag: 034d2446-e316-48b5-9259-1ca0d1e24633
		summarizeBy: sum
		sourceColumn: Primary Quantity Ordered

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Primary UOM'
		dataType: string
		lineageTag: 268a987a-1f20-4098-9e8a-4b5a63c767ff
		summarizeBy: none
		sourceColumn: Primary UOM

		annotation SummarizationSetBy = Automatic

	column 'Secondary Quantity Ordered'
		dataType: double
		formatString: #,0
		lineageTag: a8a3d9eb-39c7-4a34-9b95-bac23a33ce5c
		summarizeBy: sum
		sourceColumn: Secondary Quantity Ordered

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Secondary UOM'
		dataType: string
		lineageTag: ddb0b762-fd96-4e6b-8e1c-4f18a266c2e0
		summarizeBy: none
		sourceColumn: Secondary UOM

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: d MMM, yyyy
		lineageTag: 63b90d7b-a58e-456f-a41e-8f506856ef9d
		summarizeBy: none
		sourceColumn: Order Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Promised Ship Date'
		dataType: dateTime
		formatString: d MMM, yyyy
		lineageTag: d6dffc34-6953-4942-b772-751947cc31c0
		summarizeBy: none
		sourceColumn: Promised Ship Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Scheduled Pick Date'
		dataType: dateTime
		formatString: d MMM, yyyy
		lineageTag: 3692ad6f-f157-496f-8e90-4b708766e633
		summarizeBy: none
		sourceColumn: Scheduled Pick Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Customer Code'
		dataType: int64
		formatString: 0
		lineageTag: f6952294-a1ec-44f2-8f4c-5bae84afbfed
		summarizeBy: none
		sourceColumn: Customer Code

		annotation SummarizationSetBy = User

	column 'Customer Name'
		dataType: string
		lineageTag: 03a42217-5c66-4a8f-af48-497bca4b3ef0
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column 'Order Type'
		dataType: string
		lineageTag: 0b8e23b2-41de-4b3a-9ebb-7a1584ef6e29
		summarizeBy: none
		sourceColumn: Order Type

		annotation SummarizationSetBy = Automatic

	partition Sales_Summary = m
		mode: import
		source =
				let
				    Source = Sql.Database("ODSPROD", "ODS"),
				    Data = Value.NativeQuery(
				        Source,
				        "
				        SELECT
				            Sales5.Order_Company                 AS [Order Company],
				            Sales5.Branch_Plant                  AS [Branch Plant],
				            Item6.Global_Bulk_Item               AS [Global Bulk Item],
				            Item6.Bulk_Item                      AS [Bulk Item],
				            Sales5.C_2nd_Item_Number             AS [2nd Item Number],
				            Sales5.Order_Number                  AS [Order Number],
				            Sales5.Order_Line                    AS [Order Line],
				            Sales5.Customer_PO                   AS [Customer PO],
				            Sales5.Lot_Number                    AS [Lot Number],
				            Sales5.Hold_Orders_Code              AS [Hold Orders Code],
				            Sales5.Last_Status                   AS [Last Status],
				            Sales5.Next_Status                   AS [Next Status],
				            SUM(Sales5.Primary_Quantity_Ordered) AS [Primary Quantity Ordered],
				            Sales5.Primary_UOM                   AS [Primary UOM],
				            SUM(Sales5.Secondary_Quantity_Ordered) AS [Secondary Quantity Ordered],
				            Sales5.Secondary_UOM                 AS [Secondary UOM],
				            Sales5.Order_Date                    AS [Order Date],
				            Sales5.Promised_Ship_Date            AS [Promised Ship Date],
				            Sales5.Scheduled_Pick_Date           AS [Scheduled Pick Date],
				            Sales5.Customer_Code                 AS [Customer Code],
				            Sales5.Customer_Name                 AS [Customer Name],
				            Sales5.Order_Type                    AS [Order Type]
				        FROM
				        (
				            SELECT DISTINCT
				                LTRIM(RTRIM(LTRIM(RTRIM(ib.IBMCU))))    AS Branch_Plant,
				                LTRIM(RTRIM(LTRIM(RTRIM(tag.IMGBLK))))  AS Global_Bulk_Item,
				                LTRIM(RTRIM(LTRIM(RTRIM(tag.IMBULK))))  AS Bulk_Item,
				                LTRIM(RTRIM(LTRIM(RTRIM(ib.IBLITM))))   AS C_2nd_Item_Number
				            FROM PRODDTA.F4102 ib, PRODDTA.F554101 tag, PRODDTA.F4101 im
				            WHERE ib.IBITM = im.IMITM AND im.IMITM = tag.IMITM
				        ) Item6
				        INNER JOIN
				        (
				            SELECT
				                so.SDKCOO                        AS Order_Company,
				                LTRIM(RTRIM(so.SDMCU))           AS Branch_Plant,
				                so.SDDOCO                        AS Order_Number,
				                so.SDLNID/1000.0                 AS Order_Line,
				                LTRIM(RTRIM(so.SDVR01))          AS Customer_PO,
				                LTRIM(RTRIM(so.SDLITM))          AS C_2nd_Item_Number,
				                LTRIM(RTRIM(so.SDLOTN))          AS Lot_Number,
				                oh.SHHOLD                        AS Hold_Orders_Code,
				                so.SDLTTR                        AS Last_Status,
				                so.SDNXTR                        AS Next_Status,
				                SUM(so.SDPQOR/10000.0)           AS Primary_Quantity_Ordered,
				                so.SDUOM1                        AS Primary_UOM,
				                CASE WHEN so.SDTRDJ>0 THEN DATEADD(DAY,(so.SDTRDJ%1000)-1,DATEFROMPARTS(1900+(so.SDTRDJ/1000),1,1)) ELSE NULL END AS Order_Date,
				                CASE WHEN so.SDPDDJ>0 THEN DATEADD(DAY,(so.SDPDDJ%1000)-1,DATEFROMPARTS(1900+(so.SDPDDJ/1000),1,1)) ELSE NULL END AS Promised_Ship_Date,
				                CASE WHEN so.SDPDDJ>0 THEN DATEADD(DAY,(so.SDPDDJ%1000)-1,DATEFROMPARTS(1900+(so.SDPDDJ/1000),1,1)) ELSE NULL END AS Scheduled_Pick_Date,
				                SUM(so.SDSQOR/10000.0)           AS Secondary_Quantity_Ordered,
				                so.SDUOM2                        AS Secondary_UOM,
				                cust.ABAN8                       AS Customer_Code,
				                LTRIM(RTRIM(cust.ABALPH))        AS Customer_Name,
				                so.SDDCTO                        AS Order_Type
				            FROM PRODDTA.F4211 so,
				                 PRODDTA.F4201 oh,
				                 PRODDTA.F0101 cust
				            WHERE so.SDPQOR/10000.0 > 0
				              AND so.SDNXTR NOT IN ('620','999')
				              AND so.SDDCTO NOT IN ('ST')
				              AND so.SDSHAN = cust.ABAN8
				              AND so.SDKCOO = oh.SHKCOO
				              AND so.SDDOCO = oh.SHDOCO
				              AND so.SDDCTO = oh.SHDCTO
				              AND so.SDSFXO = oh.SHSFXO
				            GROUP BY
				                so.SDKCOO, LTRIM(RTRIM(so.SDMCU)), so.SDDOCO, so.SDLNID/1000.0,
				                LTRIM(RTRIM(so.SDVR01)), LTRIM(RTRIM(so.SDLITM)), LTRIM(RTRIM(so.SDLOTN)),
				                oh.SHHOLD, so.SDLTTR, so.SDNXTR, so.SDUOM1, so.SDTRDJ, so.SDPDDJ, so.SDUOM2,
				                cust.ABAN8, LTRIM(RTRIM(cust.ABALPH)), so.SDDCTO
				        ) Sales5
				            ON Item6.Branch_Plant = Sales5.Branch_Plant
				           AND Item6.C_2nd_Item_Number = Sales5.C_2nd_Item_Number
				        GROUP BY
				            Sales5.Order_Company, Sales5.Branch_Plant, Sales5.Order_Number, Sales5.Order_Line,
				            Sales5.Customer_PO, Sales5.C_2nd_Item_Number, Sales5.Lot_Number, Sales5.Hold_Orders_Code,
				            Sales5.Last_Status, Sales5.Next_Status, Sales5.Primary_UOM, Sales5.Order_Date,
				            Sales5.Promised_Ship_Date, Sales5.Scheduled_Pick_Date, Sales5.Secondary_UOM,
				            Sales5.Customer_Code, Sales5.Customer_Name, Sales5.Order_Type,
				            Item6.Global_Bulk_Item, Item6.Bulk_Item, Item6.C_2nd_Item_Number
				        ",
				        null,
				        [EnableFolding = true]
				    ),
				    Typed = Table.TransformColumnTypes(
				        Data,
				        {
				            {"Order Company", type text}, {"Branch Plant", type text}, {"Global Bulk Item", type text},
				            {"Bulk Item", type text}, {"2nd Item Number", type text}, {"Order Number", Int64.Type},
				            {"Order Line", type number}, {"Customer PO", type text}, {"Lot Number", type text},
				            {"Hold Orders Code", type text}, {"Last Status", type text}, {"Next Status", type text},
				            {"Primary Quantity Ordered", type number}, {"Primary UOM", type text},
				            {"Secondary Quantity Ordered", type number}, {"Secondary UOM", type text},
				            {"Order Date", type date}, {"Promised Ship Date", type date}, {"Scheduled Pick Date", type date},
				            {"Customer Code", Int64.Type}, {"Customer Name", type text}, {"Order Type", type text}
				        },
				        "en-US"
				    )
				in
				    Typed

	annotation PBI_ResultType = Table

