table '19 Item Weights'
	lineageTag: 17130000-0000-4000-8000-000000000001

	column item2nd
		dataType: string
		lineageTag: 17130001-0000-4000-8000-000000000001
		summarizeBy: none
		sourceColumn: item2nd

		annotation SummarizationSetBy = Automatic

	column RowJson
		dataType: string
		lineageTag: 17130001-0000-4000-8000-000000000002
		summarizeBy: none
		sourceColumn: RowJson

		annotation SummarizationSetBy = Automatic

	partition '19 Item Weights' = m
		mode: import
		source =
				let
				    Source = Sql.Database("ODSPROD", "ODS"),
				    Data = Value.NativeQuery(
				        Source,
				        "
				        SET NOCOUNT ON;
				        SELECT LTRIM(RTRIM(im.IMLITM)) AS item2nd,
				               (SELECT im.* FOR JSON PATH, WITHOUT_ARRAY_WRAPPER) AS RowJson
				        FROM PRODDTA.F4101 im
				        WHERE LTRIM(RTRIM(im.IMLITM)) IN (
				        '221127NX.S-B1','221151PX.E-PL','221247PX.E-TO','221255PX.E-PL','221259CX-PL','227140X-T3','227158X','231033CX.E-PD',
				        '231043PX.E-TO','231098PX.E-PL','231316PX.E-PD','241194PX-FD','241194PX-T2','241342PX.S-TL','251194NX.E-B1','251194NX.E-P1',
				        '251194NX.S-PL','251206CX.E-PD','251359PX.E-TO','26006-FD','261044NX.E-PL','26778-PL','26794-T2','ABEX2525.E',
				        'BLND550GM','BLND550GM-T3','CLG2100-T3','CLG2103-T3','CLG2110-T3','CTG102-FD','DF201-JG','DF500-JG',
				        'DF702KIT.E-BX','DG520IJ-FD','DG520IJ-OP','DG520IJ-T2','DG901.E-BX','DG902.E-B1','DGIJ523-T2','DP040-B1',
				        'DP040.E-B1','DP040.E-P1','DP050-P2','DP050-PL','DP050.E-P2','DP050.S-PD','DP050.S-PL','DP050T-T2',
				        'DP060-B1','DP060-P2','DP060-PL','DP060.E-P2','DP060.E-PL','DP060.S-PL','DP6611.S-PL','DP6612.S-B1',
				        'DP6700.S-PL','DP6701.S-PL','DP680-B1','DP680-P1','DP680.E-P1','DP680.S-B1','DPE3500-T2','DPI8000-FD',
				        'DPI8000.E-PL','DPI8000.E-TO','DPI8000.S-PL','DPI8001-FD','DPI8002-FD','DPI8004-FD','DPI8020-FD','DPI8020-PL',
				        'DPI8020.E-PD','DPI8020.E-PL','DPI8020.S-PL','DPI8435.S-PL','DPI8443.S-PL','DPI8445-FD','DPI8445-PL','DPI8445.E-PD',
				        'DPI8445.E-PL','DPI8445.S-PL','DPI8500-FD','DPI8500-PL','DPI8500.E-PL','DPI8500.S-PL','DPI8600-FD','DPI8600.E-TO',
				        'DPR145.E-TO','DPR641.E-TO','DPV9000-B1','DPV9000-P1','DPV9000.E-B1','DPV9000.E-P1','DPV9000.S-B1','DYNA3535PF-FD',
				        'DYNA4-T2','E1002.S-PD','EC4000-T2','EG205-T3','EIF1313-KP','EKF1512.S-PL','EKF1636.S-B1','ENF0922.E-TO',
				        'FDCRED-QT','FGLASSX90.S-T2','GC902H-T3','HL137-PL','HL280-KP','HL496.E-PD','HL723-OP','HL723.E-PD',
				        'HL723.E-TO','HL723.S-PD','HP1632-PL','HSGF1202.E-TO','HSGF1202.S-OP','HUH0002.E-TO','HUH0003.E-TO','HY1000AF-FD',
				        'HY1000AF-T2','HY1000AF-T3','HY420-T2','HY708-OP','HY708.S-PD','HYPOD8510','HYPOD8510-T2','J1751-T2',
				        'JPUV100.E-PD','JPUV120-FD','JPUV120-PL','JPWB1100-FD','JPWB1100-PL','LC410TP-T2','LICA41.E-TO','LICA53.E-TO',
				        'LICADH205.E-TO','LICM55.E-TO','LICOF601.E-TO','LICW11.E-LP','LICW440.E-LP','LIQLUB405-T2','LIQLUB448-FD','LIQLUB454-PL',
				        'MB360LS-OP','MC1548B.E-PL','MC1548B.E-TO','MC218CI4N-OP','MC300.S-PL','MC40EAF-T3','MC40EAF.E-PD','MC40EAF.E-TO',
				        'MC40EATD-FD','MC40HAFN-PL','MC40HHSN-OP','MC40PLUSN-FD','MC40SEN-T3','MC50AFN-FD','MC50AFN-T3','MC81-PL',
				        'MC9100.S-TL','MCL1188-B1','MCL1188.E-P1','MCL1188.S-B1','MD2685-T2','MD7900.E-TO','MD91530-FD','MD91530-KD',
				        'MD91530-PL','MD91530.S-PD','MDU2012B.E-TO','MDU4075B.E-LP','MDU4075B.E-TO','ME05940-FD','ME05940-T2','ME09730-PD',
				        'ME12235.E-PL','ME20117-PD','ME20117-T2','ME21740-FD','ME24035-BP','ME24414-PL','ME24414-T2','ME25317-T3',
				        'ME26726-BP','ME30735-BD','ME34935-T3','ME35940-T3','ME36820B.E-TO','ME36840A.E-PD','ME36840A.E-TO','ME39235-FD',
				        'ME39235-OP','ME39815-T2','ME41740-T2','ME42640-T2','ME44730-FD','ME44730-KP','ME44730-T2','ME44730-T3',
				        'ME47950-FD','ME47950.E-PD','ME47950.E-TO','ME48040M2-FD','ME48040M2-OP','ME51938-T2','ME52137-FD','ME52137-T2',
				        'ME52137I-FD','ME59040.C-OP','ME59150.C-OP','ME59240.C-OP','ME61335-FD','ME61335-T2','ME61335P.E-TO','ME62330-FD',
				        'ME62330-PL','ME62330-T3','ME62330.E-PD','ME62330.E-TO','ME62330.S-T2','ME64422.S-PD','ME66035-FD','ME66035-T3',
				        'ME66035.E-PD','ME66035.E-TO','ME67235','ME67235-T2','ME67335-T3','ME70350A-PD','ME70852.E-TO','ME71152.S-PD',
				        'ME71152.S-PL','ME71731M-FD','ME72650-FD','ME73550-PD','ME77030-FD','ME8905.E','ME89235DE','ME89535DE',
				        'ME91240G.E-PD','ME91240G.E-TO','ME91240G.S-PD','ME91735-FD','ME91735-PL','ME91735-T3','ME91735.E-TO','ME92040.S-PD',
				        'ME93135M-PL','ME93204.E-PD','ME93204.E-TO','ME93235-FD','ME93235-T3','ME93235.S-PD','ME93235A.E-PL','ME93235A.E-TO',
				        'ME93316-FD','ME93335.E-TO','ME93635-PL','ME93935-FD','ME93935.S-PD','ME94240-FD','ME94340-FD','ME94340-PL',
				        'ME94340-T2','ME94340.E-PD','ME94340.S-OP','ME94340.S-PD','ME94340.S-TL','ME95535.S-PD','ME98740-FD','MF1204.S-TL',
				        'MF1306D.S-PD','MF1406.S-PD','MF4915.E-TO','MFB1002.E-PD','MFB1002.E-PL','MFB1002.E-TO','MFB1002.S-PD','MFB5770.S-OP',
				        'MFB5770.S-PL','MFHS9105.E-PD','MFHS9105.E-PL','MFHS9105.E-TO','MFHS9121.E','MFP1808.E-TO','MFP1852-FD','MFP1853R-FD',
				        'MFP1853R.E-PD','MFP1855.E-PD','MFP1883.E-PL','MFP2300.E-PD','MFP2300.E-PL','MFP2300.E-TO','MFP2300.S-PD','MFP2300.S-T2',
				        'MFP2312-T3','MFR1924A-KP','MFR1924A.E-TO','MFR1924A.S-PD','MFR1924A.S-PL','MG7140.S-OP','MGRD200-FD','MGRD200-T3',
				        'MGRD349.S-OP','MGRD350.E-PL','MGRD4223-FD','MGRD7140-FD','MGRD7140-T2','MI001.E-BX','MI102-ML','MI102.E-BX',
				        'MI102.S-ML','MI766RN-T3','MI783-FD','MI783-PL','MIREZ25','MIWAX127','ML124-FD','ML124.S-OP',
				        'ML135-FD','ML135-PL','ML135.S-PD','ML156-FD','ML156-T3','ML156HSF-FD','ML156PFP-FD','ML156PFP.E-PL',
				        'ML156PFP.S-PD','ML160-FD','ML160F-FD','ML160P-KP','ML160PFP-FD','ML160PFP-T2','ML160PFP.E-PD','ML160PFP.E-PL',
				        'ML160PFP.E-TO','ML160PFP.S-PD','ML160RPH-FD','ML182-FD','ML190.E-PL','ML190.E-TO','ML190.S-PD','ML190.S-PL',
				        'ML193.S-PD','ML193P.E-TO','ML215P.E','ML270R-FD','ML270R-UN','ML270R.S-OP','ML368A.E-TO','ML511-FD',
				        'ML511-PL','ML511-T3','ML693-FD','ML693-T2','ML693-T3','ML723-FD','ML723-PL','ML723-T3',
				        'ML723HSP.E-PL','ML723HSP.E-TO','ML743-FD','ML743-T2','ML743-T3','ML985-PL','MP04422R-FD','MP2960-T2',
				        'MP2960.E-TO','MP34040-FD','MP48525R-FD','MP48525R-T2','MP4932.E-PD','MP498340D','MP498340R-KP','MP4983R',
				        'MP4983R-FD','MP4983R-T2','MP4983R-T3','MP4983R.E','MP4983R.E-PD','MP4983R.E-TO','MP4983R.S-PD','MP4983RN-FD',
				        'MS20LV-FD','MT242AF-PL','MT445AF-PL','MWC44.E-PD','MWC50-FD','MWC50-T3','MWC70LV-FD','MWC75-T3',
				        'NM70AFN-PL','NM70N2G-OP','NM70NR-FD','NM70NR-OP','NM70TN-FD','NM70TN.E-TO','NM73-PL','NM73-T3',
				        'NM73.E-TO','NM73R-FD','NM73R-PL','NM73R-T3','NSHLD30-FD','NVLF4002.E-LP','NVLF4002.E-PL','NVLF4605.E-PD',
				        'NVLF4605.E-PL','NYS2010.E-TO','NYS2103.E-TO','NYS2104.S-OP','NYS2203.E-PD','PA845H-OP','PD.E','PH00007E.E-PD',
				        'PH00007E.E-TO','PH00017E-OP','PH00017E-T2','PH00017E.E-TO','PH00019E.S-PD','PH00101E-OP','PH00101E-T3','PH00102E.E-PD',
				        'PH00102E.E-PL','PH00102E.S-PD','PH00102E.S-TL','PH90901L.E-TO','PK263-T3','PK265AP-T3','PK265D','PK265D-KP',
				        'PK265D-PL','PK265D-T3','PK521-T3','PP201-OP','PP201.E','PP201.E-TO','PP201.S-TL','Q4310A-PL',
				        'Q4310A.E-B1','Q4310A.S-B1','Q4324A-B1','Q4324A.E-B1','Q4324A.E-P1','Q4325A.E-B1','RB105-FD','RB105-PL',
				        'RB105-T3','RB110-PL','RB250-OP','RB250-PL','RC39AFG-OP','RC39AFG-T3','RC39AFR-FD','RCPLUSFG-OP',
				        'RCPLUSFG-T3','RCPLUSFR-OP','RCPLUSFR-T3','RLC40-FD','SDP500-PL','ST201-FD','ST2637.E-PD','ST865-UN',
				        'TECOATC.E-TO','TSM312.S-TL','U2022-PL','U502-OP','UBD211-T3','URT711-T2','UV1-PL','VAP2200R-FD',
				        'VAP2200R-KP','VAP2200R-PL','VAP2200R-T2','VAP2200R-T3','VAPCT2200.E-TO','VAPCT2200.S-OP','VAPCT2200.S-PL','VAPCT501H-T3',
				        'VAPCT501S-T2','VAPCT501S-T3','VB200-T3','VBS0800.E-TO','VC1292.E-TO','VC1300.E-PD','VC1300.E-PL','VC2200K-T3',
				        'VC2200W-T3','VC2240.E-PD','VC2240.E-PL','X1440H-FD','X1440HAP','X3000H-FD','X3000H-PL','X300AF-FD',
				        'X300AF-PL','X300AF-T3','X300EAF.E-PD','ZX1-FD'
				        )
				        ORDER BY LTRIM(RTRIM(im.IMLITM));
				        ",
				        null,
				        [EnableFolding = false]
				    ),
				    Typed = Table.TransformColumnTypes(Data, {
							{"item2nd", type text},
							{"RowJson", type text}
				    }, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table

