table Safety_Stock_HP
	lineageTag: 8f8d6925-2575-4181-ac85-27fbd2f9685f

	column REGION
		dataType: string
		lineageTag: db2eac05-faa2-4c15-b3e9-36937dc0aed8
		summarizeBy: none
		sourceColumn: REGION

		annotation SummarizationSetBy = Automatic

	column 'Branch Plant'
		dataType: string
		lineageTag: 2b33c272-4612-41cb-81c1-670fb3c3acf3
		summarizeBy: none
		sourceColumn: Branch Plant

		annotation SummarizationSetBy = Automatic

	column 'Global Bulk Item'
		dataType: string
		lineageTag: 4278a903-3bcd-41df-9e68-f666944feb7c
		summarizeBy: none
		sourceColumn: Global Bulk Item

		annotation SummarizationSetBy = Automatic

	column 'Bulk Item'
		dataType: string
		lineageTag: b4816950-4e9e-4504-a7f5-f4df7b474927
		summarizeBy: none
		sourceColumn: Bulk Item

		annotation SummarizationSetBy = Automatic

	column '2nd Item Number'
		dataType: string
		lineageTag: eaf7c4f4-549e-4306-87b6-0bc7ebebe688
		summarizeBy: none
		sourceColumn: 2nd Item Number

		annotation SummarizationSetBy = Automatic

	column 'Primary UOM'
		dataType: string
		lineageTag: aca8524b-09a5-4116-87e4-eee6ba5cce94
		summarizeBy: none
		sourceColumn: Primary UOM

		annotation SummarizationSetBy = Automatic

	column 'Safety Stock'
		dataType: double
		formatString: #,0
		lineageTag: 3b8f3bab-34ef-43f4-ad64-4d992fc830e7
		summarizeBy: none
		sourceColumn: Safety Stock

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'LB Safety Stock'
		dataType: double
		formatString: #,0
		lineageTag: d619a04e-121e-41b3-9774-ba67fb953e73
		summarizeBy: none
		sourceColumn: LB Safety Stock

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	partition Safety_Stock_HP = m
		mode: import
		source =
				let
				    Source = Sql.Database("ODSPROD", "ODS"),
				    Data = Value.NativeQuery(
				        Source,
				        "
				        SELECT DISTINCT
				            CASE LTRIM(RTRIM(ib.IBMCU))
				                 WHEN 'CINC' THEN 'Americas'
				                 WHEN 'CIN2' THEN 'Americas'
				                 WHEN 'CIN4' THEN 'Americas'
				                 WHEN 'AUBA' THEN 'EMEA'
				                 WHEN 'AUB2' THEN 'EMEA'
				                 WHEN 'SING' THEN 'PacRim'
				                 WHEN 'SNG4' THEN 'PacRim'
				                 WHEN 'MUM3' THEN 'India'
				                 WHEN 'SHAN' THEN 'China'
				            END                                     AS [REGION],
				            LTRIM(RTRIM(ib.IBMCU))                  AS [Branch Plant],
				            LTRIM(RTRIM(tag.IMGBLK))                AS [Global Bulk Item],
				            LTRIM(RTRIM(tag.IMBULK))                AS [Bulk Item],
				            LTRIM(RTRIM(ib.IBLITM))                 AS [2nd Item Number],
				            im.IMUOM1                               AS [Primary UOM],
				            ib.IBSAFE/10000.0                       AS [Safety Stock],
				            CASE WHEN im.IMUOM1 = 'LB' THEN ib.IBSAFE/10000.0
				                 WHEN im.IMUOM1 = 'KG' THEN (ib.IBSAFE/10000.0) / 0.453593
				                 WHEN im.IMUOM1 = 'EA' THEN (ib.IBSAFE/10000.0) * 40
				                 ELSE 0
				            END                                     AS [LB Safety Stock]
				        FROM PRODDTA.F4102 ib
				        JOIN PRODDTA.F4101   im  ON ib.IBITM = im.IMITM
				        JOIN PRODDTA.F554101 tag ON im.IMITM = tag.IMITM
				        WHERE LTRIM(RTRIM(ib.IBMCU)) IN ('AUBA', 'AUB2', 'SING', 'SNG4', 'SHAN', 'MUM3')
				          AND LTRIM(RTRIM(tag.IMBULK)) IN ('JS168.S', 'ME91735.S', 'ME92040.S', 'PP05S.S', 'ME91240G.S', 'MG7140.S', 'TSPP01.S', 'ME92040.S', 'ME91735.S', 'ME87235.S', 'ME91735.S', 'ME90640.S', '211018IX.S', 'ME92040.S', 'PP236A.S', 'NYS2104.S', 'PP236A.S', 'ME91240G.S', 'JS168.E', 'ME92040.S', 'PP236A.S', 'ME91240G.S', 'ME91735.S', 'ME91735.S', 'ME91735.S', 'BRIJS2.S', 'BRIJS20.S', 'JS168.E', 'BRIJS2.E', 'BRIJS20.E', 'ME91735.E')
				        ",
				        null,
				        [EnableFolding = true]
				    ),
				    Typed = Table.TransformColumnTypes(
				        Data,
				        {
				            {"REGION", type text},
				            {"Branch Plant", type text},
				            {"Global Bulk Item", type text},
				            {"Bulk Item", type text},
				            {"2nd Item Number", type text},
				            {"Primary UOM", type text},
				            {"Safety Stock", type number},
				            {"LB Safety Stock", type number}
				        },
				        "en-US"
				    )
				in
				    Typed

	annotation PBI_ResultType = Table

